//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.ed254;

import java.math.BigInteger;
import javax.xml.datatype.Duration;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;
import aero.fixm.base.RunwayDirectionDesignatorType;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the aero.fixm.ed254 package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private static final QName _FlightAmanStrategyAmanStrategyIdentifier_QNAME = new QName("http://coopans.org/swim/ed254/arrivalSequence/1.0", "amanStrategyIdentifier");
    private static final QName _ArrivalSequenceSequenceEntriesArrivalManagementInformationArrivalManagementHandlingIndicator_QNAME = new QName("http://coopans.org/swim/ed254/arrivalSequence/1.0", "arrivalManagementHandlingIndicator");
    private static final QName _ArrivalSequenceSequenceEntriesArrivalManagementInformationSequenceNumber_QNAME = new QName("http://coopans.org/swim/ed254/arrivalSequence/1.0", "sequenceNumber");
    private static final QName _ArrivalSequenceSequenceEntriesArrivalManagementInformationAssignedArrivalRunway_QNAME = new QName("http://coopans.org/swim/ed254/arrivalSequence/1.0", "assignedArrivalRunway");
    private static final QName _ArrivalSequenceSequenceEntriesArrivalManagementInformationDepartureAirportTimeToLoseOnTheGround_QNAME = new QName("http://coopans.org/swim/ed254/arrivalSequence/1.0", "timeToLoseOnTheGround");
    private static final QName _ArrivalSequenceSequenceEntriesArrivalManagementInformationLandingPositionLandingSequencePosition_QNAME = new QName("http://coopans.org/swim/ed254/arrivalSequence/1.0", "landingSequencePosition");
    private static final QName _ArrivalSequenceSequenceEntriesArrivalManagementInformationProposedProcedureAdvisedHoldingProcedure_QNAME = new QName("http://coopans.org/swim/ed254/arrivalSequence/1.0", "advisedHoldingProcedure");
    private static final QName _ArrivalSequenceSequenceEntriesArrivalManagementInformationProposedProcedureAdvisedSTAR_QNAME = new QName("http://coopans.org/swim/ed254/arrivalSequence/1.0", "advisedSTAR");
    private static final QName _ArrivalSequenceSequenceEntriesArrivalManagementInformationProposedProcedureAdvisedTransition_QNAME = new QName("http://coopans.org/swim/ed254/arrivalSequence/1.0", "advisedTransition");
    private static final QName _ArrivalSequenceSequenceEntriesArrivalManagementInformationTotalDelayArrivalDelay_QNAME = new QName("http://coopans.org/swim/ed254/arrivalSequence/1.0", "arrivalDelay");
    private static final QName _ArrivalSequenceSequenceEntriesArrivalManagementInformationMeteringInformationDelayAtPoint_QNAME = new QName("http://coopans.org/swim/ed254/arrivalSequence/1.0", "delayAtPoint");
    private static final QName _ArrivalSequenceSequenceEntriesArrivalManagementInformationMeteringInformationAdvisoryInformationConstraintCTA_QNAME = new QName("http://coopans.org/swim/ed254/arrivalSequence/1.0", "constraintCTA");
    private static final QName _ArrivalSequenceSequenceEntriesArrivalManagementInformationMeteringInformationAdvisoryInformationRouteAdvisory_QNAME = new QName("http://coopans.org/swim/ed254/arrivalSequence/1.0", "routeAdvisory");
    private static final QName _ArrivalSequenceSequenceEntriesArrivalManagementInformationMeteringInformationAdvisoryInformationSpeedAdvisory_QNAME = new QName("http://coopans.org/swim/ed254/arrivalSequence/1.0", "speedAdvisory");
    private static final QName _ArrivalSequenceSequenceEntriesArrivalManagementInformationMeteringInformationAdvisoryInformationTimeToGainOrLose_QNAME = new QName("http://coopans.org/swim/ed254/arrivalSequence/1.0", "timeToGainOrLose");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: aero.fixm.ed254
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ArrivalSequence }
     * 
     * @return
     *     the new instance of {@link ArrivalSequence }
     */
    public ArrivalSequence createArrivalSequence() {
        return new ArrivalSequence();
    }

    /**
     * Create an instance of {@link ArrivalSequence.SequenceEntries }
     * 
     * @return
     *     the new instance of {@link ArrivalSequence.SequenceEntries }
     */
    public ArrivalSequence.SequenceEntries createArrivalSequenceSequenceEntries() {
        return new ArrivalSequence.SequenceEntries();
    }

    /**
     * Create an instance of {@link ArrivalSequence.SequenceEntries.ArrivalManagementInformation }
     * 
     * @return
     *     the new instance of {@link ArrivalSequence.SequenceEntries.ArrivalManagementInformation }
     */
    public ArrivalSequence.SequenceEntries.ArrivalManagementInformation createArrivalSequenceSequenceEntriesArrivalManagementInformation() {
        return new ArrivalSequence.SequenceEntries.ArrivalManagementInformation();
    }

    /**
     * Create an instance of {@link ArrivalSequence.SequenceEntries.ArrivalManagementInformation.MeteringInformation }
     * 
     * @return
     *     the new instance of {@link ArrivalSequence.SequenceEntries.ArrivalManagementInformation.MeteringInformation }
     */
    public ArrivalSequence.SequenceEntries.ArrivalManagementInformation.MeteringInformation createArrivalSequenceSequenceEntriesArrivalManagementInformationMeteringInformation() {
        return new ArrivalSequence.SequenceEntries.ArrivalManagementInformation.MeteringInformation();
    }

    /**
     * Create an instance of {@link ArrivalSequence.ApplicableStrategyPerSequence }
     * 
     * @return
     *     the new instance of {@link ArrivalSequence.ApplicableStrategyPerSequence }
     */
    public ArrivalSequence.ApplicableStrategyPerSequence createArrivalSequenceApplicableStrategyPerSequence() {
        return new ArrivalSequence.ApplicableStrategyPerSequence();
    }

    /**
     * Create an instance of {@link ProviderExceptions }
     * 
     * @return
     *     the new instance of {@link ProviderExceptions }
     */
    public ProviderExceptions createProviderExceptions() {
        return new ProviderExceptions();
    }

    /**
     * Create an instance of {@link FlightAmanStrategy }
     * 
     * @return
     *     the new instance of {@link FlightAmanStrategy }
     */
    public FlightAmanStrategy createFlightAmanStrategy() {
        return new FlightAmanStrategy();
    }

    /**
     * Create an instance of {@link ArrivalSequence.SequenceEntries.ArrivalManagementInformation.FlightIdentification }
     * 
     * @return
     *     the new instance of {@link ArrivalSequence.SequenceEntries.ArrivalManagementInformation.FlightIdentification }
     */
    public ArrivalSequence.SequenceEntries.ArrivalManagementInformation.FlightIdentification createArrivalSequenceSequenceEntriesArrivalManagementInformationFlightIdentification() {
        return new ArrivalSequence.SequenceEntries.ArrivalManagementInformation.FlightIdentification();
    }

    /**
     * Create an instance of {@link ArrivalSequence.SequenceEntries.ArrivalManagementInformation.CustomWakeTurbulenceCategory }
     * 
     * @return
     *     the new instance of {@link ArrivalSequence.SequenceEntries.ArrivalManagementInformation.CustomWakeTurbulenceCategory }
     */
    public ArrivalSequence.SequenceEntries.ArrivalManagementInformation.CustomWakeTurbulenceCategory createArrivalSequenceSequenceEntriesArrivalManagementInformationCustomWakeTurbulenceCategory() {
        return new ArrivalSequence.SequenceEntries.ArrivalManagementInformation.CustomWakeTurbulenceCategory();
    }

    /**
     * Create an instance of {@link ArrivalSequence.SequenceEntries.ArrivalManagementInformation.FlightIsPriorityHandled }
     * 
     * @return
     *     the new instance of {@link ArrivalSequence.SequenceEntries.ArrivalManagementInformation.FlightIsPriorityHandled }
     */
    public ArrivalSequence.SequenceEntries.ArrivalManagementInformation.FlightIsPriorityHandled createArrivalSequenceSequenceEntriesArrivalManagementInformationFlightIsPriorityHandled() {
        return new ArrivalSequence.SequenceEntries.ArrivalManagementInformation.FlightIsPriorityHandled();
    }

    /**
     * Create an instance of {@link ArrivalSequence.SequenceEntries.ArrivalManagementInformation.TotalDelay }
     * 
     * @return
     *     the new instance of {@link ArrivalSequence.SequenceEntries.ArrivalManagementInformation.TotalDelay }
     */
    public ArrivalSequence.SequenceEntries.ArrivalManagementInformation.TotalDelay createArrivalSequenceSequenceEntriesArrivalManagementInformationTotalDelay() {
        return new ArrivalSequence.SequenceEntries.ArrivalManagementInformation.TotalDelay();
    }

    /**
     * Create an instance of {@link ArrivalSequence.SequenceEntries.ArrivalManagementInformation.ProposedProcedure }
     * 
     * @return
     *     the new instance of {@link ArrivalSequence.SequenceEntries.ArrivalManagementInformation.ProposedProcedure }
     */
    public ArrivalSequence.SequenceEntries.ArrivalManagementInformation.ProposedProcedure createArrivalSequenceSequenceEntriesArrivalManagementInformationProposedProcedure() {
        return new ArrivalSequence.SequenceEntries.ArrivalManagementInformation.ProposedProcedure();
    }

    /**
     * Create an instance of {@link ArrivalSequence.SequenceEntries.ArrivalManagementInformation.LandingPosition }
     * 
     * @return
     *     the new instance of {@link ArrivalSequence.SequenceEntries.ArrivalManagementInformation.LandingPosition }
     */
    public ArrivalSequence.SequenceEntries.ArrivalManagementInformation.LandingPosition createArrivalSequenceSequenceEntriesArrivalManagementInformationLandingPosition() {
        return new ArrivalSequence.SequenceEntries.ArrivalManagementInformation.LandingPosition();
    }

    /**
     * Create an instance of {@link ArrivalSequence.SequenceEntries.ArrivalManagementInformation.DepartureAirport }
     * 
     * @return
     *     the new instance of {@link ArrivalSequence.SequenceEntries.ArrivalManagementInformation.DepartureAirport }
     */
    public ArrivalSequence.SequenceEntries.ArrivalManagementInformation.DepartureAirport createArrivalSequenceSequenceEntriesArrivalManagementInformationDepartureAirport() {
        return new ArrivalSequence.SequenceEntries.ArrivalManagementInformation.DepartureAirport();
    }

    /**
     * Create an instance of {@link ArrivalSequence.SequenceEntries.ArrivalManagementInformation.MeteringInformation.AdvisoryInformation }
     * 
     * @return
     *     the new instance of {@link ArrivalSequence.SequenceEntries.ArrivalManagementInformation.MeteringInformation.AdvisoryInformation }
     */
    public ArrivalSequence.SequenceEntries.ArrivalManagementInformation.MeteringInformation.AdvisoryInformation createArrivalSequenceSequenceEntriesArrivalManagementInformationMeteringInformationAdvisoryInformation() {
        return new ArrivalSequence.SequenceEntries.ArrivalManagementInformation.MeteringInformation.AdvisoryInformation();
    }

    /**
     * Create an instance of {@link ArrivalSequence.ApplicableStrategyPerSequence.FlightAmanStrategies }
     * 
     * @return
     *     the new instance of {@link ArrivalSequence.ApplicableStrategyPerSequence.FlightAmanStrategies }
     */
    public ArrivalSequence.ApplicableStrategyPerSequence.FlightAmanStrategies createArrivalSequenceApplicableStrategyPerSequenceFlightAmanStrategies() {
        return new ArrivalSequence.ApplicableStrategyPerSequence.FlightAmanStrategies();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://coopans.org/swim/ed254/arrivalSequence/1.0", name = "amanStrategyIdentifier", scope = FlightAmanStrategy.class)
    public JAXBElement<String> createFlightAmanStrategyAmanStrategyIdentifier(String value) {
        return new JAXBElement<>(_FlightAmanStrategyAmanStrategyIdentifier_QNAME, String.class, FlightAmanStrategy.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://coopans.org/swim/ed254/arrivalSequence/1.0", name = "arrivalManagementHandlingIndicator", scope = ArrivalSequence.SequenceEntries.ArrivalManagementInformation.class)
    public JAXBElement<String> createArrivalSequenceSequenceEntriesArrivalManagementInformationArrivalManagementHandlingIndicator(String value) {
        return new JAXBElement<>(_ArrivalSequenceSequenceEntriesArrivalManagementInformationArrivalManagementHandlingIndicator_QNAME, String.class, ArrivalSequence.SequenceEntries.ArrivalManagementInformation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://coopans.org/swim/ed254/arrivalSequence/1.0", name = "sequenceNumber", scope = ArrivalSequence.SequenceEntries.ArrivalManagementInformation.class)
    public JAXBElement<String> createArrivalSequenceSequenceEntriesArrivalManagementInformationSequenceNumber(String value) {
        return new JAXBElement<>(_ArrivalSequenceSequenceEntriesArrivalManagementInformationSequenceNumber_QNAME, String.class, ArrivalSequence.SequenceEntries.ArrivalManagementInformation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RunwayDirectionDesignatorType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RunwayDirectionDesignatorType }{@code >}
     */
    @XmlElementDecl(namespace = "http://coopans.org/swim/ed254/arrivalSequence/1.0", name = "assignedArrivalRunway", scope = ArrivalSequence.SequenceEntries.ArrivalManagementInformation.class)
    public JAXBElement<RunwayDirectionDesignatorType> createArrivalSequenceSequenceEntriesArrivalManagementInformationAssignedArrivalRunway(RunwayDirectionDesignatorType value) {
        return new JAXBElement<>(_ArrivalSequenceSequenceEntriesArrivalManagementInformationAssignedArrivalRunway_QNAME, RunwayDirectionDesignatorType.class, ArrivalSequence.SequenceEntries.ArrivalManagementInformation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "http://coopans.org/swim/ed254/arrivalSequence/1.0", name = "timeToLoseOnTheGround", scope = ArrivalSequence.SequenceEntries.ArrivalManagementInformation.DepartureAirport.class)
    public JAXBElement<BigInteger> createArrivalSequenceSequenceEntriesArrivalManagementInformationDepartureAirportTimeToLoseOnTheGround(BigInteger value) {
        return new JAXBElement<>(_ArrivalSequenceSequenceEntriesArrivalManagementInformationDepartureAirportTimeToLoseOnTheGround_QNAME, BigInteger.class, ArrivalSequence.SequenceEntries.ArrivalManagementInformation.DepartureAirport.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "http://coopans.org/swim/ed254/arrivalSequence/1.0", name = "landingSequencePosition", scope = ArrivalSequence.SequenceEntries.ArrivalManagementInformation.LandingPosition.class)
    public JAXBElement<BigInteger> createArrivalSequenceSequenceEntriesArrivalManagementInformationLandingPositionLandingSequencePosition(BigInteger value) {
        return new JAXBElement<>(_ArrivalSequenceSequenceEntriesArrivalManagementInformationLandingPositionLandingSequencePosition_QNAME, BigInteger.class, ArrivalSequence.SequenceEntries.ArrivalManagementInformation.LandingPosition.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://coopans.org/swim/ed254/arrivalSequence/1.0", name = "advisedHoldingProcedure", scope = ArrivalSequence.SequenceEntries.ArrivalManagementInformation.ProposedProcedure.class)
    public JAXBElement<String> createArrivalSequenceSequenceEntriesArrivalManagementInformationProposedProcedureAdvisedHoldingProcedure(String value) {
        return new JAXBElement<>(_ArrivalSequenceSequenceEntriesArrivalManagementInformationProposedProcedureAdvisedHoldingProcedure_QNAME, String.class, ArrivalSequence.SequenceEntries.ArrivalManagementInformation.ProposedProcedure.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://coopans.org/swim/ed254/arrivalSequence/1.0", name = "advisedSTAR", scope = ArrivalSequence.SequenceEntries.ArrivalManagementInformation.ProposedProcedure.class)
    public JAXBElement<String> createArrivalSequenceSequenceEntriesArrivalManagementInformationProposedProcedureAdvisedSTAR(String value) {
        return new JAXBElement<>(_ArrivalSequenceSequenceEntriesArrivalManagementInformationProposedProcedureAdvisedSTAR_QNAME, String.class, ArrivalSequence.SequenceEntries.ArrivalManagementInformation.ProposedProcedure.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://coopans.org/swim/ed254/arrivalSequence/1.0", name = "advisedTransition", scope = ArrivalSequence.SequenceEntries.ArrivalManagementInformation.ProposedProcedure.class)
    public JAXBElement<String> createArrivalSequenceSequenceEntriesArrivalManagementInformationProposedProcedureAdvisedTransition(String value) {
        return new JAXBElement<>(_ArrivalSequenceSequenceEntriesArrivalManagementInformationProposedProcedureAdvisedTransition_QNAME, String.class, ArrivalSequence.SequenceEntries.ArrivalManagementInformation.ProposedProcedure.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "http://coopans.org/swim/ed254/arrivalSequence/1.0", name = "arrivalDelay", scope = ArrivalSequence.SequenceEntries.ArrivalManagementInformation.TotalDelay.class)
    public JAXBElement<BigInteger> createArrivalSequenceSequenceEntriesArrivalManagementInformationTotalDelayArrivalDelay(BigInteger value) {
        return new JAXBElement<>(_ArrivalSequenceSequenceEntriesArrivalManagementInformationTotalDelayArrivalDelay_QNAME, BigInteger.class, ArrivalSequence.SequenceEntries.ArrivalManagementInformation.TotalDelay.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Duration }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Duration }{@code >}
     */
    @XmlElementDecl(namespace = "http://coopans.org/swim/ed254/arrivalSequence/1.0", name = "delayAtPoint", scope = ArrivalSequence.SequenceEntries.ArrivalManagementInformation.MeteringInformation.class)
    public JAXBElement<Duration> createArrivalSequenceSequenceEntriesArrivalManagementInformationMeteringInformationDelayAtPoint(Duration value) {
        return new JAXBElement<>(_ArrivalSequenceSequenceEntriesArrivalManagementInformationMeteringInformationDelayAtPoint_QNAME, Duration.class, ArrivalSequence.SequenceEntries.ArrivalManagementInformation.MeteringInformation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://coopans.org/swim/ed254/arrivalSequence/1.0", name = "constraintCTA", scope = ArrivalSequence.SequenceEntries.ArrivalManagementInformation.MeteringInformation.AdvisoryInformation.class)
    public JAXBElement<XMLGregorianCalendar> createArrivalSequenceSequenceEntriesArrivalManagementInformationMeteringInformationAdvisoryInformationConstraintCTA(XMLGregorianCalendar value) {
        return new JAXBElement<>(_ArrivalSequenceSequenceEntriesArrivalManagementInformationMeteringInformationAdvisoryInformationConstraintCTA_QNAME, XMLGregorianCalendar.class, ArrivalSequence.SequenceEntries.ArrivalManagementInformation.MeteringInformation.AdvisoryInformation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://coopans.org/swim/ed254/arrivalSequence/1.0", name = "routeAdvisory", scope = ArrivalSequence.SequenceEntries.ArrivalManagementInformation.MeteringInformation.AdvisoryInformation.class)
    public JAXBElement<String> createArrivalSequenceSequenceEntriesArrivalManagementInformationMeteringInformationAdvisoryInformationRouteAdvisory(String value) {
        return new JAXBElement<>(_ArrivalSequenceSequenceEntriesArrivalManagementInformationMeteringInformationAdvisoryInformationRouteAdvisory_QNAME, String.class, ArrivalSequence.SequenceEntries.ArrivalManagementInformation.MeteringInformation.AdvisoryInformation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://coopans.org/swim/ed254/arrivalSequence/1.0", name = "speedAdvisory", scope = ArrivalSequence.SequenceEntries.ArrivalManagementInformation.MeteringInformation.AdvisoryInformation.class)
    public JAXBElement<String> createArrivalSequenceSequenceEntriesArrivalManagementInformationMeteringInformationAdvisoryInformationSpeedAdvisory(String value) {
        return new JAXBElement<>(_ArrivalSequenceSequenceEntriesArrivalManagementInformationMeteringInformationAdvisoryInformationSpeedAdvisory_QNAME, String.class, ArrivalSequence.SequenceEntries.ArrivalManagementInformation.MeteringInformation.AdvisoryInformation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "http://coopans.org/swim/ed254/arrivalSequence/1.0", name = "timeToGainOrLose", scope = ArrivalSequence.SequenceEntries.ArrivalManagementInformation.MeteringInformation.AdvisoryInformation.class)
    public JAXBElement<BigInteger> createArrivalSequenceSequenceEntriesArrivalManagementInformationMeteringInformationAdvisoryInformationTimeToGainOrLose(BigInteger value) {
        return new JAXBElement<>(_ArrivalSequenceSequenceEntriesArrivalManagementInformationMeteringInformationAdvisoryInformationTimeToGainOrLose_QNAME, BigInteger.class, ArrivalSequence.SequenceEntries.ArrivalManagementInformation.MeteringInformation.AdvisoryInformation.class, value);
    }

}
