//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.datatype.XMLGregorianCalendar;
import aero.fixm.base.ActualTimeOfArrivalExtensionType;
import aero.fixm.base.GeographicalPositionType;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The time, type of time (wheels-on, in blocks, etc.), and geographical position of the arrival.  [FIXM]
 * 
 * &lt;p&gt;Java class for ActualTimeOfArrivalType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="ActualTimeOfArrivalType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/base/4.3}ActualTimeOfArrivalExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="position" type="{http://www.fixm.aero/base/4.3}GeographicalPositionType" minOccurs="0"/&gt;
 *         &lt;element name="time" type="{http://www.fixm.aero/base/4.3}DateTimeUtcType" minOccurs="0"/&gt;
 *         &lt;element name="type" type="{http://www.fixm.aero/flight/4.3}ArrivalTimeTypeType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ActualTimeOfArrivalType", propOrder = {
    "extension",
    "position",
    "time",
    "type"
})
public class ActualTimeOfArrivalType
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     */
    @XmlElement(nillable = true)
    protected List<ActualTimeOfArrivalExtensionType> extension;
    /**
     * The geographical position associated with the actual time of arrival.  [FIXM]
     * 
     */
    @XmlElementRef(name = "position", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<GeographicalPositionType> position;
    /**
     * The actual time of arrival. [ICAO Doc 4444, Appendix 3, Field Type 17]
     * 
     */
    @XmlElementRef(name = "time", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<XMLGregorianCalendar> time;
    /**
     * The type of arrival time represented. [FIXM]
     * 
     */
    @XmlElementRef(name = "type", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<ArrivalTimeTypeType> type;

    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ActualTimeOfArrivalExtensionType }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<ActualTimeOfArrivalExtensionType> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * The geographical position associated with the actual time of arrival.  [FIXM]
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link GeographicalPositionType }{@code >}
     *     
     */
    public JAXBElement<GeographicalPositionType> getPosition() {
        return position;
    }

    /**
     * Sets the value of the position property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link GeographicalPositionType }{@code >}
     *     
     * @see #getPosition()
     */
    public void setPosition(JAXBElement<GeographicalPositionType> value) {
        this.position = value;
    }

    /**
     * The actual time of arrival. [ICAO Doc 4444, Appendix 3, Field Type 17]
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     * @see #getTime()
     */
    public void setTime(JAXBElement<XMLGregorianCalendar> value) {
        this.time = value;
    }

    /**
     * The type of arrival time represented. [FIXM]
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ArrivalTimeTypeType }{@code >}
     *     
     */
    public JAXBElement<ArrivalTimeTypeType> getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ArrivalTimeTypeType }{@code >}
     *     
     * @see #getType()
     */
    public void setType(JAXBElement<ArrivalTimeTypeType> value) {
        this.type = value;
    }

}
