//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Describes whether the shipment is packed to comply with the limitations prescribed for passenger and cargo aircraft or the limitations for cargo aircraft only.
 * 
 * &lt;p&gt;Java class for AircraftDangerousGoodsLimitationType&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * &lt;pre&gt;{&#064;code
 * &lt;simpleType name="AircraftDangerousGoodsLimitationType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="CARGO_AIRCRAFT_ONLY"/&gt;
 *     &lt;enumeration value="PASSENGER_AND_CARGO_AIRCRAFT"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * }&lt;/pre&gt;
 * 
 */
@XmlType(name = "AircraftDangerousGoodsLimitationType")
@XmlEnum
public enum AircraftDangerousGoodsLimitationType {


    /**
     * Specified that the shipment is packed to comply with the limitations prescribed for the limitations for cargo aircraft only.
     * 
     */
    CARGO_AIRCRAFT_ONLY,

    /**
     * Specified that the shipment is packed to comply with the limitations prescribed for passenger and cargo aircraft.
     * 
     */
    PASSENGER_AND_CARGO_AIRCRAFT;

    public String value() {
        return name();
    }

    public static AircraftDangerousGoodsLimitationType fromValue(String v) {
        return valueOf(v);
    }

}
