//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Indicates the cruise climb will be to an unspecified level at or above the lower level.
 * 
 * &lt;p&gt;Java class for AtOrAboveIndicatorType&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * &lt;pre&gt;{&#064;code
 * &lt;simpleType name="AtOrAboveIndicatorType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="AT_OR_ABOVE_LOWER_LEVEL"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * }&lt;/pre&gt;
 * 
 */
@XmlType(name = "AtOrAboveIndicatorType")
@XmlEnum
public enum AtOrAboveIndicatorType {


    /**
     * Indicates the cruise climb will be to an unspecified level at or above the lower level.
     * 
     */
    AT_OR_ABOVE_LOWER_LEVEL;

    public String value() {
        return name();
    }

    public static AtOrAboveIndicatorType fromValue(String v) {
        return valueOf(v);
    }

}
