//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.datatype.XMLGregorianCalendar;
import aero.fixm.base.BoundaryCrossingExtensionType;
import aero.fixm.base.FlightLevelOrAltitudeChoiceType;
import aero.fixm.base.SignificantPointChoiceType;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Boundary Crossing contains estimate data conveyed between ATS Units during the process of Controller Coordination. [FIXM]
 * 
 * &lt;p&gt;Java class for BoundaryCrossingType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="BoundaryCrossingType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="altitudeInTransition" type="{http://www.fixm.aero/flight/4.3}AltitudeInTransitionType" minOccurs="0"/&gt;
 *         &lt;element name="clearedLevel" type="{http://www.fixm.aero/base/4.3}FlightLevelOrAltitudeChoiceType" minOccurs="0"/&gt;
 *         &lt;element name="crossingPoint" type="{http://www.fixm.aero/base/4.3}SignificantPointChoiceType" minOccurs="0"/&gt;
 *         &lt;element name="crossingTime" type="{http://www.fixm.aero/base/4.3}DateTimeUtcType" minOccurs="0"/&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/base/4.3}BoundaryCrossingExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BoundaryCrossingType", propOrder = {
    "altitudeInTransition",
    "clearedLevel",
    "crossingPoint",
    "crossingTime",
    "extension"
})
public class BoundaryCrossingType
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    /**
     * Negotiated boundary crossing transition altitude.
     * 
     */
    @XmlElementRef(name = "altitudeInTransition", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<AltitudeInTransitionType> altitudeInTransition;
    /**
     * The cleared altitude (flight level) at which the aircraft will cross the boundary crossing point if in level cruising flight or, if the aircraft is climbing or descending at the boundary crossing point, the cleared flight level to which it is proceeding.
     * 
     */
    @XmlElementRef(name = "clearedLevel", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<FlightLevelOrAltitudeChoiceType> clearedLevel;
    /**
     * The point where the flight will cross an ATS facility boundary.
     * 
     */
    @XmlElementRef(name = "crossingPoint", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<SignificantPointChoiceType> crossingPoint;
    /**
     * The estimated time at which a flight will cross the associated boundary crossing point.
     * 
     */
    @XmlElementRef(name = "crossingTime", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<XMLGregorianCalendar> crossingTime;
    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     */
    @XmlElement(nillable = true)
    protected List<BoundaryCrossingExtensionType> extension;

    /**
     * Negotiated boundary crossing transition altitude.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AltitudeInTransitionType }{@code >}
     *     
     */
    public JAXBElement<AltitudeInTransitionType> getAltitudeInTransition() {
        return altitudeInTransition;
    }

    /**
     * Sets the value of the altitudeInTransition property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AltitudeInTransitionType }{@code >}
     *     
     * @see #getAltitudeInTransition()
     */
    public void setAltitudeInTransition(JAXBElement<AltitudeInTransitionType> value) {
        this.altitudeInTransition = value;
    }

    /**
     * The cleared altitude (flight level) at which the aircraft will cross the boundary crossing point if in level cruising flight or, if the aircraft is climbing or descending at the boundary crossing point, the cleared flight level to which it is proceeding.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link FlightLevelOrAltitudeChoiceType }{@code >}
     *     
     */
    public JAXBElement<FlightLevelOrAltitudeChoiceType> getClearedLevel() {
        return clearedLevel;
    }

    /**
     * Sets the value of the clearedLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link FlightLevelOrAltitudeChoiceType }{@code >}
     *     
     * @see #getClearedLevel()
     */
    public void setClearedLevel(JAXBElement<FlightLevelOrAltitudeChoiceType> value) {
        this.clearedLevel = value;
    }

    /**
     * The point where the flight will cross an ATS facility boundary.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link SignificantPointChoiceType }{@code >}
     *     
     */
    public JAXBElement<SignificantPointChoiceType> getCrossingPoint() {
        return crossingPoint;
    }

    /**
     * Sets the value of the crossingPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link SignificantPointChoiceType }{@code >}
     *     
     * @see #getCrossingPoint()
     */
    public void setCrossingPoint(JAXBElement<SignificantPointChoiceType> value) {
        this.crossingPoint = value;
    }

    /**
     * The estimated time at which a flight will cross the associated boundary crossing point.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getCrossingTime() {
        return crossingTime;
    }

    /**
     * Sets the value of the crossingTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     * @see #getCrossingTime()
     */
    public void setCrossingTime(JAXBElement<XMLGregorianCalendar> value) {
        this.crossingTime = value;
    }

    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BoundaryCrossingExtensionType }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<BoundaryCrossingExtensionType> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

}
