//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import aero.fixm.base.CommunicationCapabilitiesExtensionType;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The serviceable communications equipment, available on the aircraft at the time of flight, and associated flight crew qualifications that may be used to communicate with ATS units. [FIXM]
 * 
 * &lt;p&gt;Java class for CommunicationCapabilitiesType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="CommunicationCapabilitiesType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="communicationCapabilityCode" type="{http://www.fixm.aero/flight/4.3}CommunicationCapabilityCodeListType" minOccurs="0"/&gt;
 *         &lt;element name="datalinkCommunicationCapabilityCode" type="{http://www.fixm.aero/flight/4.3}DatalinkCommunicationCapabilityCodeListType" minOccurs="0"/&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/base/4.3}CommunicationCapabilitiesExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="otherCommunicationCapabilities" type="{http://www.fixm.aero/base/4.3}CharacterStringType" minOccurs="0"/&gt;
 *         &lt;element name="otherDatalinkCapabilities" type="{http://www.fixm.aero/base/4.3}CharacterStringType" minOccurs="0"/&gt;
 *         &lt;element name="selectiveCallingCode" type="{http://www.fixm.aero/flight/4.3}SelectiveCallingCodeType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CommunicationCapabilitiesType", propOrder = {
    "communicationCapabilityCode",
    "datalinkCommunicationCapabilityCode",
    "extension",
    "otherCommunicationCapabilities",
    "otherDatalinkCapabilities",
    "selectiveCallingCode"
})
public class CommunicationCapabilitiesType
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    /**
     * A code indicating the capability of the aircraft and associated flight crew qualifications to communicate with ATS units. [FIXM]
     * 
     */
    @XmlElementRef(name = "communicationCapabilityCode", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected List<JAXBElement<List<CommunicationCapabilityCodeType>>> communicationCapabilityCode;
    /**
     * A code indicating the capability of the aircraft to communicate or receive data. [FIXM]
     * 
     */
    @XmlElementRef(name = "datalinkCommunicationCapabilityCode", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected List<JAXBElement<List<DatalinkCommunicationCapabilityCodeType>>> datalinkCommunicationCapabilityCode;
    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     */
    @XmlElement(nillable = true)
    protected List<CommunicationCapabilitiesExtensionType> extension;
    /**
     * Additional Communication capabilities available on the aircraft.
     * 
     */
    @XmlElementRef(name = "otherCommunicationCapabilities", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<String> otherCommunicationCapabilities;
    /**
     * Additional data link capabilities available on the aircraft.
     * 
     */
    @XmlElementRef(name = "otherDatalinkCapabilities", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<String> otherDatalinkCapabilities;
    /**
     * A code that consists of two 2-letter pairs and acts as a paging system for an ATS unit to establish voice communications with the pilot of an aircraft.
     * 
     */
    @XmlElementRef(name = "selectiveCallingCode", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<String> selectiveCallingCode;

    /**
     * A code indicating the capability of the aircraft and associated flight crew qualifications to communicate with ATS units. [FIXM]
     * 
     * Gets the value of the communicationCapabilityCode property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the communicationCapabilityCode property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getCommunicationCapabilityCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link List }{@code <}{@link CommunicationCapabilityCodeType }{@code >}{@code >}
     * </p>
     * 
     * 
     * @return
     *     The value of the communicationCapabilityCode property.
     */
    public List<JAXBElement<List<CommunicationCapabilityCodeType>>> getCommunicationCapabilityCode() {
        if (communicationCapabilityCode == null) {
            communicationCapabilityCode = new ArrayList<>();
        }
        return this.communicationCapabilityCode;
    }

    /**
     * A code indicating the capability of the aircraft to communicate or receive data. [FIXM]
     * 
     * Gets the value of the datalinkCommunicationCapabilityCode property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the datalinkCommunicationCapabilityCode property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getDatalinkCommunicationCapabilityCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link List }{@code <}{@link DatalinkCommunicationCapabilityCodeType }{@code >}{@code >}
     * </p>
     * 
     * 
     * @return
     *     The value of the datalinkCommunicationCapabilityCode property.
     */
    public List<JAXBElement<List<DatalinkCommunicationCapabilityCodeType>>> getDatalinkCommunicationCapabilityCode() {
        if (datalinkCommunicationCapabilityCode == null) {
            datalinkCommunicationCapabilityCode = new ArrayList<>();
        }
        return this.datalinkCommunicationCapabilityCode;
    }

    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CommunicationCapabilitiesExtensionType }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<CommunicationCapabilitiesExtensionType> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * Additional Communication capabilities available on the aircraft.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getOtherCommunicationCapabilities() {
        return otherCommunicationCapabilities;
    }

    /**
     * Sets the value of the otherCommunicationCapabilities property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     * @see #getOtherCommunicationCapabilities()
     */
    public void setOtherCommunicationCapabilities(JAXBElement<String> value) {
        this.otherCommunicationCapabilities = value;
    }

    /**
     * Additional data link capabilities available on the aircraft.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getOtherDatalinkCapabilities() {
        return otherDatalinkCapabilities;
    }

    /**
     * Sets the value of the otherDatalinkCapabilities property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     * @see #getOtherDatalinkCapabilities()
     */
    public void setOtherDatalinkCapabilities(JAXBElement<String> value) {
        this.otherDatalinkCapabilities = value;
    }

    /**
     * A code that consists of two 2-letter pairs and acts as a paging system for an ATS unit to establish voice communications with the pilot of an aircraft.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getSelectiveCallingCode() {
        return selectiveCallingCode;
    }

    /**
     * Sets the value of the selectiveCallingCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     * @see #getSelectiveCallingCode()
     */
    public void setSelectiveCallingCode(JAXBElement<String> value) {
        this.selectiveCallingCode = value;
    }

}
