//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A code indicating the capability of the aircraft and associated flight crew qualifications to communicate with ATS units. [FIXM]
 * 
 * &lt;p&gt;Java class for CommunicationCapabilityCodeType&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * &lt;pre&gt;{&#064;code
 * &lt;simpleType name="CommunicationCapabilityCodeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="E1"/&gt;
 *     &lt;enumeration value="E2"/&gt;
 *     &lt;enumeration value="E3"/&gt;
 *     &lt;enumeration value="H"/&gt;
 *     &lt;enumeration value="M1"/&gt;
 *     &lt;enumeration value="M2"/&gt;
 *     &lt;enumeration value="M3"/&gt;
 *     &lt;enumeration value="P1"/&gt;
 *     &lt;enumeration value="P2"/&gt;
 *     &lt;enumeration value="P3"/&gt;
 *     &lt;enumeration value="P4"/&gt;
 *     &lt;enumeration value="P5"/&gt;
 *     &lt;enumeration value="P6"/&gt;
 *     &lt;enumeration value="P7"/&gt;
 *     &lt;enumeration value="P8"/&gt;
 *     &lt;enumeration value="P9"/&gt;
 *     &lt;enumeration value="U"/&gt;
 *     &lt;enumeration value="V"/&gt;
 *     &lt;enumeration value="Y"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * }&lt;/pre&gt;
 * 
 */
@XmlType(name = "CommunicationCapabilityCodeType")
@XmlEnum
public enum CommunicationCapabilityCodeType {


    /**
     * FMC WPR ACARS
     * 
     */
    @XmlEnumValue("E1")
    E_1("E1"),

    /**
     * D-FIS ACARS
     * 
     */
    @XmlEnumValue("E2")
    E_2("E2"),

    /**
     * PDC ACARS
     * 
     */
    @XmlEnumValue("E3")
    E_3("E3"),

    /**
     * HF RTF
     * 
     */
    H("H"),

    /**
     * ATC RTF SATCOM (INMARSAT)
     * 
     */
    @XmlEnumValue("M1")
    M_1("M1"),

    /**
     * ATC RTF (MTSAT)
     * 
     */
    @XmlEnumValue("M2")
    M_2("M2"),

    /**
     * ATC RTF (Iridium)
     * 
     */
    @XmlEnumValue("M3")
    M_3("M3"),

    /**
     * Reserved for RCP
     * 
     */
    @XmlEnumValue("P1")
    P_1("P1"),

    /**
     * Reserved for RCP
     * 
     */
    @XmlEnumValue("P2")
    P_2("P2"),

    /**
     * Reserved for RCP
     * 
     */
    @XmlEnumValue("P3")
    P_3("P3"),

    /**
     * Reserved for RCP
     * 
     */
    @XmlEnumValue("P4")
    P_4("P4"),

    /**
     * Reserved for RCP
     * 
     */
    @XmlEnumValue("P5")
    P_5("P5"),

    /**
     * Reserved for RCP
     * 
     */
    @XmlEnumValue("P6")
    P_6("P6"),

    /**
     * Reserved for RCP
     * 
     */
    @XmlEnumValue("P7")
    P_7("P7"),

    /**
     * Reserved for RCP
     * 
     */
    @XmlEnumValue("P8")
    P_8("P8"),

    /**
     * Reserved for RCP
     * 
     */
    @XmlEnumValue("P9")
    P_9("P9"),

    /**
     * UHF RTF
     * 
     */
    U("U"),

    /**
     * VHF RTF
     * 
     */
    V("V"),

    /**
     * VHF with 8.33 kHz channel spacing capability
     * 
     */
    Y("Y");
    private final String value;

    CommunicationCapabilityCodeType(String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static CommunicationCapabilityCodeType fromValue(String v) {
        for (CommunicationCapabilityCodeType c: CommunicationCapabilityCodeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
