//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import aero.fixm.base.CruisingSpeedChangeExtensionType;
import aero.fixm.base.TrueAirspeedType;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Describes the new planned speed at the specified point at which the change to the new speed is planned to commence.  (May also describe a point at which the speed change is planned to be attained).
 * 
 * &lt;p&gt;Java class for CruisingSpeedChangeType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="CruisingSpeedChangeType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="activation" type="{http://www.fixm.aero/flight/4.3}ActivationType" minOccurs="0"/&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/base/4.3}CruisingSpeedChangeExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="speed" type="{http://www.fixm.aero/base/4.3}TrueAirspeedType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CruisingSpeedChangeType", propOrder = {
    "activation",
    "extension",
    "speed"
})
public class CruisingSpeedChangeType
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    /**
     * Qualifies the position associated with the speed constraint.
     * 
     */
    @XmlElementRef(name = "activation", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<ActivationType> activation;
    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     */
    @XmlElement(nillable = true)
    protected List<CruisingSpeedChangeExtensionType> extension;
    /**
     * Describes the new planned speed at the specified point at which the change to the new speed is planned to commence
     * .Speed Change: Describes the new planned speed at the specified point at which the change to the new speed is planned to commence.  (May also describe a point at which the speed change is planned to be attained).
     * 
     */
    @XmlElementRef(name = "speed", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<TrueAirspeedType> speed;

    /**
     * Qualifies the position associated with the speed constraint.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ActivationType }{@code >}
     *     
     */
    public JAXBElement<ActivationType> getActivation() {
        return activation;
    }

    /**
     * Sets the value of the activation property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ActivationType }{@code >}
     *     
     * @see #getActivation()
     */
    public void setActivation(JAXBElement<ActivationType> value) {
        this.activation = value;
    }

    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CruisingSpeedChangeExtensionType }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<CruisingSpeedChangeExtensionType> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * Describes the new planned speed at the specified point at which the change to the new speed is planned to commence
     * .Speed Change: Describes the new planned speed at the specified point at which the change to the new speed is planned to commence.  (May also describe a point at which the speed change is planned to be attained).
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link TrueAirspeedType }{@code >}
     *     
     */
    public JAXBElement<TrueAirspeedType> getSpeed() {
        return speed;
    }

    /**
     * Sets the value of the speed property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link TrueAirspeedType }{@code >}
     *     
     * @see #getSpeed()
     */
    public void setSpeed(JAXBElement<TrueAirspeedType> value) {
        this.speed = value;
    }

}
