//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import aero.fixm.base.DangerousGoodsPackageGroupExtensionType;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The part of the IATA Shipper's Declaration For Dangerous Goods that contains the Package Details for the shipment.
 * 
 * &lt;p&gt;Java class for DangerousGoodsPackageGroupType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="DangerousGoodsPackageGroupType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="dangerousGoodsPackage" type="{http://www.fixm.aero/flight/4.3}DangerousGoodsPackageType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/base/4.3}DangerousGoodsPackageGroupExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="shipmentDimensions" type="{http://www.fixm.aero/flight/4.3}DangerousGoodsDimensionsType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DangerousGoodsPackageGroupType", propOrder = {
    "dangerousGoodsPackage",
    "extension",
    "shipmentDimensions"
})
public class DangerousGoodsPackageGroupType
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    /**
     * A collection of at least one DangerousGoodsPackage.
     * 
     */
    @XmlElement(nillable = true)
    protected List<DangerousGoodsPackageType> dangerousGoodsPackage;
    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     */
    @XmlElement(nillable = true)
    protected List<DangerousGoodsPackageGroupExtensionType> extension;
    /**
     * Weight and volume (not height, width, and depth)
     * 
     */
    @XmlElementRef(name = "shipmentDimensions", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<DangerousGoodsDimensionsType> shipmentDimensions;

    /**
     * A collection of at least one DangerousGoodsPackage.
     * 
     * Gets the value of the dangerousGoodsPackage property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the dangerousGoodsPackage property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getDangerousGoodsPackage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DangerousGoodsPackageType }
     * </p>
     * 
     * 
     * @return
     *     The value of the dangerousGoodsPackage property.
     */
    public List<DangerousGoodsPackageType> getDangerousGoodsPackage() {
        if (dangerousGoodsPackage == null) {
            dangerousGoodsPackage = new ArrayList<>();
        }
        return this.dangerousGoodsPackage;
    }

    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DangerousGoodsPackageGroupExtensionType }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<DangerousGoodsPackageGroupExtensionType> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * Weight and volume (not height, width, and depth)
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link DangerousGoodsDimensionsType }{@code >}
     *     
     */
    public JAXBElement<DangerousGoodsDimensionsType> getShipmentDimensions() {
        return shipmentDimensions;
    }

    /**
     * Sets the value of the shipmentDimensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link DangerousGoodsDimensionsType }{@code >}
     *     
     * @see #getShipmentDimensions()
     */
    public void setShipmentDimensions(JAXBElement<DangerousGoodsDimensionsType> value) {
        this.shipmentDimensions = value;
    }

}
