//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import aero.fixm.base.DangerousGoodsExtensionType;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Articles or substances which are capable of posing a risk to health, safety, property or the environment and which are shown in the list of dangerous goods in the Technical Instructions or which are classified according to those Instructions. [ICAO Annex 18]
 * 
 * &lt;p&gt;Java class for DangerousGoodsType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="DangerousGoodsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="aircraftLimitation" type="{http://www.fixm.aero/flight/4.3}AircraftDangerousGoodsLimitationType" minOccurs="0"/&gt;
 *         &lt;element name="airWaybillNumber" type="{http://www.fixm.aero/flight/4.3}AirWaybillNumberType" minOccurs="0"/&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/base/4.3}DangerousGoodsExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="onboardLocation" type="{http://www.fixm.aero/base/4.3}CharacterStringType" minOccurs="0"/&gt;
 *         &lt;element name="packageGroup" type="{http://www.fixm.aero/flight/4.3}DangerousGoodsPackageGroupType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="shippingInformation" type="{http://www.fixm.aero/flight/4.3}ShippingInformationType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DangerousGoodsType", propOrder = {
    "aircraftLimitation",
    "airWaybillNumber",
    "extension",
    "onboardLocation",
    "packageGroup",
    "shippingInformation"
})
public class DangerousGoodsType
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    /**
     * Describes whether the shipment is packed to comply with the limitations prescribed for passenger and cargo aircraft or the limitations for cargo aircraft only.
     * 
     */
    @XmlElementRef(name = "aircraftLimitation", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<AircraftDangerousGoodsLimitationType> aircraftLimitation;
    /**
     * The number referencing the air waybill.
     * 
     */
    @XmlElementRef(name = "airWaybillNumber", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<String> airWaybillNumber;
    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     */
    @XmlElement(nillable = true)
    protected List<DangerousGoodsExtensionType> extension;
    /**
     * The location of a dangerous goods shipment inside the airframe.
     * 
     */
    @XmlElementRef(name = "onboardLocation", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<String> onboardLocation;
    /**
     * A code that indicates the relative degree of danger presented by various articles and substances within a Class or Division.
     * 
     */
    @XmlElement(nillable = true)
    protected List<DangerousGoodsPackageGroupType> packageGroup;
    /**
     * IATA Shipper's Declaration for Dangerous Goods.
     * 
     */
    @XmlElementRef(name = "shippingInformation", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<ShippingInformationType> shippingInformation;

    /**
     * Describes whether the shipment is packed to comply with the limitations prescribed for passenger and cargo aircraft or the limitations for cargo aircraft only.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AircraftDangerousGoodsLimitationType }{@code >}
     *     
     */
    public JAXBElement<AircraftDangerousGoodsLimitationType> getAircraftLimitation() {
        return aircraftLimitation;
    }

    /**
     * Sets the value of the aircraftLimitation property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AircraftDangerousGoodsLimitationType }{@code >}
     *     
     * @see #getAircraftLimitation()
     */
    public void setAircraftLimitation(JAXBElement<AircraftDangerousGoodsLimitationType> value) {
        this.aircraftLimitation = value;
    }

    /**
     * The number referencing the air waybill.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getAirWaybillNumber() {
        return airWaybillNumber;
    }

    /**
     * Sets the value of the airWaybillNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     * @see #getAirWaybillNumber()
     */
    public void setAirWaybillNumber(JAXBElement<String> value) {
        this.airWaybillNumber = value;
    }

    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DangerousGoodsExtensionType }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<DangerousGoodsExtensionType> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * The location of a dangerous goods shipment inside the airframe.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getOnboardLocation() {
        return onboardLocation;
    }

    /**
     * Sets the value of the onboardLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     * @see #getOnboardLocation()
     */
    public void setOnboardLocation(JAXBElement<String> value) {
        this.onboardLocation = value;
    }

    /**
     * A code that indicates the relative degree of danger presented by various articles and substances within a Class or Division.
     * 
     * Gets the value of the packageGroup property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the packageGroup property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getPackageGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DangerousGoodsPackageGroupType }
     * </p>
     * 
     * 
     * @return
     *     The value of the packageGroup property.
     */
    public List<DangerousGoodsPackageGroupType> getPackageGroup() {
        if (packageGroup == null) {
            packageGroup = new ArrayList<>();
        }
        return this.packageGroup;
    }

    /**
     * IATA Shipper's Declaration for Dangerous Goods.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ShippingInformationType }{@code >}
     *     
     */
    public JAXBElement<ShippingInformationType> getShippingInformation() {
        return shippingInformation;
    }

    /**
     * Sets the value of the shippingInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ShippingInformationType }{@code >}
     *     
     * @see #getShippingInformation()
     */
    public void setShippingInformation(JAXBElement<ShippingInformationType> value) {
        this.shippingInformation = value;
    }

}
