//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The type of departure time represented. [FIXM]
 * 
 * &lt;p&gt;Java class for DepartureTimeTypeType&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * &lt;pre&gt;{&#064;code
 * &lt;simpleType name="DepartureTimeTypeType"&gt;
 *   &lt;restriction base="{http://www.fixm.aero/flight/4.3}TrajectoryPointPropertyTypeType"&gt;
 *     &lt;enumeration value="OFF_BLOCKS"/&gt;
 *     &lt;enumeration value="START_TAKEOFF_ROLL"/&gt;
 *     &lt;enumeration value="WHEELS_OFF"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * }&lt;/pre&gt;
 * 
 */
@XmlType(name = "DepartureTimeTypeType")
@XmlEnum(TrajectoryPointPropertyTypeType.class)
public enum DepartureTimeTypeType {


    /**
     * This is the point at which the aircraft pushes back and begins to taxi for departure.
     * 
     */
    OFF_BLOCKS,

    /**
     * Indicates that the associated trajectory point corresponds to the point at the start of take-off roll (used for departures only).
     * 
     */
    START_TAKEOFF_ROLL,

    /**
     * Indicates that the associated trajectory point corresponds to the point at which the aircraft is predicted to be wheels off the runway on departure.
     * 
     */
    WHEELS_OFF;

    public String value() {
        return name();
    }

    public static DepartureTimeTypeType fromValue(String v) {
        return valueOf(v);
    }

}
