//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Indication of the covered/uncovered nature of the dinghies carried by the aircraft. [FIXM]
 * 
 * &lt;p&gt;Java class for DinghyCoverIndicatorType&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * &lt;pre&gt;{&#064;code
 * &lt;simpleType name="DinghyCoverIndicatorType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="COVERED"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * }&lt;/pre&gt;
 * 
 */
@XmlType(name = "DinghyCoverIndicatorType")
@XmlEnum
public enum DinghyCoverIndicatorType {


    /**
     * Indication of the covered/uncovered nature of the dinghies carried by the aircraft. [FIXM]
     * 
     */
    COVERED;

    public String value() {
        return name();
    }

    public static DinghyCoverIndicatorType fromValue(String v) {
        return valueOf(v);
    }

}
