//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import aero.fixm.base.DinghiesExtensionType;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Dinghy information including total capacity in persons of all dinghies carried, indicator if dinghies are covered, their colours and number.  [ICAO Doc 4444, Appendix 2, ITEM 19 D]
 * 
 * &lt;p&gt;Java class for DinghiesType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="DinghiesType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="colour" type="{http://www.fixm.aero/base/4.3}CharacterStringType" minOccurs="0"/&gt;
 *         &lt;element name="covered" type="{http://www.fixm.aero/flight/4.3}DinghyCoverIndicatorType" minOccurs="0"/&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/base/4.3}DinghiesExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="number" type="{http://www.fixm.aero/base/4.3}CountType" minOccurs="0"/&gt;
 *         &lt;element name="totalCapacity" type="{http://www.fixm.aero/base/4.3}CountPositiveType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DinghiesType", propOrder = {
    "colour",
    "covered",
    "extension",
    "number",
    "totalCapacity"
})
public class DinghiesType
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    /**
     * The colour of the dinghies carried by the aircraft. [FIXM]
     * 
     */
    @XmlElementRef(name = "colour", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<String> colour;
    /**
     * Indication of the covered/uncovered nature of the dinghies carried by the aircraft.
     * 
     */
    @XmlElementRef(name = "covered", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<DinghyCoverIndicatorType> covered;
    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     */
    @XmlElement(nillable = true)
    protected List<DinghiesExtensionType> extension;
    /**
     * The number of dinghies carried by the aircraft. [adapted from ICAO Doc 4444, Appendix 2, ITEM 19 D/]
     * 
     */
    @XmlElementRef(name = "number", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<Integer> number;
    /**
     * Total capacity, in persons, of all dinghies carried. [ICAO Doc 4444, Appendix 2, ITEM 19 D/]
     * 
     */
    @XmlElementRef(name = "totalCapacity", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<Integer> totalCapacity;

    /**
     * The colour of the dinghies carried by the aircraft. [FIXM]
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getColour() {
        return colour;
    }

    /**
     * Sets the value of the colour property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     * @see #getColour()
     */
    public void setColour(JAXBElement<String> value) {
        this.colour = value;
    }

    /**
     * Indication of the covered/uncovered nature of the dinghies carried by the aircraft.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link DinghyCoverIndicatorType }{@code >}
     *     
     */
    public JAXBElement<DinghyCoverIndicatorType> getCovered() {
        return covered;
    }

    /**
     * Sets the value of the covered property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link DinghyCoverIndicatorType }{@code >}
     *     
     * @see #getCovered()
     */
    public void setCovered(JAXBElement<DinghyCoverIndicatorType> value) {
        this.covered = value;
    }

    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DinghiesExtensionType }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<DinghiesExtensionType> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * The number of dinghies carried by the aircraft. [adapted from ICAO Doc 4444, Appendix 2, ITEM 19 D/]
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     * @see #getNumber()
     */
    public void setNumber(JAXBElement<Integer> value) {
        this.number = value;
    }

    /**
     * Total capacity, in persons, of all dinghies carried. [ICAO Doc 4444, Appendix 2, ITEM 19 D/]
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getTotalCapacity() {
        return totalCapacity;
    }

    /**
     * Sets the value of the totalCapacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     * @see #getTotalCapacity()
     */
    public void setTotalCapacity(JAXBElement<Integer> value) {
        this.totalCapacity = value;
    }

}
