//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import java.io.Serializable;
import java.math.BigDecimal;
import aero.fixm.base.SignificantPointChoiceType;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The location associated with estimated elapsed time. It can be a longitude, significant point or flight information region.
 * 
 * &lt;p&gt;Java class for ElapsedTimeLocationChoiceType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="ElapsedTimeLocationChoiceType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="longitude" type="{http://www.fixm.aero/base/4.3}LongitudeType"/&gt;
 *         &lt;element name="point" type="{http://www.fixm.aero/base/4.3}SignificantPointChoiceType"/&gt;
 *         &lt;element name="region" type="{http://www.fixm.aero/base/4.3}LocationIndicatorType"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ElapsedTimeLocationChoiceType", propOrder = {
    "longitude",
    "point",
    "region"
})
public class ElapsedTimeLocationChoiceType
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    /**
     * Longitude associated with the elapsed time.
     * 
     */
    protected BigDecimal longitude;
    /**
     * Point associated with the estimated elapsed time.
     * 
     */
    protected SignificantPointChoiceType point;
    /**
     * Flight information boundary associated with the elapsed time.
     * 
     */
    protected String region;

    /**
     * Longitude associated with the elapsed time.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLongitude() {
        return longitude;
    }

    /**
     * Sets the value of the longitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getLongitude()
     */
    public void setLongitude(BigDecimal value) {
        this.longitude = value;
    }

    /**
     * Point associated with the estimated elapsed time.
     * 
     * @return
     *     possible object is
     *     {@link SignificantPointChoiceType }
     *     
     */
    public SignificantPointChoiceType getPoint() {
        return point;
    }

    /**
     * Sets the value of the point property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignificantPointChoiceType }
     *     
     * @see #getPoint()
     */
    public void setPoint(SignificantPointChoiceType value) {
        this.point = value;
    }

    /**
     * Flight information boundary associated with the elapsed time.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegion() {
        return region;
    }

    /**
     * Sets the value of the region property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getRegion()
     */
    public void setRegion(String value) {
        this.region = value;
    }

}
