//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A generic term meaning, as the case may be, uncertainty phase, alert phase or distress phase. [ICAO Annex 11]
 * This is the stage of emergency the flight is currently under, as designated by an ATS unit. [FIXM]
 * 
 * &lt;p&gt;Java class for EmergencyPhaseType&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * &lt;pre&gt;{&#064;code
 * &lt;simpleType name="EmergencyPhaseType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="ALERFA"/&gt;
 *     &lt;enumeration value="DETRESFA"/&gt;
 *     &lt;enumeration value="INCERFA"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * }&lt;/pre&gt;
 * 
 */
@XmlType(name = "EmergencyPhaseType")
@XmlEnum
public enum EmergencyPhaseType {


    /**
     * The code word used to designate an alert phase. [ICAO Annex 11]
     * 
     */
    ALERFA,

    /**
     * The code word used to designate a distress phase. [ICAO Annex 11]
     * 
     */
    DETRESFA,

    /**
     * The code word used to designate an uncertainty phase. [ICAO Annex 11]
     * 
     */
    INCERFA;

    public String value() {
        return name();
    }

    public static EmergencyPhaseType fromValue(String v) {
        return valueOf(v);
    }

}
