//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import aero.fixm.base.AerodromeReferenceType;
import aero.fixm.base.EnRouteExtensionType;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Groups the en route information about the flight.
 * 
 * &lt;p&gt;Java class for EnRouteType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="EnRouteType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="alternateAerodrome" type="{http://www.fixm.aero/base/4.3}AerodromeReferenceType" maxOccurs="20" minOccurs="0"/&gt;
 *         &lt;element name="boundaryCrossingCoordination" type="{http://www.fixm.aero/flight/4.3}BoundaryCrossingType" minOccurs="0"/&gt;
 *         &lt;element name="currentModeACode" type="{http://www.fixm.aero/base/4.3}ModeACodeType" minOccurs="0"/&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/base/4.3}EnRouteExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EnRouteType", propOrder = {
    "alternateAerodrome",
    "boundaryCrossingCoordination",
    "currentModeACode",
    "extension"
})
public class EnRouteType
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    /**
     * An ICAO designator of the aerodrome to which a flight could be diverted while en route, if needed.
     * 
     */
    @XmlElement(nillable = true)
    protected List<AerodromeReferenceType> alternateAerodrome;
    /**
     * A proposed boundary crossing information with associated details including altitude, crossing point and crossing time.
     * 
     */
    @XmlElementRef(name = "boundaryCrossingCoordination", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<BoundaryCrossingType> boundaryCrossingCoordination;
    /**
     * Current assigned Mode A code. [FIXM]
     * 
     */
    @XmlElementRef(name = "currentModeACode", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<String> currentModeACode;
    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     */
    @XmlElement(nillable = true)
    protected List<EnRouteExtensionType> extension;

    /**
     * An ICAO designator of the aerodrome to which a flight could be diverted while en route, if needed.
     * 
     * Gets the value of the alternateAerodrome property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the alternateAerodrome property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getAlternateAerodrome().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AerodromeReferenceType }
     * </p>
     * 
     * 
     * @return
     *     The value of the alternateAerodrome property.
     */
    public List<AerodromeReferenceType> getAlternateAerodrome() {
        if (alternateAerodrome == null) {
            alternateAerodrome = new ArrayList<>();
        }
        return this.alternateAerodrome;
    }

    /**
     * A proposed boundary crossing information with associated details including altitude, crossing point and crossing time.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BoundaryCrossingType }{@code >}
     *     
     */
    public JAXBElement<BoundaryCrossingType> getBoundaryCrossingCoordination() {
        return boundaryCrossingCoordination;
    }

    /**
     * Sets the value of the boundaryCrossingCoordination property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BoundaryCrossingType }{@code >}
     *     
     * @see #getBoundaryCrossingCoordination()
     */
    public void setBoundaryCrossingCoordination(JAXBElement<BoundaryCrossingType> value) {
        this.boundaryCrossingCoordination = value;
    }

    /**
     * Current assigned Mode A code. [FIXM]
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCurrentModeACode() {
        return currentModeACode;
    }

    /**
     * Sets the value of the currentModeACode property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     * @see #getCurrentModeACode()
     */
    public void setCurrentModeACode(JAXBElement<String> value) {
        this.currentModeACode = value;
    }

    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EnRouteExtensionType }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<EnRouteExtensionType> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

}
