//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import aero.fixm.base.FlightConstraintExtensionType;
import aero.fixm.base.RestrictionReferenceType;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A general flight constraint is intended to express a constraint on the flight that cannot be associated with a specific trajectory point, either because it is not relevant to only a specific point or because it is not possible to identify the point. [FF-ICE]
 * 
 * &lt;p&gt;Java class for FlightConstraintType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="FlightConstraintType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="applicability" type="{http://www.fixm.aero/base/4.3}CharacterStringType" minOccurs="0"/&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/base/4.3}FlightConstraintExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="impact" type="{http://www.fixm.aero/base/4.3}CharacterStringType" minOccurs="0"/&gt;
 *         &lt;element name="restrictionReference" type="{http://www.fixm.aero/base/4.3}RestrictionReferenceType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FlightConstraintType", propOrder = {
    "applicability",
    "extension",
    "impact",
    "restrictionReference"
})
public class FlightConstraintType
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    /**
     * Expression of a general flight constraint shall allow for a description of applicability.  Description of the applicability shall accommodate a free-text description. [FF-ICE]
     * 
     */
    @XmlElementRef(name = "applicability", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<String> applicability;
    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     */
    @XmlElement(nillable = true)
    protected List<FlightConstraintExtensionType> extension;
    /**
     * Expression of a general flight constraint shall allow for a description of the impact of the restriction on the flight. Description of the impact of the constraint shall accommodate a free-text description.  [FF-ICE]
     * 
     */
    @XmlElementRef(name = "impact", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<String> impact;
    /**
     * A general flight constraint should allow reference to a NOTAM; advisory; or AIXM identifier as necessary. [FF-ICE]
     * 
     */
    @XmlElementRef(name = "restrictionReference", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<RestrictionReferenceType> restrictionReference;

    /**
     * Expression of a general flight constraint shall allow for a description of applicability.  Description of the applicability shall accommodate a free-text description. [FF-ICE]
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getApplicability() {
        return applicability;
    }

    /**
     * Sets the value of the applicability property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     * @see #getApplicability()
     */
    public void setApplicability(JAXBElement<String> value) {
        this.applicability = value;
    }

    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FlightConstraintExtensionType }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<FlightConstraintExtensionType> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * Expression of a general flight constraint shall allow for a description of the impact of the restriction on the flight. Description of the impact of the constraint shall accommodate a free-text description.  [FF-ICE]
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getImpact() {
        return impact;
    }

    /**
     * Sets the value of the impact property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     * @see #getImpact()
     */
    public void setImpact(JAXBElement<String> value) {
        this.impact = value;
    }

    /**
     * A general flight constraint should allow reference to a NOTAM; advisory; or AIXM identifier as necessary. [FF-ICE]
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link RestrictionReferenceType }{@code >}
     *     
     */
    public JAXBElement<RestrictionReferenceType> getRestrictionReference() {
        return restrictionReference;
    }

    /**
     * Sets the value of the restrictionReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link RestrictionReferenceType }{@code >}
     *     
     * @see #getRestrictionReference()
     */
    public void setRestrictionReference(JAXBElement<RestrictionReferenceType> value) {
        this.restrictionReference = value;
    }

}
