//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import aero.fixm.base.AtcUnitReferenceType;
import aero.fixm.base.FlightEmergencyExtensionType;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Groups emergency information (description, phase, position, etc) for the flight.
 * 
 * &lt;p&gt;Java class for FlightEmergencyType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="FlightEmergencyType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="actionTaken" type="{http://www.fixm.aero/base/4.3}CharacterStringType" minOccurs="0"/&gt;
 *         &lt;element name="emergencyDescription" type="{http://www.fixm.aero/base/4.3}CharacterStringType" minOccurs="0"/&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/base/4.3}FlightEmergencyExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="lastContact" type="{http://www.fixm.aero/flight/4.3}LastContactType" minOccurs="0"/&gt;
 *         &lt;element name="originator" type="{http://www.fixm.aero/base/4.3}AtcUnitReferenceType" minOccurs="0"/&gt;
 *         &lt;element name="otherInformation" type="{http://www.fixm.aero/base/4.3}CharacterStringType" minOccurs="0"/&gt;
 *         &lt;element name="phase" type="{http://www.fixm.aero/flight/4.3}EmergencyPhaseType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FlightEmergencyType", propOrder = {
    "actionTaken",
    "emergencyDescription",
    "extension",
    "lastContact",
    "originator",
    "otherInformation",
    "phase"
})
public class FlightEmergencyType
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    /**
     * A description of the actions taken by the reporting Air Traffic Service (ATS) unit, in the event of search and rescue.
     * 
     */
    @XmlElementRef(name = "actionTaken", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<String> actionTaken;
    /**
     * A short, plain-language description of the nature of the emergency.
     * 
     */
    @XmlElementRef(name = "emergencyDescription", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<String> emergencyDescription;
    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     */
    @XmlElement(nillable = true)
    protected List<FlightEmergencyExtensionType> extension;
    /**
     * The last two-way contact between an ATS unit and the aircraft. [FIXM]
     * 
     */
    @XmlElementRef(name = "lastContact", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<LastContactType> lastContact;
    /**
     * The ICAO identifier of the ATS unit originating the emergency message.
     * 
     */
    @XmlElementRef(name = "originator", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<AtcUnitReferenceType> originator;
    /**
     * Other pertinent information not captured elsewhere needed to notify appropriate organizations regarding aircraft in need of search and rescue.
     * 
     */
    @XmlElementRef(name = "otherInformation", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<String> otherInformation;
    /**
     * A generic term meaning, as the case may be, uncertainty phase, alert phase or distress phase. [ICAO Annex 11]
     * 
     * This is the stage of emergency the flight is currently under or an indication the emergency has been cancelled, as designated by an ATS unit. [FIXM]
     * 
     */
    @XmlElementRef(name = "phase", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<EmergencyPhaseType> phase;

    /**
     * A description of the actions taken by the reporting Air Traffic Service (ATS) unit, in the event of search and rescue.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getActionTaken() {
        return actionTaken;
    }

    /**
     * Sets the value of the actionTaken property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     * @see #getActionTaken()
     */
    public void setActionTaken(JAXBElement<String> value) {
        this.actionTaken = value;
    }

    /**
     * A short, plain-language description of the nature of the emergency.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getEmergencyDescription() {
        return emergencyDescription;
    }

    /**
     * Sets the value of the emergencyDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     * @see #getEmergencyDescription()
     */
    public void setEmergencyDescription(JAXBElement<String> value) {
        this.emergencyDescription = value;
    }

    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FlightEmergencyExtensionType }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<FlightEmergencyExtensionType> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * The last two-way contact between an ATS unit and the aircraft. [FIXM]
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link LastContactType }{@code >}
     *     
     */
    public JAXBElement<LastContactType> getLastContact() {
        return lastContact;
    }

    /**
     * Sets the value of the lastContact property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link LastContactType }{@code >}
     *     
     * @see #getLastContact()
     */
    public void setLastContact(JAXBElement<LastContactType> value) {
        this.lastContact = value;
    }

    /**
     * The ICAO identifier of the ATS unit originating the emergency message.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AtcUnitReferenceType }{@code >}
     *     
     */
    public JAXBElement<AtcUnitReferenceType> getOriginator() {
        return originator;
    }

    /**
     * Sets the value of the originator property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AtcUnitReferenceType }{@code >}
     *     
     * @see #getOriginator()
     */
    public void setOriginator(JAXBElement<AtcUnitReferenceType> value) {
        this.originator = value;
    }

    /**
     * Other pertinent information not captured elsewhere needed to notify appropriate organizations regarding aircraft in need of search and rescue.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getOtherInformation() {
        return otherInformation;
    }

    /**
     * Sets the value of the otherInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     * @see #getOtherInformation()
     */
    public void setOtherInformation(JAXBElement<String> value) {
        this.otherInformation = value;
    }

    /**
     * A generic term meaning, as the case may be, uncertainty phase, alert phase or distress phase. [ICAO Annex 11]
     * 
     * This is the stage of emergency the flight is currently under or an indication the emergency has been cancelled, as designated by an ATS unit. [FIXM]
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link EmergencyPhaseType }{@code >}
     *     
     */
    public JAXBElement<EmergencyPhaseType> getPhase() {
        return phase;
    }

    /**
     * Sets the value of the phase property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link EmergencyPhaseType }{@code >}
     *     
     * @see #getPhase()
     */
    public void setPhase(JAXBElement<EmergencyPhaseType> value) {
        this.phase = value;
    }

}
