//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import aero.fixm.base.FlightIdentificationExtensionType;
import aero.fixm.base.GloballyUniqueFlightIdentifierType;
import aero.fixm.base.UniversallyUniqueIdentifierType;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A container of flight identifying data. [FIXM]
 * 
 * &lt;p&gt;Java class for FlightIdentificationType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="FlightIdentificationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="aircraftIdentification" type="{http://www.fixm.aero/base/4.3}AircraftIdentificationType" minOccurs="0"/&gt;
 *         &lt;element name="aircraftIdentificationPrevious" type="{http://www.fixm.aero/base/4.3}AircraftIdentificationType" minOccurs="0"/&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/base/4.3}FlightIdentificationExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;choice minOccurs="0"&gt;
 *           &lt;element name="gufi" type="{http://www.fixm.aero/base/4.3}GloballyUniqueFlightIdentifierType"/&gt;
 *           &lt;element name="gufiLegacy" type="{http://www.fixm.aero/base/4.3}UniversallyUniqueIdentifierType"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="iataFlightDesignator" type="{http://www.fixm.aero/flight/4.3}IataFlightDesignatorType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FlightIdentificationType", propOrder = {
    "aircraftIdentification",
    "aircraftIdentificationPrevious",
    "extension",
    "gufi",
    "gufiLegacy",
    "iataFlightDesignator"
})
public class FlightIdentificationType
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    /**
     * A group of letters, figures or a combination thereof which is either identical to, or the coded equivalent of, the aircraft call sign to be used in air-ground communications, and which is used to identify the aircraft in ground-ground air traffic services communications. [ICAO Doc 4444]
     * 
     */
    @XmlElementRef(name = "aircraftIdentification", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<String> aircraftIdentification;
    /**
     * Specifies the previous aircraft identification value when a change is made.
     * 
     */
    @XmlElementRef(name = "aircraftIdentificationPrevious", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<String> aircraftIdentificationPrevious;
    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     */
    @XmlElement(nillable = true)
    protected List<FlightIdentificationExtensionType> extension;
    /**
     * A single reference for FF-ICE information pertinent to a flight that is unique globally. [ICAO Doc 9965]
     * This is a reference that uniquely identifies a specific flight and is independent of any particular system. [FIXM]
     * 
     */
    @XmlElementRef(name = "gufi", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<GloballyUniqueFlightIdentifierType> gufi;
    /**
     * The legacy version of the GUFI included in the Core 4.3.0 release solely for backwards compatibility reasons.  This field should only be used when the GUFI assigned to a flight is in Core 4.2.0 format but there is a need to publish information about the flight in Core 4.3.0 format.  In all other cases, the new version of the GUFI should be used.
     * 
     */
    @XmlElementRef(name = "gufiLegacy", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<UniversallyUniqueIdentifierType> gufiLegacy;
    /**
     * International Air Transport Association (IATA) flight designator.  [FIXM]
     * 
     */
    @XmlElementRef(name = "iataFlightDesignator", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<IataFlightDesignatorType> iataFlightDesignator;

    /**
     * A group of letters, figures or a combination thereof which is either identical to, or the coded equivalent of, the aircraft call sign to be used in air-ground communications, and which is used to identify the aircraft in ground-ground air traffic services communications. [ICAO Doc 4444]
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getAircraftIdentification() {
        return aircraftIdentification;
    }

    /**
     * Sets the value of the aircraftIdentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     * @see #getAircraftIdentification()
     */
    public void setAircraftIdentification(JAXBElement<String> value) {
        this.aircraftIdentification = value;
    }

    /**
     * Specifies the previous aircraft identification value when a change is made.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getAircraftIdentificationPrevious() {
        return aircraftIdentificationPrevious;
    }

    /**
     * Sets the value of the aircraftIdentificationPrevious property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     * @see #getAircraftIdentificationPrevious()
     */
    public void setAircraftIdentificationPrevious(JAXBElement<String> value) {
        this.aircraftIdentificationPrevious = value;
    }

    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FlightIdentificationExtensionType }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<FlightIdentificationExtensionType> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * A single reference for FF-ICE information pertinent to a flight that is unique globally. [ICAO Doc 9965]
     * This is a reference that uniquely identifies a specific flight and is independent of any particular system. [FIXM]
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link GloballyUniqueFlightIdentifierType }{@code >}
     *     
     */
    public JAXBElement<GloballyUniqueFlightIdentifierType> getGufi() {
        return gufi;
    }

    /**
     * Sets the value of the gufi property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link GloballyUniqueFlightIdentifierType }{@code >}
     *     
     * @see #getGufi()
     */
    public void setGufi(JAXBElement<GloballyUniqueFlightIdentifierType> value) {
        this.gufi = value;
    }

    /**
     * The legacy version of the GUFI included in the Core 4.3.0 release solely for backwards compatibility reasons.  This field should only be used when the GUFI assigned to a flight is in Core 4.2.0 format but there is a need to publish information about the flight in Core 4.3.0 format.  In all other cases, the new version of the GUFI should be used.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link UniversallyUniqueIdentifierType }{@code >}
     *     
     */
    public JAXBElement<UniversallyUniqueIdentifierType> getGufiLegacy() {
        return gufiLegacy;
    }

    /**
     * Sets the value of the gufiLegacy property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link UniversallyUniqueIdentifierType }{@code >}
     *     
     * @see #getGufiLegacy()
     */
    public void setGufiLegacy(JAXBElement<UniversallyUniqueIdentifierType> value) {
        this.gufiLegacy = value;
    }

    /**
     * International Air Transport Association (IATA) flight designator.  [FIXM]
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link IataFlightDesignatorType }{@code >}
     *     
     */
    public JAXBElement<IataFlightDesignatorType> getIataFlightDesignator() {
        return iataFlightDesignator;
    }

    /**
     * Sets the value of the iataFlightDesignator property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link IataFlightDesignatorType }{@code >}
     *     
     * @see #getIataFlightDesignator()
     */
    public void setIataFlightDesignator(JAXBElement<IataFlightDesignatorType> value) {
        this.iataFlightDesignator = value;
    }

}
