//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import aero.fixm.base.HazardClassExtensionType;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A number assigned to a dangerous good that represents a classification (Class) according to the most dominant hazard it represents, potentially followed by a number representing a subdivision (Division) within the Class.
 * An identifier of any subsidiary hazard class(es)/division(s) in addition to the primary hazard class and division.
 * 
 * &lt;p&gt;Java class for HazardClassType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="HazardClassType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="class" type="{http://www.fixm.aero/flight/4.3}RestrictedHazardClassType" minOccurs="0"/&gt;
 *         &lt;element name="division" type="{http://www.fixm.aero/flight/4.3}HazardDivisionType" minOccurs="0"/&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/base/4.3}HazardClassExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HazardClassType", propOrder = {
    "clazz",
    "division",
    "extension"
})
public class HazardClassType
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    /**
     * A number assigned to a dangerous good that represents a classification (Class) according to the most dominant hazard it represents.
     * 
     */
    @XmlElementRef(name = "class", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<String> clazz;
    /**
     * A number representing a subdivision (Division) within the Class.
     * 
     */
    @XmlElementRef(name = "division", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<String> division;
    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     */
    @XmlElement(nillable = true)
    protected List<HazardClassExtensionType> extension;

    /**
     * A number assigned to a dangerous good that represents a classification (Class) according to the most dominant hazard it represents.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getClazz() {
        return clazz;
    }

    /**
     * Sets the value of the clazz property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     * @see #getClazz()
     */
    public void setClazz(JAXBElement<String> value) {
        this.clazz = value;
    }

    /**
     * A number representing a subdivision (Division) within the Class.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getDivision() {
        return division;
    }

    /**
     * Sets the value of the division property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     * @see #getDivision()
     */
    public void setDivision(JAXBElement<String> value) {
        this.division = value;
    }

    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HazardClassExtensionType }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<HazardClassExtensionType> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

}
