//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.datatype.XMLGregorianCalendar;
import aero.fixm.base.AltitudeWithSourceType;
import aero.fixm.base.BearingType;
import aero.fixm.base.DistanceType;
import aero.fixm.base.GroundSpeedType;
import aero.fixm.base.LastPositionReportExtensionType;
import aero.fixm.base.SignificantPointChoiceType;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The position of the aircraft last known to ATS and a corresponding timestamp.
 * 
 * &lt;p&gt;Java class for LastPositionReportType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="LastPositionReportType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="altitude" type="{http://www.fixm.aero/base/4.3}AltitudeWithSourceType" minOccurs="0"/&gt;
 *         &lt;element name="determinationMethod" type="{http://www.fixm.aero/base/4.3}CharacterStringType" minOccurs="0"/&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/base/4.3}LastPositionReportExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="groundSpeed" type="{http://www.fixm.aero/base/4.3}GroundSpeedType" minOccurs="0"/&gt;
 *         &lt;element name="heading" type="{http://www.fixm.aero/base/4.3}BearingType" minOccurs="0"/&gt;
 *         &lt;element name="horizontalAccuracy" type="{http://www.fixm.aero/base/4.3}DistanceType" minOccurs="0"/&gt;
 *         &lt;element name="position" type="{http://www.fixm.aero/base/4.3}SignificantPointChoiceType" minOccurs="0"/&gt;
 *         &lt;element name="timeAtPosition" type="{http://www.fixm.aero/base/4.3}DateTimeUtcType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LastPositionReportType", propOrder = {
    "altitude",
    "determinationMethod",
    "extension",
    "groundSpeed",
    "heading",
    "horizontalAccuracy",
    "position",
    "timeAtPosition"
})
public class LastPositionReportType
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    /**
     * The vertical distance, at the last known position, of the aircraft considered as a point, measured from mean Sea level (MSL). [FIXM]
     * 
     */
    @XmlElementRef(name = "altitude", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<AltitudeWithSourceType> altitude;
    /**
     * A plain-language description of the method used to determine the last known position of an aircraft.
     * 
     */
    @XmlElementRef(name = "determinationMethod", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<String> determinationMethod;
    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     */
    @XmlElement(nillable = true)
    protected List<LastPositionReportExtensionType> extension;
    /**
     * The speed of the aircraft relative to the surface of the earth at the last known position. [FIXM]
     * 
     */
    @XmlElementRef(name = "groundSpeed", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<GroundSpeedType> groundSpeed;
    /**
     * The direction, at the last known position, in which the longitudinal axis of the aircraft was pointed. [FIXM]
     * 
     */
    @XmlElementRef(name = "heading", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<BearingType> heading;
    /**
     * The difference between the measured horizontal coordinates of the aircraft and its true position referenced to the same geodetic datum expressed as a circular error at 95 percent probability. [FIXM]
     * 
     */
    @XmlElementRef(name = "horizontalAccuracy", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<DistanceType> horizontalAccuracy;
    /**
     * The position of the aircraft last known to ATS.
     * 
     */
    @XmlElementRef(name = "position", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<SignificantPointChoiceType> position;
    /**
     * Timestamp corresponding to the last known position.
     * 
     */
    @XmlElementRef(name = "timeAtPosition", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<XMLGregorianCalendar> timeAtPosition;

    /**
     * The vertical distance, at the last known position, of the aircraft considered as a point, measured from mean Sea level (MSL). [FIXM]
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AltitudeWithSourceType }{@code >}
     *     
     */
    public JAXBElement<AltitudeWithSourceType> getAltitude() {
        return altitude;
    }

    /**
     * Sets the value of the altitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AltitudeWithSourceType }{@code >}
     *     
     * @see #getAltitude()
     */
    public void setAltitude(JAXBElement<AltitudeWithSourceType> value) {
        this.altitude = value;
    }

    /**
     * A plain-language description of the method used to determine the last known position of an aircraft.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getDeterminationMethod() {
        return determinationMethod;
    }

    /**
     * Sets the value of the determinationMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     * @see #getDeterminationMethod()
     */
    public void setDeterminationMethod(JAXBElement<String> value) {
        this.determinationMethod = value;
    }

    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LastPositionReportExtensionType }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<LastPositionReportExtensionType> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * The speed of the aircraft relative to the surface of the earth at the last known position. [FIXM]
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link GroundSpeedType }{@code >}
     *     
     */
    public JAXBElement<GroundSpeedType> getGroundSpeed() {
        return groundSpeed;
    }

    /**
     * Sets the value of the groundSpeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link GroundSpeedType }{@code >}
     *     
     * @see #getGroundSpeed()
     */
    public void setGroundSpeed(JAXBElement<GroundSpeedType> value) {
        this.groundSpeed = value;
    }

    /**
     * The direction, at the last known position, in which the longitudinal axis of the aircraft was pointed. [FIXM]
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BearingType }{@code >}
     *     
     */
    public JAXBElement<BearingType> getHeading() {
        return heading;
    }

    /**
     * Sets the value of the heading property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BearingType }{@code >}
     *     
     * @see #getHeading()
     */
    public void setHeading(JAXBElement<BearingType> value) {
        this.heading = value;
    }

    /**
     * The difference between the measured horizontal coordinates of the aircraft and its true position referenced to the same geodetic datum expressed as a circular error at 95 percent probability. [FIXM]
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link DistanceType }{@code >}
     *     
     */
    public JAXBElement<DistanceType> getHorizontalAccuracy() {
        return horizontalAccuracy;
    }

    /**
     * Sets the value of the horizontalAccuracy property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link DistanceType }{@code >}
     *     
     * @see #getHorizontalAccuracy()
     */
    public void setHorizontalAccuracy(JAXBElement<DistanceType> value) {
        this.horizontalAccuracy = value;
    }

    /**
     * The position of the aircraft last known to ATS.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link SignificantPointChoiceType }{@code >}
     *     
     */
    public JAXBElement<SignificantPointChoiceType> getPosition() {
        return position;
    }

    /**
     * Sets the value of the position property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link SignificantPointChoiceType }{@code >}
     *     
     * @see #getPosition()
     */
    public void setPosition(JAXBElement<SignificantPointChoiceType> value) {
        this.position = value;
    }

    /**
     * Timestamp corresponding to the last known position.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getTimeAtPosition() {
        return timeAtPosition;
    }

    /**
     * Sets the value of the timeAtPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     * @see #getTimeAtPosition()
     */
    public void setTimeAtPosition(JAXBElement<XMLGregorianCalendar> value) {
        this.timeAtPosition = value;
    }

}
