//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The type of life jackets available on board the aircraft. [FIXM]
 * 
 * &lt;p&gt;Java class for LifeJacketTypeType&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * &lt;pre&gt;{&#064;code
 * &lt;simpleType name="LifeJacketTypeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="FLUORESCENCE"/&gt;
 *     &lt;enumeration value="LIGHTS"/&gt;
 *     &lt;enumeration value="ULTRA_HIGH_FREQUENCY"/&gt;
 *     &lt;enumeration value="VERY_HIGH_FREQUENCY"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * }&lt;/pre&gt;
 * 
 */
@XmlType(name = "LifeJacketTypeType")
@XmlEnum
public enum LifeJacketTypeType {


    /**
     * Life jackets are equipped with fluorescence. [adapted from ICAO Doc 4444, Appendix 2, ITEM 19 J/]
     * 
     */
    FLUORESCENCE,

    /**
     * Life jackets are equipped with lights. [adapted from ICAO Doc 4444, Appendix 2, ITEM 19 J/]
     * 
     */
    LIGHTS,

    /**
     * UHF on frequency 243.0 MHz is available. [adapted from ICAO Doc 4444, Appendix 2, ITEM 19 R/ and J/]
     * 
     */
    ULTRA_HIGH_FREQUENCY,

    /**
     * VHF on frequency 121.5 MHz is available. [adapted from ICAO Doc 4444, Appendix 2, ITEM 19 R/ and J/]
     * 
     */
    VERY_HIGH_FREQUENCY;

    public String value() {
        return name();
    }

    public static LifeJacketTypeType fromValue(String v) {
        return valueOf(v);
    }

}
