//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import aero.fixm.base.MeteorologicalDataExtensionType;
import aero.fixm.base.TemperatureType;
import aero.fixm.base.WindDirectionType;
import aero.fixm.base.WindSpeedType;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlType;


/**
 * In a predicted trajectory, the instantaneous temperature and wind vector used at the 4D Point for creating the 4D trajectory.
 * 
 * &lt;p&gt;Java class for MeteorologicalDataType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="MeteorologicalDataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/base/4.3}MeteorologicalDataExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="temperature" type="{http://www.fixm.aero/base/4.3}TemperatureType" minOccurs="0"/&gt;
 *         &lt;element name="windDirection" type="{http://www.fixm.aero/base/4.3}WindDirectionType" minOccurs="0"/&gt;
 *         &lt;element name="windSpeed" type="{http://www.fixm.aero/base/4.3}WindSpeedType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MeteorologicalDataType", propOrder = {
    "extension",
    "temperature",
    "windDirection",
    "windSpeed"
})
public class MeteorologicalDataType
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     */
    @XmlElement(nillable = true)
    protected List<MeteorologicalDataExtensionType> extension;
    /**
     * In a predicted trajectory, the instantaneous temperature used at the 4D Point for creating the 4D trajectory.
     * 
     */
    @XmlElementRef(name = "temperature", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<TemperatureType> temperature;
    /**
     * In a predicted trajectory, the instantaneous wind direction used at the 4D Point for creating the 4D trajectory.
     * 
     */
    @XmlElementRef(name = "windDirection", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<WindDirectionType> windDirection;
    /**
     * In a predicted trajectory, the instantaneous wind speed used at the 4D Point for creating the 4D trajectory.
     * 
     */
    @XmlElementRef(name = "windSpeed", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<WindSpeedType> windSpeed;

    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MeteorologicalDataExtensionType }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<MeteorologicalDataExtensionType> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * In a predicted trajectory, the instantaneous temperature used at the 4D Point for creating the 4D trajectory.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link TemperatureType }{@code >}
     *     
     */
    public JAXBElement<TemperatureType> getTemperature() {
        return temperature;
    }

    /**
     * Sets the value of the temperature property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link TemperatureType }{@code >}
     *     
     * @see #getTemperature()
     */
    public void setTemperature(JAXBElement<TemperatureType> value) {
        this.temperature = value;
    }

    /**
     * In a predicted trajectory, the instantaneous wind direction used at the 4D Point for creating the 4D trajectory.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link WindDirectionType }{@code >}
     *     
     */
    public JAXBElement<WindDirectionType> getWindDirection() {
        return windDirection;
    }

    /**
     * Sets the value of the windDirection property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link WindDirectionType }{@code >}
     *     
     * @see #getWindDirection()
     */
    public void setWindDirection(JAXBElement<WindDirectionType> value) {
        this.windDirection = value;
    }

    /**
     * In a predicted trajectory, the instantaneous wind speed used at the 4D Point for creating the 4D trajectory.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link WindSpeedType }{@code >}
     *     
     */
    public JAXBElement<WindSpeedType> getWindSpeed() {
        return windSpeed;
    }

    /**
     * Sets the value of the windSpeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link WindSpeedType }{@code >}
     *     
     * @see #getWindSpeed()
     */
    public void setWindSpeed(JAXBElement<WindSpeedType> value) {
        this.windSpeed = value;
    }

}
