//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import aero.fixm.base.DistanceType;
import aero.fixm.base.NavigationCapabilitiesExtensionType;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The navigation capability of the aircraft and associated flight crew qualifications. [FIXM]
 * 
 * &lt;p&gt;Java class for NavigationCapabilitiesType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="NavigationCapabilitiesType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/base/4.3}NavigationCapabilitiesExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="navigationCapabilityCode" type="{http://www.fixm.aero/flight/4.3}NavigationCapabilityCodeListType" minOccurs="0"/&gt;
 *         &lt;element name="otherNavigationCapabilities" type="{http://www.fixm.aero/base/4.3}CharacterStringType" minOccurs="0"/&gt;
 *         &lt;element name="performanceBasedCode" type="{http://www.fixm.aero/flight/4.3}PerformanceBasedNavigationCapabilityCodeListType" minOccurs="0"/&gt;
 *         &lt;element name="requiredRunwayVisualRange" type="{http://www.fixm.aero/base/4.3}DistanceType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NavigationCapabilitiesType", propOrder = {
    "extension",
    "navigationCapabilityCode",
    "otherNavigationCapabilities",
    "performanceBasedCode",
    "requiredRunwayVisualRange"
})
public class NavigationCapabilitiesType
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     */
    @XmlElement(nillable = true)
    protected List<NavigationCapabilitiesExtensionType> extension;
    /**
     * A code indicating the navigation capability of the aircraft and associated flight crew qualifications. [FIXM]
     * 
     */
    @XmlElementRef(name = "navigationCapabilityCode", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected List<JAXBElement<List<NavigationCapabilityCodeType>>> navigationCapabilityCode;
    /**
     * Additional navigation capabilities available on board the aircraft.
     * 
     */
    @XmlElementRef(name = "otherNavigationCapabilities", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<String> otherNavigationCapabilities;
    /**
     * A coded category denoting which Required Navigation Performance (RNP) and Area Navigation (RNAV) requirements can be met by the aircraft while operating in the context of a particular airspace when supported by the appropriate navigation infrastructure.
     * 
     */
    @XmlElementRef(name = "performanceBasedCode", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected List<JAXBElement<List<PerformanceBasedNavigationCapabilityCodeType>>> performanceBasedCode;
    /**
     * The minimum RVR value required by a flight in order to execute an approach to land at the destination aerodrome in accordance with the applicable ATM configuration. [FF-ICE]
     * 
     */
    @XmlElementRef(name = "requiredRunwayVisualRange", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<DistanceType> requiredRunwayVisualRange;

    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NavigationCapabilitiesExtensionType }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<NavigationCapabilitiesExtensionType> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * A code indicating the navigation capability of the aircraft and associated flight crew qualifications. [FIXM]
     * 
     * Gets the value of the navigationCapabilityCode property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the navigationCapabilityCode property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getNavigationCapabilityCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link List }{@code <}{@link NavigationCapabilityCodeType }{@code >}{@code >}
     * </p>
     * 
     * 
     * @return
     *     The value of the navigationCapabilityCode property.
     */
    public List<JAXBElement<List<NavigationCapabilityCodeType>>> getNavigationCapabilityCode() {
        if (navigationCapabilityCode == null) {
            navigationCapabilityCode = new ArrayList<>();
        }
        return this.navigationCapabilityCode;
    }

    /**
     * Additional navigation capabilities available on board the aircraft.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getOtherNavigationCapabilities() {
        return otherNavigationCapabilities;
    }

    /**
     * Sets the value of the otherNavigationCapabilities property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     * @see #getOtherNavigationCapabilities()
     */
    public void setOtherNavigationCapabilities(JAXBElement<String> value) {
        this.otherNavigationCapabilities = value;
    }

    /**
     * A coded category denoting which Required Navigation Performance (RNP) and Area Navigation (RNAV) requirements can be met by the aircraft while operating in the context of a particular airspace when supported by the appropriate navigation infrastructure.
     * 
     * Gets the value of the performanceBasedCode property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the performanceBasedCode property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getPerformanceBasedCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link List }{@code <}{@link PerformanceBasedNavigationCapabilityCodeType }{@code >}{@code >}
     * </p>
     * 
     * 
     * @return
     *     The value of the performanceBasedCode property.
     */
    public List<JAXBElement<List<PerformanceBasedNavigationCapabilityCodeType>>> getPerformanceBasedCode() {
        if (performanceBasedCode == null) {
            performanceBasedCode = new ArrayList<>();
        }
        return this.performanceBasedCode;
    }

    /**
     * The minimum RVR value required by a flight in order to execute an approach to land at the destination aerodrome in accordance with the applicable ATM configuration. [FF-ICE]
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link DistanceType }{@code >}
     *     
     */
    public JAXBElement<DistanceType> getRequiredRunwayVisualRange() {
        return requiredRunwayVisualRange;
    }

    /**
     * Sets the value of the requiredRunwayVisualRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link DistanceType }{@code >}
     *     
     * @see #getRequiredRunwayVisualRange()
     */
    public void setRequiredRunwayVisualRange(JAXBElement<DistanceType> value) {
        this.requiredRunwayVisualRange = value;
    }

}
