//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A code indicating the navigation capability of the aircraft and associated flight crew qualifications. [FIXM]
 * 
 * &lt;p&gt;Java class for NavigationCapabilityCodeType&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * &lt;pre&gt;{&#064;code
 * &lt;simpleType name="NavigationCapabilityCodeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="A"/&gt;
 *     &lt;enumeration value="B"/&gt;
 *     &lt;enumeration value="C"/&gt;
 *     &lt;enumeration value="D"/&gt;
 *     &lt;enumeration value="F"/&gt;
 *     &lt;enumeration value="G"/&gt;
 *     &lt;enumeration value="I"/&gt;
 *     &lt;enumeration value="K"/&gt;
 *     &lt;enumeration value="L"/&gt;
 *     &lt;enumeration value="O"/&gt;
 *     &lt;enumeration value="T"/&gt;
 *     &lt;enumeration value="W"/&gt;
 *     &lt;enumeration value="X"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * }&lt;/pre&gt;
 * 
 */
@XmlType(name = "NavigationCapabilityCodeType")
@XmlEnum
public enum NavigationCapabilityCodeType {


    /**
     * GBAS
     * 
     */
    A,

    /**
     * LPV
     * 
     */
    B,

    /**
     * LORAN C
     * 
     */
    C,

    /**
     * DME
     * 
     */
    D,

    /**
     * ADF
     * 
     */
    F,

    /**
     * GNSS
     * 
     */
    G,

    /**
     * Inertial Navigation
     * 
     */
    I,

    /**
     * MLS
     * 
     */
    K,

    /**
     * ILS
     * 
     */
    L,

    /**
     * VOR
     * 
     */
    O,

    /**
     * TACAN
     * 
     */
    T,

    /**
     * RVSM
     * 
     */
    W,

    /**
     * MNPS
     * 
     */
    X;

    public String value() {
        return name();
    }

    public static NavigationCapabilityCodeType fromValue(String v) {
        return valueOf(v);
    }

}
