//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Indicates that the route to next element is either DIRECT or UNSPECIFIED.
 * 
 * &lt;p&gt;Java class for OtherRouteDesignatorType&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * &lt;pre&gt;{&#064;code
 * &lt;simpleType name="OtherRouteDesignatorType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="DIRECT"/&gt;
 *     &lt;enumeration value="UNSPECIFIED"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * }&lt;/pre&gt;
 * 
 */
@XmlType(name = "OtherRouteDesignatorType")
@XmlEnum
public enum OtherRouteDesignatorType {


    /**
     * When the element is direct, "Direct" must be specified. [FF-ICE]
     * 
     */
    DIRECT,

    /**
     * If the element is a delay segment, the route to next element should be labeled as "Unspecified". [FF-ICE]
     * 
     */
    UNSPECIFIED;

    public String value() {
        return name();
    }

    public static OtherRouteDesignatorType fromValue(String v) {
        return valueOf(v);
    }

}
