//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A code that indicates the relative degree of danger presented by various articles and substances within a Class or Division.
 * 
 * &lt;p&gt;Java class for PackingGroupType&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * &lt;pre&gt;{&#064;code
 * &lt;simpleType name="PackingGroupType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="I"/&gt;
 *     &lt;enumeration value="II"/&gt;
 *     &lt;enumeration value="III"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * }&lt;/pre&gt;
 * 
 */
@XmlType(name = "PackingGroupType")
@XmlEnum
public enum PackingGroupType {


    /**
     * Represents high danger.
     * 
     */
    I,

    /**
     * Represents medium danger.
     * 
     */
    II,

    /**
     * Represents low danger.
     * 
     */
    III;

    public String value() {
        return name();
    }

    public static PackingGroupType fromValue(String v) {
        return valueOf(v);
    }

}
