//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.datatype.Duration;
import aero.fixm.base.PlannedDelayExtensionType;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Delay or holding planned to occur at a significant point or along a route element.
 * 
 * &lt;p&gt;Java class for PlannedDelayType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="PlannedDelayType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="delayReason" type="{http://www.fixm.aero/base/4.3}CharacterStringType" minOccurs="0"/&gt;
 *         &lt;element name="delayReference" type="{http://www.fixm.aero/base/4.3}CharacterStringType" minOccurs="0"/&gt;
 *         &lt;element name="delayType" type="{http://www.fixm.aero/flight/4.3}PlannedDelayTypeType" minOccurs="0"/&gt;
 *         &lt;element name="delayValue" type="{http://www.fixm.aero/base/4.3}DurationType" minOccurs="0"/&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/base/4.3}PlannedDelayExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PlannedDelayType", propOrder = {
    "delayReason",
    "delayReference",
    "delayType",
    "delayValue",
    "extension"
})
public class PlannedDelayType
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    /**
     * The reason for the delay.  [FIXM]
     * 
     */
    @XmlElementRef(name = "delayReason", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<String> delayReason;
    /**
     * Indicates a named hold pattern, airspace, or aerodrome at which the delay is expected to occur.
     * 
     */
    @XmlElementRef(name = "delayReference", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<String> delayReference;
    /**
     * Indicates if the delay is planned airborne holding or Operator (Airspace User) requested operations at a specified location.
     * 
     */
    @XmlElementRef(name = "delayType", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<PlannedDelayTypeType> delayType;
    /**
     * The length of time the flight is expected to be delayed at a specific point.
     * 
     */
    @XmlElementRef(name = "delayValue", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<Duration> delayValue;
    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     */
    @XmlElement(nillable = true)
    protected List<PlannedDelayExtensionType> extension;

    /**
     * The reason for the delay.  [FIXM]
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getDelayReason() {
        return delayReason;
    }

    /**
     * Sets the value of the delayReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     * @see #getDelayReason()
     */
    public void setDelayReason(JAXBElement<String> value) {
        this.delayReason = value;
    }

    /**
     * Indicates a named hold pattern, airspace, or aerodrome at which the delay is expected to occur.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getDelayReference() {
        return delayReference;
    }

    /**
     * Sets the value of the delayReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     * @see #getDelayReference()
     */
    public void setDelayReference(JAXBElement<String> value) {
        this.delayReference = value;
    }

    /**
     * Indicates if the delay is planned airborne holding or Operator (Airspace User) requested operations at a specified location.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link PlannedDelayTypeType }{@code >}
     *     
     */
    public JAXBElement<PlannedDelayTypeType> getDelayType() {
        return delayType;
    }

    /**
     * Sets the value of the delayType property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link PlannedDelayTypeType }{@code >}
     *     
     * @see #getDelayType()
     */
    public void setDelayType(JAXBElement<PlannedDelayTypeType> value) {
        this.delayType = value;
    }

    /**
     * The length of time the flight is expected to be delayed at a specific point.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Duration }{@code >}
     *     
     */
    public JAXBElement<Duration> getDelayValue() {
        return delayValue;
    }

    /**
     * Sets the value of the delayValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Duration }{@code >}
     *     
     * @see #getDelayValue()
     */
    public void setDelayValue(JAXBElement<Duration> value) {
        this.delayValue = value;
    }

    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PlannedDelayExtensionType }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<PlannedDelayExtensionType> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

}
