//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.datatype.Duration;
import aero.fixm.base.DistanceType;
import aero.fixm.base.FlightLevelOrAltitudeChoiceType;
import aero.fixm.base.ProfilePointExtensionType;
import aero.fixm.base.TrueAirspeedType;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A point in a performance climb or descent profile.
 * 
 * &lt;p&gt;Java class for ProfilePointType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="ProfilePointType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="airspeed" type="{http://www.fixm.aero/base/4.3}TrueAirspeedType" minOccurs="0"/&gt;
 *         &lt;element name="distance" type="{http://www.fixm.aero/base/4.3}DistanceType" minOccurs="0"/&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/base/4.3}ProfilePointExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="level" type="{http://www.fixm.aero/base/4.3}FlightLevelOrAltitudeChoiceType" minOccurs="0"/&gt;
 *         &lt;element name="time" type="{http://www.fixm.aero/base/4.3}DurationType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="seqNum" type="{http://www.fixm.aero/base/4.3}CountType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProfilePointType", propOrder = {
    "airspeed",
    "distance",
    "extension",
    "level",
    "time"
})
public class ProfilePointType
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    /**
     * The true airspeed of a point in a zero-wind, standard atmosphere, unconstrained profile.
     * 
     */
    @XmlElementRef(name = "airspeed", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<TrueAirspeedType> airspeed;
    /**
     * The distance (from the start of the profile) at a point in a zero-wind, unconstrained profile.
     * 
     */
    @XmlElementRef(name = "distance", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<DistanceType> distance;
    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     */
    @XmlElement(nillable = true)
    protected List<ProfilePointExtensionType> extension;
    /**
     * The altitude of a point in a zero-wind, unconstrained profile.
     * 
     */
    @XmlElementRef(name = "level", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<FlightLevelOrAltitudeChoiceType> level;
    /**
     * The time (from the start of the profile) at a point in a zero-wind, unconstrained profile.
     * 
     */
    @XmlElementRef(name = "time", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<Duration> time;
    /**
     * Incrementing identifier used to ensure the sequence of ordered lists is retained. The identifier should begin at zero. [FIXM]
     * 
     */
    @XmlAttribute(name = "seqNum")
    protected Integer seqNum;

    /**
     * The true airspeed of a point in a zero-wind, standard atmosphere, unconstrained profile.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link TrueAirspeedType }{@code >}
     *     
     */
    public JAXBElement<TrueAirspeedType> getAirspeed() {
        return airspeed;
    }

    /**
     * Sets the value of the airspeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link TrueAirspeedType }{@code >}
     *     
     * @see #getAirspeed()
     */
    public void setAirspeed(JAXBElement<TrueAirspeedType> value) {
        this.airspeed = value;
    }

    /**
     * The distance (from the start of the profile) at a point in a zero-wind, unconstrained profile.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link DistanceType }{@code >}
     *     
     */
    public JAXBElement<DistanceType> getDistance() {
        return distance;
    }

    /**
     * Sets the value of the distance property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link DistanceType }{@code >}
     *     
     * @see #getDistance()
     */
    public void setDistance(JAXBElement<DistanceType> value) {
        this.distance = value;
    }

    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProfilePointExtensionType }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<ProfilePointExtensionType> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * The altitude of a point in a zero-wind, unconstrained profile.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link FlightLevelOrAltitudeChoiceType }{@code >}
     *     
     */
    public JAXBElement<FlightLevelOrAltitudeChoiceType> getLevel() {
        return level;
    }

    /**
     * Sets the value of the level property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link FlightLevelOrAltitudeChoiceType }{@code >}
     *     
     * @see #getLevel()
     */
    public void setLevel(JAXBElement<FlightLevelOrAltitudeChoiceType> value) {
        this.level = value;
    }

    /**
     * The time (from the start of the profile) at a point in a zero-wind, unconstrained profile.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Duration }{@code >}
     *     
     */
    public JAXBElement<Duration> getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Duration }{@code >}
     *     
     * @see #getTime()
     */
    public void setTime(JAXBElement<Duration> value) {
        this.time = value;
    }

    /**
     * Incrementing identifier used to ensure the sequence of ordered lists is retained. The identifier should begin at zero. [FIXM]
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSeqNum() {
        return seqNum;
    }

    /**
     * Sets the value of the seqNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getSeqNum()
     */
    public void setSeqNum(Integer value) {
        this.seqNum = value;
    }

}
