//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import aero.fixm.base.RadioactiveMaterialExtensionType;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The  grouping element for goods that contain radioactive materials.
 * 
 * &lt;p&gt;Java class for RadioactiveMaterialType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="RadioactiveMaterialType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="category" type="{http://www.fixm.aero/flight/4.3}RadioactiveMaterialCategoryType" minOccurs="0"/&gt;
 *         &lt;element name="criticalSafetyIndex" type="{http://www.fixm.aero/flight/4.3}CriticalSafetyIndexType" minOccurs="0"/&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/base/4.3}RadioactiveMaterialExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="transportIndex" type="{http://www.fixm.aero/flight/4.3}TransportIndexType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RadioactiveMaterialType", propOrder = {
    "category",
    "criticalSafetyIndex",
    "extension",
    "transportIndex"
})
public class RadioactiveMaterialType
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    /**
     * A category used for radioactive materials in a package, overpack or freight container, based on their maximum radiation level.
     * 
     */
    @XmlElementRef(name = "category", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<RadioactiveMaterialCategoryType> category;
    /**
     * The dimensionless number (rounded up to the next tenth) assigned to and placed on the label of a fissile material package to designate the degree of control of accumulation of packages containing fissile material during transportation.
     * 
     */
    @XmlElementRef(name = "criticalSafetyIndex", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<BigDecimal> criticalSafetyIndex;
    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     */
    @XmlElement(nillable = true)
    protected List<RadioactiveMaterialExtensionType> extension;
    /**
     * A figure representing the radiation level measured at one meter from the package.
     * 
     */
    @XmlElementRef(name = "transportIndex", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<BigDecimal> transportIndex;

    /**
     * A category used for radioactive materials in a package, overpack or freight container, based on their maximum radiation level.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link RadioactiveMaterialCategoryType }{@code >}
     *     
     */
    public JAXBElement<RadioactiveMaterialCategoryType> getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link RadioactiveMaterialCategoryType }{@code >}
     *     
     * @see #getCategory()
     */
    public void setCategory(JAXBElement<RadioactiveMaterialCategoryType> value) {
        this.category = value;
    }

    /**
     * The dimensionless number (rounded up to the next tenth) assigned to and placed on the label of a fissile material package to designate the degree of control of accumulation of packages containing fissile material during transportation.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public JAXBElement<BigDecimal> getCriticalSafetyIndex() {
        return criticalSafetyIndex;
    }

    /**
     * Sets the value of the criticalSafetyIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     * @see #getCriticalSafetyIndex()
     */
    public void setCriticalSafetyIndex(JAXBElement<BigDecimal> value) {
        this.criticalSafetyIndex = value;
    }

    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RadioactiveMaterialExtensionType }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<RadioactiveMaterialExtensionType> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * A figure representing the radiation level measured at one meter from the package.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public JAXBElement<BigDecimal> getTransportIndex() {
        return transportIndex;
    }

    /**
     * Sets the value of the transportIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     * @see #getTransportIndex()
     */
    public void setTransportIndex(JAXBElement<BigDecimal> value) {
        this.transportIndex = value;
    }

}
