//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A category used for radioactive materials in a package, overpack or freight container, based on their maximum radiation level.
 * 
 * &lt;p&gt;Java class for RadioactiveMaterialCategoryType&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * &lt;pre&gt;{&#064;code
 * &lt;simpleType name="RadioactiveMaterialCategoryType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="I_WHITE"/&gt;
 *     &lt;enumeration value="II_YELLOW"/&gt;
 *     &lt;enumeration value="III_YELLOW"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * }&lt;/pre&gt;
 * 
 */
@XmlType(name = "RadioactiveMaterialCategoryType")
@XmlEnum
public enum RadioactiveMaterialCategoryType {


    /**
     * .Surface radiation &lt;0.5 millirem/hr, 1 meter radiation: N/A
     * 
     */
    I_WHITE,
    II_YELLOW,

    /**
     * Surface radiation &gt;50 millirem/hr, 1 meter radiation &gt;1 millirem/hr
     * 
     */
    III_YELLOW;

    public String value() {
        return name();
    }

    public static RadioactiveMaterialCategoryType fromValue(String v) {
        return valueOf(v);
    }

}
