//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import aero.fixm.base.RadioCommunicationFailureExtensionType;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Groups information regarding loss of radio communication capabilities.
 * 
 * &lt;p&gt;Java class for RadioCommunicationFailureType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="RadioCommunicationFailureType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="contact" type="{http://www.fixm.aero/flight/4.3}LastContactType" minOccurs="0"/&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/base/4.3}RadioCommunicationFailureExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="radioFailureRemarks" type="{http://www.fixm.aero/base/4.3}CharacterStringType" minOccurs="0"/&gt;
 *         &lt;element name="remainingComCapability" type="{http://www.fixm.aero/base/4.3}CharacterStringType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RadioCommunicationFailureType", propOrder = {
    "contact",
    "extension",
    "radioFailureRemarks",
    "remainingComCapability"
})
public class RadioCommunicationFailureType
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    /**
     * The last ATS unit which had two-way contact with the aircraft.
     * 
     */
    @XmlElementRef(name = "contact", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<LastContactType> contact;
    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     */
    @XmlElement(nillable = true)
    protected List<RadioCommunicationFailureExtensionType> extension;
    /**
     * Pertinent information needed to notify appropriate organizations regarding loss of radio communication capabilities.
     * 
     */
    @XmlElementRef(name = "radioFailureRemarks", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<String> radioFailureRemarks;
    /**
     * The remaining communication capability of the aircraft following radio failure.
     * 
     */
    @XmlElementRef(name = "remainingComCapability", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<String> remainingComCapability;

    /**
     * The last ATS unit which had two-way contact with the aircraft.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link LastContactType }{@code >}
     *     
     */
    public JAXBElement<LastContactType> getContact() {
        return contact;
    }

    /**
     * Sets the value of the contact property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link LastContactType }{@code >}
     *     
     * @see #getContact()
     */
    public void setContact(JAXBElement<LastContactType> value) {
        this.contact = value;
    }

    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RadioCommunicationFailureExtensionType }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<RadioCommunicationFailureExtensionType> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * Pertinent information needed to notify appropriate organizations regarding loss of radio communication capabilities.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getRadioFailureRemarks() {
        return radioFailureRemarks;
    }

    /**
     * Sets the value of the radioFailureRemarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     * @see #getRadioFailureRemarks()
     */
    public void setRadioFailureRemarks(JAXBElement<String> value) {
        this.radioFailureRemarks = value;
    }

    /**
     * The remaining communication capability of the aircraft following radio failure.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getRemainingComCapability() {
        return remainingComCapability;
    }

    /**
     * Sets the value of the remainingComCapability property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     * @see #getRemainingComCapability()
     */
    public void setRemainingComCapability(JAXBElement<String> value) {
        this.remainingComCapability = value;
    }

}
