//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import aero.fixm.base.AerodromeReferenceType;
import aero.fixm.base.ReclearanceInFlightExtensionType;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The route details to the revised destination aerodrome, followed by the ICAO four-letter location indicator of
 * the aerodrome. The revised route is subject to reclearance in flight. [ICAO Doc 4444]
 * 
 * &lt;p&gt;Java class for ReclearanceInFlightType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="ReclearanceInFlightType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/base/4.3}ReclearanceInFlightExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="filedRevisedDestinationAerodrome" type="{http://www.fixm.aero/base/4.3}AerodromeReferenceType" minOccurs="0"/&gt;
 *         &lt;element name="routeToRevisedDestination" type="{http://www.fixm.aero/base/4.3}CharacterStringType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReclearanceInFlightType", propOrder = {
    "extension",
    "filedRevisedDestinationAerodrome",
    "routeToRevisedDestination"
})
public class ReclearanceInFlightType
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     */
    @XmlElement(nillable = true)
    protected List<ReclearanceInFlightExtensionType> extension;
    /**
     * Aerodrome where the flight will divert to based on the revised route. For example, an aerodrome where the flight will divert to if more fuel is used than expected.[FIXM]
     * 
     */
    @XmlElementRef(name = "filedRevisedDestinationAerodrome", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<AerodromeReferenceType> filedRevisedDestinationAerodrome;
    /**
     * Route to the revised destination aerodrome. [FIXM]
     * 
     */
    @XmlElementRef(name = "routeToRevisedDestination", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<String> routeToRevisedDestination;

    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReclearanceInFlightExtensionType }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<ReclearanceInFlightExtensionType> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * Aerodrome where the flight will divert to based on the revised route. For example, an aerodrome where the flight will divert to if more fuel is used than expected.[FIXM]
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AerodromeReferenceType }{@code >}
     *     
     */
    public JAXBElement<AerodromeReferenceType> getFiledRevisedDestinationAerodrome() {
        return filedRevisedDestinationAerodrome;
    }

    /**
     * Sets the value of the filedRevisedDestinationAerodrome property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AerodromeReferenceType }{@code >}
     *     
     * @see #getFiledRevisedDestinationAerodrome()
     */
    public void setFiledRevisedDestinationAerodrome(JAXBElement<AerodromeReferenceType> value) {
        this.filedRevisedDestinationAerodrome = value;
    }

    /**
     * Route to the revised destination aerodrome. [FIXM]
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getRouteToRevisedDestination() {
        return routeToRevisedDestination;
    }

    /**
     * Sets the value of the routeToRevisedDestination property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     * @see #getRouteToRevisedDestination()
     */
    public void setRouteToRevisedDestination(JAXBElement<String> value) {
        this.routeToRevisedDestination = value;
    }

}
