//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import aero.fixm.base.RouteTrajectoryGroupContainerExtensionType;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A logical grouping for all Route Trajectory Groups associated with the flight. [FIXM]
 * 
 * &lt;p&gt;Java class for RouteTrajectoryGroupContainerType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="RouteTrajectoryGroupContainerType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="agreed" type="{http://www.fixm.aero/flight/4.3}RouteTrajectoryGroupType" minOccurs="0"/&gt;
 *         &lt;element name="current" type="{http://www.fixm.aero/flight/4.3}RouteTrajectoryGroupType" minOccurs="0"/&gt;
 *         &lt;element name="desired" type="{http://www.fixm.aero/flight/4.3}RouteTrajectoryGroupType" minOccurs="0"/&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/base/4.3}RouteTrajectoryGroupContainerExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="negotiating" type="{http://www.fixm.aero/flight/4.3}RouteTrajectoryGroupType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RouteTrajectoryGroupContainerType", propOrder = {
    "agreed",
    "current",
    "desired",
    "extension",
    "negotiating"
})
public class RouteTrajectoryGroupContainerType
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    /**
     * The 4D Trajectory agreed to by a FF-ICE enabled Air Traffic Management Service Providers (eASP) after collaboration between the FF-ICE enabled airspace user (eAU) and the eASP.
     * The route of flight agreed to by a FF-ICE enabled Air Traffic Management Service Providers (eASP) after collaboration between the FF-ICE enabled airspace user (eAU) and the eASP.
     * 
     */
    @XmlElementRef(name = "agreed", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<RouteTrajectoryGroupType> agreed;
    /**
     * Represents the current flight plan concept described by ICAO PANS-ATM Doc 4444.
     * 
     */
    @XmlElementRef(name = "current", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<RouteTrajectoryGroupType> current;
    /**
     * The preferred route of flight submitted by the FF-ICE enabled airspace user (eAU) to the FF-ICE enabled Air Traffic Management Service Providers (eASP) subject to required constraints.
     * This trajectory indicates the preferred 4D trajectory submitted by the FF-ICE enabled airspace user (eAU) to the FF-ICE enabled Air Traffic Management Service Providers (eASP) subject to required constraints.
     * 
     */
    @XmlElementRef(name = "desired", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<RouteTrajectoryGroupType> desired;
    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     */
    @XmlElement(nillable = true)
    protected List<RouteTrajectoryGroupContainerExtensionType> extension;
    /**
     * The 4D Trajectory used during the collaboration between the FF-ICE enabled airspace user (eAU) and the FF-ICE enabled Air Traffic Management Service Providers (eASP) in order to agree on a 4D trajectory. This trajectory is intended to be transitory. 
     * This Route is used during collaboration between the FF-ICE enabled airspace user (eAU) and the FF-ICE enabled Air Traffic Management Service Providers (eASP) in order to agree on a route. This route field is intended to be transitory.
     * 
     */
    @XmlElementRef(name = "negotiating", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<RouteTrajectoryGroupType> negotiating;

    /**
     * The 4D Trajectory agreed to by a FF-ICE enabled Air Traffic Management Service Providers (eASP) after collaboration between the FF-ICE enabled airspace user (eAU) and the eASP.
     * The route of flight agreed to by a FF-ICE enabled Air Traffic Management Service Providers (eASP) after collaboration between the FF-ICE enabled airspace user (eAU) and the eASP.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link RouteTrajectoryGroupType }{@code >}
     *     
     */
    public JAXBElement<RouteTrajectoryGroupType> getAgreed() {
        return agreed;
    }

    /**
     * Sets the value of the agreed property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link RouteTrajectoryGroupType }{@code >}
     *     
     * @see #getAgreed()
     */
    public void setAgreed(JAXBElement<RouteTrajectoryGroupType> value) {
        this.agreed = value;
    }

    /**
     * Represents the current flight plan concept described by ICAO PANS-ATM Doc 4444.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link RouteTrajectoryGroupType }{@code >}
     *     
     */
    public JAXBElement<RouteTrajectoryGroupType> getCurrent() {
        return current;
    }

    /**
     * Sets the value of the current property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link RouteTrajectoryGroupType }{@code >}
     *     
     * @see #getCurrent()
     */
    public void setCurrent(JAXBElement<RouteTrajectoryGroupType> value) {
        this.current = value;
    }

    /**
     * The preferred route of flight submitted by the FF-ICE enabled airspace user (eAU) to the FF-ICE enabled Air Traffic Management Service Providers (eASP) subject to required constraints.
     * This trajectory indicates the preferred 4D trajectory submitted by the FF-ICE enabled airspace user (eAU) to the FF-ICE enabled Air Traffic Management Service Providers (eASP) subject to required constraints.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link RouteTrajectoryGroupType }{@code >}
     *     
     */
    public JAXBElement<RouteTrajectoryGroupType> getDesired() {
        return desired;
    }

    /**
     * Sets the value of the desired property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link RouteTrajectoryGroupType }{@code >}
     *     
     * @see #getDesired()
     */
    public void setDesired(JAXBElement<RouteTrajectoryGroupType> value) {
        this.desired = value;
    }

    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RouteTrajectoryGroupContainerExtensionType }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<RouteTrajectoryGroupContainerExtensionType> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * The 4D Trajectory used during the collaboration between the FF-ICE enabled airspace user (eAU) and the FF-ICE enabled Air Traffic Management Service Providers (eASP) in order to agree on a 4D trajectory. This trajectory is intended to be transitory. 
     * This Route is used during collaboration between the FF-ICE enabled airspace user (eAU) and the FF-ICE enabled Air Traffic Management Service Providers (eASP) in order to agree on a route. This route field is intended to be transitory.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link RouteTrajectoryGroupType }{@code >}
     *     
     */
    public JAXBElement<RouteTrajectoryGroupType> getNegotiating() {
        return negotiating;
    }

    /**
     * Sets the value of the negotiating property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link RouteTrajectoryGroupType }{@code >}
     *     
     * @see #getNegotiating()
     */
    public void setNegotiating(JAXBElement<RouteTrajectoryGroupType> value) {
        this.negotiating = value;
    }

}
