//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import aero.fixm.base.MassType;
import aero.fixm.base.RouteTrajectoryGroupExtensionType;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A data container supporting the representation of aircraft movement descriptions with variable levels of granularity.  This container enables the representation of a flight route and a 4D trajectory, as described in ICAO Doc 9965 Volume 2.  [FIXM]
 * 
 * &lt;p&gt;Java class for RouteTrajectoryGroupType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="RouteTrajectoryGroupType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="climbProfile" type="{http://www.fixm.aero/flight/4.3}PerformanceProfileType" minOccurs="0"/&gt;
 *         &lt;element name="climbSchedule" type="{http://www.fixm.aero/flight/4.3}SpeedScheduleType" minOccurs="0"/&gt;
 *         &lt;element name="descentProfile" type="{http://www.fixm.aero/flight/4.3}PerformanceProfileType" minOccurs="0"/&gt;
 *         &lt;element name="descentSchedule" type="{http://www.fixm.aero/flight/4.3}SpeedScheduleType" minOccurs="0"/&gt;
 *         &lt;element name="element" type="{http://www.fixm.aero/flight/4.3}RouteTrajectoryElementType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/base/4.3}RouteTrajectoryGroupExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="routeInformation" type="{http://www.fixm.aero/flight/4.3}FlightRouteInformationType" minOccurs="0"/&gt;
 *         &lt;element name="takeoffMass" type="{http://www.fixm.aero/base/4.3}MassType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RouteTrajectoryGroupType", propOrder = {
    "climbProfile",
    "climbSchedule",
    "descentProfile",
    "descentSchedule",
    "element",
    "extension",
    "routeInformation",
    "takeoffMass"
})
public class RouteTrajectoryGroupType
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    /**
     * A zero-wind, standard atmosphere, unconstrained climb profile reflective of the flight capabilities and desired parameters during climb.
     * 
     */
    @XmlElementRef(name = "climbProfile", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<PerformanceProfileType> climbProfile;
    /**
     * Initially submitted by the airspace user, this defines the target speed in both Indicated Airspeed (IAS) and MACH so the aircraft can climb through the crossover altitude and target the MACH speed when needed.
     * 
     */
    @XmlElementRef(name = "climbSchedule", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<SpeedScheduleType> climbSchedule;
    /**
     * A zero-wind, standard atmosphere, unconstrained descent profile reflective of the flight capabilities and desired parameters during descent.
     * 
     */
    @XmlElementRef(name = "descentProfile", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<PerformanceProfileType> descentProfile;
    /**
     * Initially submitted by the airspace user, this defines the target speed in both (Indicated Airspeed) IAS and MACH so the aircraft can descend through the crossover altitude and target the IAS speed when needed.
     * 
     */
    @XmlElementRef(name = "descentSchedule", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<SpeedScheduleType> descentSchedule;
    /**
     * A container for information pertinent to a single point in a trajectory. The elements are ordered according to increasing time/distance from the start point.
     * 
     */
    @XmlElement(nillable = true)
    protected List<RouteTrajectoryElementType> element;
    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     */
    @XmlElement(nillable = true)
    protected List<RouteTrajectoryGroupExtensionType> extension;
    /**
     * Contains information about the Flight Route. The route is comprised of Route Segments, which are comprised of Route Point/Airway pairs. Route also contains an expanded route.
     * 
     */
    @XmlElementRef(name = "routeInformation", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<FlightRouteInformationType> routeInformation;
    /**
     * The estimated takeoff mass of the aircraft.
     * 
     */
    @XmlElementRef(name = "takeoffMass", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<MassType> takeoffMass;

    /**
     * A zero-wind, standard atmosphere, unconstrained climb profile reflective of the flight capabilities and desired parameters during climb.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link PerformanceProfileType }{@code >}
     *     
     */
    public JAXBElement<PerformanceProfileType> getClimbProfile() {
        return climbProfile;
    }

    /**
     * Sets the value of the climbProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link PerformanceProfileType }{@code >}
     *     
     * @see #getClimbProfile()
     */
    public void setClimbProfile(JAXBElement<PerformanceProfileType> value) {
        this.climbProfile = value;
    }

    /**
     * Initially submitted by the airspace user, this defines the target speed in both Indicated Airspeed (IAS) and MACH so the aircraft can climb through the crossover altitude and target the MACH speed when needed.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link SpeedScheduleType }{@code >}
     *     
     */
    public JAXBElement<SpeedScheduleType> getClimbSchedule() {
        return climbSchedule;
    }

    /**
     * Sets the value of the climbSchedule property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link SpeedScheduleType }{@code >}
     *     
     * @see #getClimbSchedule()
     */
    public void setClimbSchedule(JAXBElement<SpeedScheduleType> value) {
        this.climbSchedule = value;
    }

    /**
     * A zero-wind, standard atmosphere, unconstrained descent profile reflective of the flight capabilities and desired parameters during descent.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link PerformanceProfileType }{@code >}
     *     
     */
    public JAXBElement<PerformanceProfileType> getDescentProfile() {
        return descentProfile;
    }

    /**
     * Sets the value of the descentProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link PerformanceProfileType }{@code >}
     *     
     * @see #getDescentProfile()
     */
    public void setDescentProfile(JAXBElement<PerformanceProfileType> value) {
        this.descentProfile = value;
    }

    /**
     * Initially submitted by the airspace user, this defines the target speed in both (Indicated Airspeed) IAS and MACH so the aircraft can descend through the crossover altitude and target the IAS speed when needed.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link SpeedScheduleType }{@code >}
     *     
     */
    public JAXBElement<SpeedScheduleType> getDescentSchedule() {
        return descentSchedule;
    }

    /**
     * Sets the value of the descentSchedule property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link SpeedScheduleType }{@code >}
     *     
     * @see #getDescentSchedule()
     */
    public void setDescentSchedule(JAXBElement<SpeedScheduleType> value) {
        this.descentSchedule = value;
    }

    /**
     * A container for information pertinent to a single point in a trajectory. The elements are ordered according to increasing time/distance from the start point.
     * 
     * Gets the value of the element property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the element property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getElement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RouteTrajectoryElementType }
     * </p>
     * 
     * 
     * @return
     *     The value of the element property.
     */
    public List<RouteTrajectoryElementType> getElement() {
        if (element == null) {
            element = new ArrayList<>();
        }
        return this.element;
    }

    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RouteTrajectoryGroupExtensionType }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<RouteTrajectoryGroupExtensionType> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * Contains information about the Flight Route. The route is comprised of Route Segments, which are comprised of Route Point/Airway pairs. Route also contains an expanded route.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link FlightRouteInformationType }{@code >}
     *     
     */
    public JAXBElement<FlightRouteInformationType> getRouteInformation() {
        return routeInformation;
    }

    /**
     * Sets the value of the routeInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link FlightRouteInformationType }{@code >}
     *     
     * @see #getRouteInformation()
     */
    public void setRouteInformation(JAXBElement<FlightRouteInformationType> value) {
        this.routeInformation = value;
    }

    /**
     * The estimated takeoff mass of the aircraft.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MassType }{@code >}
     *     
     */
    public JAXBElement<MassType> getTakeoffMass() {
        return takeoffMass;
    }

    /**
     * Sets the value of the takeoffMass property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MassType }{@code >}
     *     
     * @see #getTakeoffMass()
     */
    public void setTakeoffMass(JAXBElement<MassType> value) {
        this.takeoffMass = value;
    }

}
