//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import aero.fixm.base.RouteChangeExtensionType;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A requested change that is applicable to a route or trajectory point. Can be any of the several defined requested changes.
 * 
 * &lt;p&gt;Java class for RouteChangeType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="RouteChangeType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="cruiseClimbStart" type="{http://www.fixm.aero/flight/4.3}CruiseClimbStartType" minOccurs="0"/&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/base/4.3}RouteChangeExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="level" type="{http://www.fixm.aero/flight/4.3}CruisingLevelChangeType" minOccurs="0"/&gt;
 *         &lt;element name="speed" type="{http://www.fixm.aero/flight/4.3}CruisingSpeedChangeType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RouteChangeType", propOrder = {
    "cruiseClimbStart",
    "extension",
    "level",
    "speed"
})
public class RouteChangeType
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    /**
     * The parameters of a cruise climb executed at the associated significant point. It contains the following parameters: 1. the speed to be maintained during cruise climb; 2. either the minimum and maximum levels defining the layer to be occupied during cruise climb, or the level above which cruise climb is planned.
     * 
     */
    @XmlElementRef(name = "cruiseClimbStart", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<CruiseClimbStartType> cruiseClimbStart;
    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     */
    @XmlElement(nillable = true)
    protected List<RouteChangeExtensionType> extension;
    /**
     * The planned altitude that the aircraft will change to upon reaching the associated Significant Point along its Route.
     * 
     */
    @XmlElementRef(name = "level", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<CruisingLevelChangeType> level;
    /**
     * The planned speed  that the aircraft will change to upon reaching the associated Significant Point along its Route.
     * 
     */
    @XmlElementRef(name = "speed", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<CruisingSpeedChangeType> speed;

    /**
     * The parameters of a cruise climb executed at the associated significant point. It contains the following parameters: 1. the speed to be maintained during cruise climb; 2. either the minimum and maximum levels defining the layer to be occupied during cruise climb, or the level above which cruise climb is planned.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link CruiseClimbStartType }{@code >}
     *     
     */
    public JAXBElement<CruiseClimbStartType> getCruiseClimbStart() {
        return cruiseClimbStart;
    }

    /**
     * Sets the value of the cruiseClimbStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link CruiseClimbStartType }{@code >}
     *     
     * @see #getCruiseClimbStart()
     */
    public void setCruiseClimbStart(JAXBElement<CruiseClimbStartType> value) {
        this.cruiseClimbStart = value;
    }

    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RouteChangeExtensionType }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<RouteChangeExtensionType> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * The planned altitude that the aircraft will change to upon reaching the associated Significant Point along its Route.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link CruisingLevelChangeType }{@code >}
     *     
     */
    public JAXBElement<CruisingLevelChangeType> getLevel() {
        return level;
    }

    /**
     * Sets the value of the level property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link CruisingLevelChangeType }{@code >}
     *     
     * @see #getLevel()
     */
    public void setLevel(JAXBElement<CruisingLevelChangeType> value) {
        this.level = value;
    }

    /**
     * The planned speed  that the aircraft will change to upon reaching the associated Significant Point along its Route.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link CruisingSpeedChangeType }{@code >}
     *     
     */
    public JAXBElement<CruisingSpeedChangeType> getSpeed() {
        return speed;
    }

    /**
     * Sets the value of the speed property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link CruisingSpeedChangeType }{@code >}
     *     
     * @see #getSpeed()
     */
    public void setSpeed(JAXBElement<CruisingSpeedChangeType> value) {
        this.speed = value;
    }

}
