//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Indicates the route description is truncated at the preceding point
 * 
 * &lt;p&gt;Java class for RouteTruncationIndicatorType&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * &lt;pre&gt;{&#064;code
 * &lt;simpleType name="RouteTruncationIndicatorType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="ROUTE_TRUNCATION"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * }&lt;/pre&gt;
 * 
 */
@XmlType(name = "RouteTruncationIndicatorType")
@XmlEnum
public enum RouteTruncationIndicatorType {

    ROUTE_TRUNCATION;

    public String value() {
        return name();
    }

    public static RouteTruncationIndicatorType fromValue(String v) {
        return valueOf(v);
    }

}
