//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import java.io.Serializable;
import aero.fixm.base.RouteDesignatorType;
import aero.fixm.base.SidStarReferenceType;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The route (airway) to the next element on the route. Can be either an en route airway, standard instrument departure route, or standard instrument arrival route. [FIXM]
 * 
 * &lt;p&gt;Java class for RouteDesignatorToNextElementChoiceType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="RouteDesignatorToNextElementChoiceType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="otherRouteDesignator" type="{http://www.fixm.aero/flight/4.3}OtherRouteDesignatorType"/&gt;
 *         &lt;element name="routeDesignator" type="{http://www.fixm.aero/base/4.3}RouteDesignatorType"/&gt;
 *         &lt;element name="standardInstrumentArrival" type="{http://www.fixm.aero/base/4.3}SidStarReferenceType"/&gt;
 *         &lt;element name="standardInstrumentDeparture" type="{http://www.fixm.aero/base/4.3}SidStarReferenceType"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RouteDesignatorToNextElementChoiceType", propOrder = {
    "otherRouteDesignator",
    "routeDesignator",
    "standardInstrumentArrival",
    "standardInstrumentDeparture"
})
public class RouteDesignatorToNextElementChoiceType
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    /**
     * Indicates that the route to next element is either DIRECT or UNSPECIFIED.
     * 
     */
    @XmlSchemaType(name = "string")
    protected OtherRouteDesignatorType otherRouteDesignator;
    /**
     * The coded designator for a published ATS route or route segment.
     * 
     */
    protected RouteDesignatorType routeDesignator;
    /**
     * The textual designator of the Standard Instrument Arrival (STAR).
     * 
     */
    protected SidStarReferenceType standardInstrumentArrival;
    /**
     * This is the name of a published procedure extending from the departure runway to the start of the en route part of the aircraft's route.
     * 
     */
    protected SidStarReferenceType standardInstrumentDeparture;

    /**
     * Indicates that the route to next element is either DIRECT or UNSPECIFIED.
     * 
     * @return
     *     possible object is
     *     {@link OtherRouteDesignatorType }
     *     
     */
    public OtherRouteDesignatorType getOtherRouteDesignator() {
        return otherRouteDesignator;
    }

    /**
     * Sets the value of the otherRouteDesignator property.
     * 
     * @param value
     *     allowed object is
     *     {@link OtherRouteDesignatorType }
     *     
     * @see #getOtherRouteDesignator()
     */
    public void setOtherRouteDesignator(OtherRouteDesignatorType value) {
        this.otherRouteDesignator = value;
    }

    /**
     * The coded designator for a published ATS route or route segment.
     * 
     * @return
     *     possible object is
     *     {@link RouteDesignatorType }
     *     
     */
    public RouteDesignatorType getRouteDesignator() {
        return routeDesignator;
    }

    /**
     * Sets the value of the routeDesignator property.
     * 
     * @param value
     *     allowed object is
     *     {@link RouteDesignatorType }
     *     
     * @see #getRouteDesignator()
     */
    public void setRouteDesignator(RouteDesignatorType value) {
        this.routeDesignator = value;
    }

    /**
     * The textual designator of the Standard Instrument Arrival (STAR).
     * 
     * @return
     *     possible object is
     *     {@link SidStarReferenceType }
     *     
     */
    public SidStarReferenceType getStandardInstrumentArrival() {
        return standardInstrumentArrival;
    }

    /**
     * Sets the value of the standardInstrumentArrival property.
     * 
     * @param value
     *     allowed object is
     *     {@link SidStarReferenceType }
     *     
     * @see #getStandardInstrumentArrival()
     */
    public void setStandardInstrumentArrival(SidStarReferenceType value) {
        this.standardInstrumentArrival = value;
    }

    /**
     * This is the name of a published procedure extending from the departure runway to the start of the en route part of the aircraft's route.
     * 
     * @return
     *     possible object is
     *     {@link SidStarReferenceType }
     *     
     */
    public SidStarReferenceType getStandardInstrumentDeparture() {
        return standardInstrumentDeparture;
    }

    /**
     * Sets the value of the standardInstrumentDeparture property.
     * 
     * @param value
     *     allowed object is
     *     {@link SidStarReferenceType }
     *     
     * @see #getStandardInstrumentDeparture()
     */
    public void setStandardInstrumentDeparture(SidStarReferenceType value) {
        this.standardInstrumentDeparture = value;
    }

}
