//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The reason for special handling of a flight by ATS. [adapted from ICAO Doc 4444, Appendix 2, ITEM 18 STS/]
 * 
 * &lt;p&gt;Java class for SpecialHandlingReasonCodeType&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * &lt;pre&gt;{&#064;code
 * &lt;simpleType name="SpecialHandlingReasonCodeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="ALTRV"/&gt;
 *     &lt;enumeration value="ATFMX"/&gt;
 *     &lt;enumeration value="FFR"/&gt;
 *     &lt;enumeration value="FLTCK"/&gt;
 *     &lt;enumeration value="HAZMAT"/&gt;
 *     &lt;enumeration value="HEAD"/&gt;
 *     &lt;enumeration value="HOSP"/&gt;
 *     &lt;enumeration value="HUM"/&gt;
 *     &lt;enumeration value="MARSA"/&gt;
 *     &lt;enumeration value="MEDEVAC"/&gt;
 *     &lt;enumeration value="NONRVSM"/&gt;
 *     &lt;enumeration value="SAR"/&gt;
 *     &lt;enumeration value="STATE"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * }&lt;/pre&gt;
 * 
 */
@XmlType(name = "SpecialHandlingReasonCodeType")
@XmlEnum
public enum SpecialHandlingReasonCodeType {


    /**
     * for a flight operated in accordance with an altitude reservation [ICAO Doc 4444, Appendix 2, ITEM 18 STS/]
     * 
     */
    ALTRV,

    /**
     * for a flight approved for exemption from ATFM measures by the appropriate ATS authority; [ICAO Doc 4444, Appendix 2, ITEM 18 STS/]
     * 
     */
    ATFMX,

    /**
     * fire-fighting; [ICAO Doc 4444, Appendix 2, ITEM 18 STS/]
     * 
     */
    FFR,

    /**
     * flight check for calibration of navaids; [ICAO Doc 4444, Appendix 2, ITEM 18 STS/]
     * 
     */
    FLTCK,

    /**
     * for a flight carrying hazardous material; [ICAO Doc 4444, Appendix 2, ITEM 18 STS/]
     * 
     */
    HAZMAT,

    /**
     * a flight with Head of State status; [ICAO Doc 4444, Appendix 2, ITEM 18 STS/]
     * 
     */
    HEAD,

    /**
     * for a medical flight declared by medical authorities; [ICAO Doc 4444, Appendix 2, ITEM 18 STS/]
     * 
     */
    HOSP,

    /**
     * for a flight operating on a humanitarian mission; [ICAO Doc 4444, Appendix 2, ITEM 18 STS/]
     * 
     */
    HUM,

    /**
     * for a flight for which a military entity assumes responsibility for separation of military aircraft; [ICAO Doc 4444, Appendix 2, ITEM 18 STS/]
     * 
     */
    MARSA,

    /**
     * for a life critical medical emergency evacuation; [ICAO Doc 4444, Appendix 2, ITEM 18 STS/]
     * 
     */
    MEDEVAC,

    /**
     * for a non-RVSM capable flight intending to operate in RVSM airspace; [ICAO Doc 4444, Appendix 2, ITEM 18 STS/]
     * 
     */
    NONRVSM,

    /**
     * for a flight engaged in a search and rescue mission; [ICAO Doc 4444, Appendix 2, ITEM 18 STS/]
     * 
     */
    SAR,

    /**
     * for a flight engaged in military, customs or police services. [ICAO Doc 4444, Appendix 2, ITEM 18 STS/]
     * 
     */
    STATE;

    public String value() {
        return name();
    }

    public static SpecialHandlingReasonCodeType fromValue(String v) {
        return valueOf(v);
    }

}
