//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import aero.fixm.base.IndicatedAirspeedType;
import aero.fixm.base.SpeedScheduleExtensionType;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Defines the speed schedule for climb and descent of the aircraft through the crossover altitude.
 * 
 * &lt;p&gt;Java class for SpeedScheduleType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="SpeedScheduleType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/base/4.3}SpeedScheduleExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="initialSpeed" type="{http://www.fixm.aero/base/4.3}IndicatedAirspeedType" minOccurs="0"/&gt;
 *         &lt;element name="subsequentSpeed" type="{http://www.fixm.aero/base/4.3}IndicatedAirspeedType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpeedScheduleType", propOrder = {
    "extension",
    "initialSpeed",
    "subsequentSpeed"
})
public class SpeedScheduleType
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     */
    @XmlElement(nillable = true)
    protected List<SpeedScheduleExtensionType> extension;
    /**
     * Initial speed of the aircraft during the climb
     * 
     */
    @XmlElementRef(name = "initialSpeed", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<IndicatedAirspeedType> initialSpeed;
    /**
     * Subsequent speed of the aircraft during the climb
     * 
     */
    @XmlElementRef(name = "subsequentSpeed", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<IndicatedAirspeedType> subsequentSpeed;

    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SpeedScheduleExtensionType }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<SpeedScheduleExtensionType> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * Initial speed of the aircraft during the climb
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link IndicatedAirspeedType }{@code >}
     *     
     */
    public JAXBElement<IndicatedAirspeedType> getInitialSpeed() {
        return initialSpeed;
    }

    /**
     * Sets the value of the initialSpeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link IndicatedAirspeedType }{@code >}
     *     
     * @see #getInitialSpeed()
     */
    public void setInitialSpeed(JAXBElement<IndicatedAirspeedType> value) {
        this.initialSpeed = value;
    }

    /**
     * Subsequent speed of the aircraft during the climb
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link IndicatedAirspeedType }{@code >}
     *     
     */
    public JAXBElement<IndicatedAirspeedType> getSubsequentSpeed() {
        return subsequentSpeed;
    }

    /**
     * Sets the value of the subsequentSpeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link IndicatedAirspeedType }{@code >}
     *     
     * @see #getSubsequentSpeed()
     */
    public void setSubsequentSpeed(JAXBElement<IndicatedAirspeedType> value) {
        this.subsequentSpeed = value;
    }

}
