//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.datatype.Duration;
import aero.fixm.base.PersonOrOrganizationType;
import aero.fixm.base.SupplementaryInformationExtensionType;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A container for supplementary information about the flight. This container does not capture the complete set of elements described in ICAO Doc 4444 ITEM 19 "Supplementary Information"; it only contains those elements that could not be modeled more logically in other FIXM structures. [FIXM]
 * 
 * &lt;p&gt;Java class for SupplementaryInformationType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="SupplementaryInformationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/base/4.3}SupplementaryInformationExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="fuelEndurance" type="{http://www.fixm.aero/base/4.3}DurationType" minOccurs="0"/&gt;
 *         &lt;element name="personsOnBoard" type="{http://www.fixm.aero/base/4.3}CountType" minOccurs="0"/&gt;
 *         &lt;element name="pilotInCommand" type="{http://www.fixm.aero/base/4.3}PersonOrOrganizationType" minOccurs="0"/&gt;
 *         &lt;element name="supplementaryInformationSource" type="{http://www.fixm.aero/flight/4.3}SupplementaryInformationSourceChoiceType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SupplementaryInformationType", propOrder = {
    "extension",
    "fuelEndurance",
    "personsOnBoard",
    "pilotInCommand",
    "supplementaryInformationSource"
})
public class SupplementaryInformationType
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     */
    @XmlElement(nillable = true)
    protected List<SupplementaryInformationExtensionType> extension;
    /**
     * The estimated maximum length of time the aircraft can spend in the cruise phase of flight, determined by the amount of fuel at takeoff. [FIXM]
     * 
     */
    @XmlElementRef(name = "fuelEndurance", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<Duration> fuelEndurance;
    /**
     * The total number of persons (passengers and crew) on board the aircraft. [ICAO Doc 4444, Appendix 2, Item 19]
     * 
     */
    @XmlElementRef(name = "personsOnBoard", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<Integer> personsOnBoard;
    /**
     * The pilot designated by the operator, or in the case of general aviation, the owner, as being in command and charged with the safe conduct of a flight. [ICAO Doc 4444]
     * 
     */
    @XmlElementRef(name = "pilotInCommand", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<PersonOrOrganizationType> pilotInCommand;
    /**
     * Describes the source of the supplementary information. Can be either a Person/Organization or ATC Unit.
     * 
     * A Supplementary Information Source can be identified using a location identifier (from Doc. 7910 + Doc. 8585) for an ATS unit; an AFTN address; FF-ICE Participant identification per B-2.28; or appropriate contact information per B-2.12.
     * 
     */
    @XmlElementRef(name = "supplementaryInformationSource", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<SupplementaryInformationSourceChoiceType> supplementaryInformationSource;

    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SupplementaryInformationExtensionType }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<SupplementaryInformationExtensionType> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * The estimated maximum length of time the aircraft can spend in the cruise phase of flight, determined by the amount of fuel at takeoff. [FIXM]
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Duration }{@code >}
     *     
     */
    public JAXBElement<Duration> getFuelEndurance() {
        return fuelEndurance;
    }

    /**
     * Sets the value of the fuelEndurance property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Duration }{@code >}
     *     
     * @see #getFuelEndurance()
     */
    public void setFuelEndurance(JAXBElement<Duration> value) {
        this.fuelEndurance = value;
    }

    /**
     * The total number of persons (passengers and crew) on board the aircraft. [ICAO Doc 4444, Appendix 2, Item 19]
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getPersonsOnBoard() {
        return personsOnBoard;
    }

    /**
     * Sets the value of the personsOnBoard property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     * @see #getPersonsOnBoard()
     */
    public void setPersonsOnBoard(JAXBElement<Integer> value) {
        this.personsOnBoard = value;
    }

    /**
     * The pilot designated by the operator, or in the case of general aviation, the owner, as being in command and charged with the safe conduct of a flight. [ICAO Doc 4444]
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link PersonOrOrganizationType }{@code >}
     *     
     */
    public JAXBElement<PersonOrOrganizationType> getPilotInCommand() {
        return pilotInCommand;
    }

    /**
     * Sets the value of the pilotInCommand property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link PersonOrOrganizationType }{@code >}
     *     
     * @see #getPilotInCommand()
     */
    public void setPilotInCommand(JAXBElement<PersonOrOrganizationType> value) {
        this.pilotInCommand = value;
    }

    /**
     * Describes the source of the supplementary information. Can be either a Person/Organization or ATC Unit.
     * 
     * A Supplementary Information Source can be identified using a location identifier (from Doc. 7910 + Doc. 8585) for an ATS unit; an AFTN address; FF-ICE Participant identification per B-2.28; or appropriate contact information per B-2.12.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link SupplementaryInformationSourceChoiceType }{@code >}
     *     
     */
    public JAXBElement<SupplementaryInformationSourceChoiceType> getSupplementaryInformationSource() {
        return supplementaryInformationSource;
    }

    /**
     * Sets the value of the supplementaryInformationSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link SupplementaryInformationSourceChoiceType }{@code >}
     *     
     * @see #getSupplementaryInformationSource()
     */
    public void setSupplementaryInformationSource(JAXBElement<SupplementaryInformationSourceChoiceType> value) {
        this.supplementaryInformationSource = value;
    }

}
