//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A code indicating the SSR and ADS capability of the aircraft. [FIXM]
 * 
 * &lt;p&gt;Java class for SurveillanceCapabilityCodeType&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * &lt;pre&gt;{&#064;code
 * &lt;simpleType name="SurveillanceCapabilityCodeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="A"/&gt;
 *     &lt;enumeration value="B1"/&gt;
 *     &lt;enumeration value="B2"/&gt;
 *     &lt;enumeration value="C"/&gt;
 *     &lt;enumeration value="D1"/&gt;
 *     &lt;enumeration value="E"/&gt;
 *     &lt;enumeration value="G1"/&gt;
 *     &lt;enumeration value="H"/&gt;
 *     &lt;enumeration value="I"/&gt;
 *     &lt;enumeration value="L"/&gt;
 *     &lt;enumeration value="P"/&gt;
 *     &lt;enumeration value="S"/&gt;
 *     &lt;enumeration value="U1"/&gt;
 *     &lt;enumeration value="U2"/&gt;
 *     &lt;enumeration value="V1"/&gt;
 *     &lt;enumeration value="V2"/&gt;
 *     &lt;enumeration value="X"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * }&lt;/pre&gt;
 * 
 */
@XmlType(name = "SurveillanceCapabilityCodeType")
@XmlEnum
public enum SurveillanceCapabilityCodeType {


    /**
     * Transponder-Mode A (4 digits-4,096 codes)
     * 
     */
    A("A"),

    /**
     * ADS-B with dedicated 1090 MHz ADS-B out capability
     * 
     */
    @XmlEnumValue("B1")
    B_1("B1"),

    /**
     * ADS-B with dedicated 1090 MHz ADS-B out and in capability
     * 
     */
    @XmlEnumValue("B2")
    B_2("B2"),

    /**
     * Transponder-Mode A (4 digits-4,096 codes) and Mode C
     * 
     */
    C("C"),

    /**
     * ADS-C with FANS 1/A capabilities
     * 
     */
    @XmlEnumValue("D1")
    D_1("D1"),

    /**
     * Transponder Mode S including aircraft identification, pressure-altitude, and extended squitter capability (ADS-B)
     * 
     */
    E("E"),

    /**
     * ADS-C with ATN capabilities
     * 
     */
    @XmlEnumValue("G1")
    G_1("G1"),

    /**
     * Transponder Mode S including aircraft identification, pressure-altitude, and enhanced surveillance capability
     * 
     */
    H("H"),

    /**
     * Transponder Mode S including aircraft identification, but no pressure-altitude capability
     * 
     */
    I("I"),

    /**
     * Transponder Mode S including aircraft identification, pressure-altitude, extended squitter, and enhanced surveillance capability
     * 
     */
    L("L"),

    /**
     * Transponder Mode S including pressure-altitude, but no aircraft identification capability
     * 
     */
    P("P"),

    /**
     * Transponder-Mode S, including both pressure-altitude and aircraft identification transmission
     * 
     */
    S("S"),

    /**
     * ADS-B out capability using UAT
     * 
     */
    @XmlEnumValue("U1")
    U_1("U1"),

    /**
     * ADS-B out and in capability using UAT
     * 
     */
    @XmlEnumValue("U2")
    U_2("U2"),

    /**
     * ADS-B out capability using VDL mode 4
     * 
     */
    @XmlEnumValue("V1")
    V_1("V1"),

    /**
     * ADS-B in and out capability using VDL mode 4
     * 
     */
    @XmlEnumValue("V2")
    V_2("V2"),

    /**
     * Transponder Mode S with neither aircraft identification nor pressure-altitude capability
     * 
     */
    X("X");
    private final String value;

    SurveillanceCapabilityCodeType(String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static SurveillanceCapabilityCodeType fromValue(String v) {
        for (SurveillanceCapabilityCodeType c: SurveillanceCapabilityCodeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
