//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import aero.fixm.base.SurveillanceCapabilitiesExtensionType;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The serviceable Secondary Surveillance Radar (SSR) and/or Automatic Dependent Surveillance (ADS) equipment available on the aircraft at the time of flight that may be used to identify and/or locate the aircraft. [FIXM]
 * 
 * &lt;p&gt;Java class for SurveillanceCapabilitiesType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="SurveillanceCapabilitiesType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/base/4.3}SurveillanceCapabilitiesExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="otherSurveillanceCapabilities" type="{http://www.fixm.aero/base/4.3}CharacterStringType" minOccurs="0"/&gt;
 *         &lt;element name="surveillanceCapabilityCode" type="{http://www.fixm.aero/flight/4.3}SurveillanceCapabilityCodeListType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SurveillanceCapabilitiesType", propOrder = {
    "extension",
    "otherSurveillanceCapabilities",
    "surveillanceCapabilityCode"
})
public class SurveillanceCapabilitiesType
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     */
    @XmlElement(nillable = true)
    protected List<SurveillanceCapabilitiesExtensionType> extension;
    /**
     * Additional surveillance capabilities available on board the aircraft.
     * 
     */
    @XmlElementRef(name = "otherSurveillanceCapabilities", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<String> otherSurveillanceCapabilities;
    /**
     * A code indicating the SSR and ADS capability of the aircraft. [FIXM]
     * 
     */
    @XmlElementRef(name = "surveillanceCapabilityCode", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected List<JAXBElement<List<SurveillanceCapabilityCodeType>>> surveillanceCapabilityCode;

    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SurveillanceCapabilitiesExtensionType }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<SurveillanceCapabilitiesExtensionType> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * Additional surveillance capabilities available on board the aircraft.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getOtherSurveillanceCapabilities() {
        return otherSurveillanceCapabilities;
    }

    /**
     * Sets the value of the otherSurveillanceCapabilities property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     * @see #getOtherSurveillanceCapabilities()
     */
    public void setOtherSurveillanceCapabilities(JAXBElement<String> value) {
        this.otherSurveillanceCapabilities = value;
    }

    /**
     * A code indicating the SSR and ADS capability of the aircraft. [FIXM]
     * 
     * Gets the value of the surveillanceCapabilityCode property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the surveillanceCapabilityCode property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getSurveillanceCapabilityCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link List }{@code <}{@link SurveillanceCapabilityCodeType }{@code >}{@code >}
     * </p>
     * 
     * 
     * @return
     *     The value of the surveillanceCapabilityCode property.
     */
    public List<JAXBElement<List<SurveillanceCapabilityCodeType>>> getSurveillanceCapabilityCode() {
        if (surveillanceCapabilityCode == null) {
            surveillanceCapabilityCode = new ArrayList<>();
        }
        return this.surveillanceCapabilityCode;
    }

}
