//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import aero.fixm.base.TimeChoiceType;
import aero.fixm.base.TimeConstraintExtensionType;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The time constraint applicable to a specific point on the route.
 * 
 * &lt;p&gt;Java class for TimeConstraintType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="TimeConstraintType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/base/4.3}TimeConstraintExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="timeSpecification" type="{http://www.fixm.aero/base/4.3}TimeChoiceType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TimeConstraintType", propOrder = {
    "extension",
    "timeSpecification"
})
public class TimeConstraintType
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     */
    @XmlElement(nillable = true)
    protected List<TimeConstraintExtensionType> extension;
    /**
     * Date and time associated with the constraint.
     * 
     */
    @XmlElementRef(name = "timeSpecification", namespace = "http://www.fixm.aero/flight/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<TimeChoiceType> timeSpecification;

    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TimeConstraintExtensionType }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<TimeConstraintExtensionType> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * Date and time associated with the constraint.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link TimeChoiceType }{@code >}
     *     
     */
    public JAXBElement<TimeChoiceType> getTimeSpecification() {
        return timeSpecification;
    }

    /**
     * Sets the value of the timeSpecification property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link TimeChoiceType }{@code >}
     *     
     * @see #getTimeSpecification()
     */
    public void setTimeSpecification(JAXBElement<TimeChoiceType> value) {
        this.timeSpecification = value;
    }

}
