//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Indication of the rule under which an air traffic controller provides categorical handling of a flight. [FIXM]
 * 
 * &lt;p&gt;Java class for TypeOfFlightType&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * &lt;pre&gt;{&#064;code
 * &lt;simpleType name="TypeOfFlightType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="G"/&gt;
 *     &lt;enumeration value="M"/&gt;
 *     &lt;enumeration value="N"/&gt;
 *     &lt;enumeration value="S"/&gt;
 *     &lt;enumeration value="X"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * }&lt;/pre&gt;
 * 
 */
@XmlType(name = "TypeOfFlightType")
@XmlEnum
public enum TypeOfFlightType {


    /**
     * General aviation [ICAO Doc 4444, Item 8]
     * 
     */
    G,

    /**
     * Military [ICAO Doc 4444, Item 8]
     * 
     */
    M,

    /**
     * Non-scheduled air transport operation [ICAO Doc 4444, Item 8]
     * 
     */
    N,

    /**
     * Scheduled air service [ICAO Doc 4444, Item 8]
     * 
     */
    S,

    /**
     * Other than any of the defined categories above. [ICAO Doc 4444, Item 8]
     * 
     */
    X;

    public String value() {
        return name();
    }

    public static TypeOfFlightType fromValue(String v) {
        return valueOf(v);
    }

}
