//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.flight;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * ICAO classification of the aircraft wake turbulence, based on the maximum certified take off mass. [FIXM}
 * 
 * &lt;p&gt;Java class for WakeTurbulenceCategoryType&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * &lt;pre&gt;{&#064;code
 * &lt;simpleType name="WakeTurbulenceCategoryType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="H"/&gt;
 *     &lt;enumeration value="J"/&gt;
 *     &lt;enumeration value="L"/&gt;
 *     &lt;enumeration value="M"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * }&lt;/pre&gt;
 * 
 */
@XmlType(name = "WakeTurbulenceCategoryType")
@XmlEnum
public enum WakeTurbulenceCategoryType {


    /**
     * An aircraft type with a maximum certified take-off mass of 136000 kg or more. [ICAO Doc 4444, Appendix 2, ITEM M]
     * 
     */
    H,

    /**
     * A super heavy aircraft type e.g. the Airbus A380-800. (In the order of 560,000kg). [FIXM]
     * 
     */
    J,

    /**
     * An aircraft type with a maximum certified take-off mass of 7000 kg or less. [ICAO Doc 4444, Appendix 2, ITEM M]
     * 
     */
    L,

    /**
     * An aircraft type with a maximum certified take-off mass of less than 136000 kg. but more than 7000 kg. [ICAO Doc 4444, Appendix 2, ITEM M]
     * 
     */
    M;

    public String value() {
        return name();
    }

    public static WakeTurbulenceCategoryType fromValue(String v) {
        return valueOf(v);
    }

}
