//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.base;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * An altitude with a specified source. [FIXM]
 * 
 * &lt;p&gt;Java class for AltitudeWithSourceType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="AltitudeWithSourceType"&gt;
 *   &lt;simpleContent&gt;
 *     &lt;extension base="&lt;http://www.fixm.aero/base/4.3&gt;AltitudeType"&gt;
 *       &lt;attribute name="source" use="required" type="{http://www.fixm.aero/base/4.3}AltitudeSourceType" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AltitudeWithSourceType")
public class AltitudeWithSourceType
    extends AltitudeType
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    /**
     * The source of the altitude. [FIXM]
     * 
     */
    @XmlAttribute(name = "source", required = true)
    protected AltitudeSourceType source;

    /**
     * The source of the altitude. [FIXM]
     * 
     * @return
     *     possible object is
     *     {@link AltitudeSourceType }
     *     
     */
    public AltitudeSourceType getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link AltitudeSourceType }
     *     
     * @see #getSource()
     */
    public void setSource(AltitudeSourceType value) {
        this.source = value;
    }

}
