//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.base;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A reference to an area control centre, approach control unit or aerodrome control tower being either:
 * - the ICAO location indicator of the atc unit, as listed in ICAO Doc 7910
 * - if no ICAO location indicator is available, the ATC unit name and optionally its geographical position. [FIXM]
 * 
 * &lt;p&gt;Java class for AtcUnitReferenceType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="AtcUnitReferenceType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="atcUnitNameOrAlternate" type="{http://www.fixm.aero/base/4.3}TextNameType" minOccurs="0"/&gt;
 *         &lt;element name="controlSectorDesignator" type="{http://www.fixm.aero/base/4.3}AirspaceDesignatorType" minOccurs="0"/&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/base/4.3}AtcUnitReferenceExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="locationIndicator" type="{http://www.fixm.aero/base/4.3}LocationIndicatorType" minOccurs="0"/&gt;
 *         &lt;element name="position" type="{http://www.fixm.aero/base/4.3}GeographicalPositionType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="href" type="{http://www.fixm.aero/base/4.3}HypertextReferenceType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AtcUnitReferenceType", propOrder = {
    "atcUnitNameOrAlternate",
    "controlSectorDesignator",
    "extension",
    "locationIndicator",
    "position"
})
public class AtcUnitReferenceType
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    /**
     * The full textual name of the ATC unit [adapted from AIXM 5.1] or an alternate identifier for the unit. [FIXM]
     * 
     */
    @XmlElementRef(name = "atcUnitNameOrAlternate", namespace = "http://www.fixm.aero/base/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<String> atcUnitNameOrAlternate;
    /**
     * A published sequence of characters allowing the identification of a subdivision of a designated control area within which responsibility is assigned to one controller or to a small group of controllers.
     * 
     */
    @XmlElementRef(name = "controlSectorDesignator", namespace = "http://www.fixm.aero/base/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<AirspaceDesignatorType> controlSectorDesignator;
    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     */
    @XmlElement(nillable = true)
    protected List<AtcUnitReferenceExtensionType> extension;
    /**
     * A four-letter code group formulated in accordance with rules prescribed by ICAO and assigned to the atc unit. [Specialised from ICAO Annex 10] The list of ICAO location indicators is provided by ICAO Doc 7910.
     * 
     */
    @XmlElementRef(name = "locationIndicator", namespace = "http://www.fixm.aero/base/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<String> locationIndicator;
    /**
     * The geographical point of the Unit. [AIXM 5.1]
     * 
     */
    @XmlElementRef(name = "position", namespace = "http://www.fixm.aero/base/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<GeographicalPositionType> position;
    /**
     * Provides an optional mechanism enabling FIXM aeronautical fields to be supplemented with references to AIXM features.  This field should be considered functionally equivalent to the xlink:href field used in AIXM to reference features. [FIXM]
     * 
     */
    @XmlAttribute(name = "href")
    protected String href;

    /**
     * The full textual name of the ATC unit [adapted from AIXM 5.1] or an alternate identifier for the unit. [FIXM]
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getAtcUnitNameOrAlternate() {
        return atcUnitNameOrAlternate;
    }

    /**
     * Sets the value of the atcUnitNameOrAlternate property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     * @see #getAtcUnitNameOrAlternate()
     */
    public void setAtcUnitNameOrAlternate(JAXBElement<String> value) {
        this.atcUnitNameOrAlternate = value;
    }

    /**
     * A published sequence of characters allowing the identification of a subdivision of a designated control area within which responsibility is assigned to one controller or to a small group of controllers.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AirspaceDesignatorType }{@code >}
     *     
     */
    public JAXBElement<AirspaceDesignatorType> getControlSectorDesignator() {
        return controlSectorDesignator;
    }

    /**
     * Sets the value of the controlSectorDesignator property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AirspaceDesignatorType }{@code >}
     *     
     * @see #getControlSectorDesignator()
     */
    public void setControlSectorDesignator(JAXBElement<AirspaceDesignatorType> value) {
        this.controlSectorDesignator = value;
    }

    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AtcUnitReferenceExtensionType }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<AtcUnitReferenceExtensionType> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * A four-letter code group formulated in accordance with rules prescribed by ICAO and assigned to the atc unit. [Specialised from ICAO Annex 10] The list of ICAO location indicators is provided by ICAO Doc 7910.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLocationIndicator() {
        return locationIndicator;
    }

    /**
     * Sets the value of the locationIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     * @see #getLocationIndicator()
     */
    public void setLocationIndicator(JAXBElement<String> value) {
        this.locationIndicator = value;
    }

    /**
     * The geographical point of the Unit. [AIXM 5.1]
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link GeographicalPositionType }{@code >}
     *     
     */
    public JAXBElement<GeographicalPositionType> getPosition() {
        return position;
    }

    /**
     * Sets the value of the position property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link GeographicalPositionType }{@code >}
     *     
     * @see #getPosition()
     */
    public void setPosition(JAXBElement<GeographicalPositionType> value) {
        this.position = value;
    }

    /**
     * Provides an optional mechanism enabling FIXM aeronautical fields to be supplemented with references to AIXM features.  This field should be considered functionally equivalent to the xlink:href field used in AIXM to reference features. [FIXM]
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHref() {
        return href;
    }

    /**
     * Sets the value of the href property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getHref()
     */
    public void setHref(String value) {
        this.href = value;
    }

}
