//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.base;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A data type used to represent direction in the coordinate reference system. [ISO 19107, chapter 6.3.12.1]
 * 
 * The value of a bearing indication (at a given point) is measured as the angle between the bearing and either True North or Magnetic North. The angle is measured clockwise from 0 degrees up to and including 360 degrees. The value can also be a VOR radial.  [AIXM 5.1]
 * 
 * &lt;p&gt;Java class for BearingType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="BearingType"&gt;
 *   &lt;simpleContent&gt;
 *     &lt;extension base="&lt;http://www.fixm.aero/base/4.3&gt;AngleType"&gt;
 *       &lt;attribute name="zeroBearingType" use="required" type="{http://www.fixm.aero/base/4.3}ZeroBearingTypeType" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BearingType")
public class BearingType
    extends AngleType
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    /**
     * A code indicating the direction of the zero bearing.
     * 
     */
    @XmlAttribute(name = "zeroBearingType", required = true)
    protected ZeroBearingTypeType zeroBearingType;

    /**
     * A code indicating the direction of the zero bearing.
     * 
     * @return
     *     possible object is
     *     {@link ZeroBearingTypeType }
     *     
     */
    public ZeroBearingTypeType getZeroBearingType() {
        return zeroBearingType;
    }

    /**
     * Sets the value of the zeroBearingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZeroBearingTypeType }
     *     
     * @see #getZeroBearingType()
     */
    public void setZeroBearingType(ZeroBearingTypeType value) {
        this.zeroBearingType = value;
    }

}
