//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.base;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A choice between flight level or altitude or VFR specification.
 * 
 * &lt;p&gt;Java class for FlightLevelOrAltitudeOrVfrChoiceType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="FlightLevelOrAltitudeOrVfrChoiceType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="altitude" type="{http://www.fixm.aero/base/4.3}AltitudeType"/&gt;
 *         &lt;element name="flightLevel" type="{http://www.fixm.aero/base/4.3}FlightLevelType"/&gt;
 *         &lt;element name="visualFlightRules" type="{http://www.fixm.aero/base/4.3}VisualFlightRulesLevelType"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FlightLevelOrAltitudeOrVfrChoiceType", propOrder = {
    "altitude",
    "flightLevel",
    "visualFlightRules"
})
public class FlightLevelOrAltitudeOrVfrChoiceType
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    /**
     * Altitude specification.
     * 
     */
    protected AltitudeType altitude;
    /**
     * Flight Level specification.
     * 
     */
    protected FlightLevelType flightLevel;
    /**
     * Visual Flight Rules specification.
     * 
     */
    @XmlSchemaType(name = "string")
    protected VisualFlightRulesLevelType visualFlightRules;

    /**
     * Altitude specification.
     * 
     * @return
     *     possible object is
     *     {@link AltitudeType }
     *     
     */
    public AltitudeType getAltitude() {
        return altitude;
    }

    /**
     * Sets the value of the altitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link AltitudeType }
     *     
     * @see #getAltitude()
     */
    public void setAltitude(AltitudeType value) {
        this.altitude = value;
    }

    /**
     * Flight Level specification.
     * 
     * @return
     *     possible object is
     *     {@link FlightLevelType }
     *     
     */
    public FlightLevelType getFlightLevel() {
        return flightLevel;
    }

    /**
     * Sets the value of the flightLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlightLevelType }
     *     
     * @see #getFlightLevel()
     */
    public void setFlightLevel(FlightLevelType value) {
        this.flightLevel = value;
    }

    /**
     * Visual Flight Rules specification.
     * 
     * @return
     *     possible object is
     *     {@link VisualFlightRulesLevelType }
     *     
     */
    public VisualFlightRulesLevelType getVisualFlightRules() {
        return visualFlightRules;
    }

    /**
     * Sets the value of the visualFlightRules property.
     * 
     * @param value
     *     allowed object is
     *     {@link VisualFlightRulesLevelType }
     *     
     * @see #getVisualFlightRules()
     */
    public void setVisualFlightRules(VisualFlightRulesLevelType value) {
        this.visualFlightRules = value;
    }

}
