//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.base;

import java.io.Serializable;
import java.math.BigDecimal;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;


/**
 * The measure of distance as an integral, for example the length of curve, the perimeter of a polygon as the length of the boundary. [ISO 19103, chapter 6.5.7.6]
 * 
 * &lt;p&gt;Java class for LengthType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="LengthType"&gt;
 *   &lt;simpleContent&gt;
 *     &lt;extension base="&lt;http://www.fixm.aero/base/4.3&gt;RestrictedMeasureType"&gt;
 *       &lt;attribute name="uom" use="required" type="{http://www.fixm.aero/base/4.3}UomLengthType" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LengthType", propOrder = {
    "value"
})
@XmlSeeAlso({
    DistanceType.class
})
public class LengthType
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    /**
     * Helper class for restrictions on measures.  [FIXM]
     * 
     */
    @XmlValue
    protected BigDecimal value;
    /**
     * Unit of measure
     * 
     */
    @XmlAttribute(name = "uom", required = true)
    protected UomLengthType uom;

    /**
     * Helper class for restrictions on measures.  [FIXM]
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getValue()
     */
    public void setValue(BigDecimal value) {
        this.value = value;
    }

    /**
     * Unit of measure
     * 
     * @return
     *     possible object is
     *     {@link UomLengthType }
     *     
     */
    public UomLengthType getUom() {
        return uom;
    }

    /**
     * Sets the value of the uom property.
     * 
     * @param value
     *     allowed object is
     *     {@link UomLengthType }
     *     
     * @see #getUom()
     */
    public void setUom(UomLengthType value) {
        this.uom = value;
    }

}
