//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.base;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A radio navigation aid used in defining an ATS route, the flight path of an aircraft or for other navigation or ATS purposes. [FIXM]
 * 
 * The coded designator of a navaid is not always sufficient for unambiguously referring to that feature: 
 * The en-route navaids (VOR, DME, NDB) designator is supposed to be unique (according to ICAO Annex 11) within 600 NM. This means that these designators are not unique world-wide. For airport navaids, there is no limitation.
 * 
 * The combinations of fields that would make the references unique are designator + position + navaid service type.
 * 
 * This FIXM class adds two optional properties 'position' and 'navaidServiceType' which may be used as a complement to the 'designator' information in order to remove any ambiguity on the coded designator.
 * 
 * &lt;p&gt;Java class for NavaidType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="NavaidType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="designator" type="{http://www.fixm.aero/base/4.3}NavaidDesignatorType"/&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/base/4.3}NavaidExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="navaidServiceType" type="{http://www.fixm.aero/base/4.3}NavaidServiceTypeType" minOccurs="0"/&gt;
 *         &lt;element name="position" type="{http://www.fixm.aero/base/4.3}GeographicalPositionType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="href" type="{http://www.fixm.aero/base/4.3}HypertextReferenceType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NavaidType", propOrder = {
    "designator",
    "extension",
    "navaidServiceType",
    "position"
})
public class NavaidType
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    /**
     * The name of the navaid.
     * 
     */
    @XmlElement(required = true)
    protected String designator;
    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     */
    @XmlElement(nillable = true)
    protected List<NavaidExtensionType> extension;
    /**
     * Type of the navaid service. [AIXM 5.1]
     * This optional field may be used as a complement of the designator in order to achieve unambiguous reference to the navaid. 
     * The combinations of fields that would make the reference unique are designator + position + navaid service type.
     * 
     */
    @XmlElementRef(name = "navaidServiceType", namespace = "http://www.fixm.aero/base/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<NavaidServiceTypeType> navaidServiceType;
    /**
     * The values of latitude and longitude that define the position of the Navaid on the surface of the Earth with respect to a reference datum. [specialised from ICAO Doc 9881]
     * 
     * This optional field may be used to achieve unambiguous reference to the navaid. 
     * The combinations of fields that would make the reference unique are name + position + navaid service type.
     * 
     */
    @XmlElementRef(name = "position", namespace = "http://www.fixm.aero/base/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<GeographicalPositionType> position;
    /**
     * Provides an optional mechanism enabling FIXM aeronautical fields to be supplemented with references to AIXM features.  This field should be considered functionally equivalent to the xlink:href field used in AIXM to reference features. [FIXM]
     * 
     */
    @XmlAttribute(name = "href")
    protected String href;

    /**
     * The name of the navaid.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesignator() {
        return designator;
    }

    /**
     * Sets the value of the designator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getDesignator()
     */
    public void setDesignator(String value) {
        this.designator = value;
    }

    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NavaidExtensionType }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<NavaidExtensionType> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * Type of the navaid service. [AIXM 5.1]
     * This optional field may be used as a complement of the designator in order to achieve unambiguous reference to the navaid. 
     * The combinations of fields that would make the reference unique are designator + position + navaid service type.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link NavaidServiceTypeType }{@code >}
     *     
     */
    public JAXBElement<NavaidServiceTypeType> getNavaidServiceType() {
        return navaidServiceType;
    }

    /**
     * Sets the value of the navaidServiceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link NavaidServiceTypeType }{@code >}
     *     
     * @see #getNavaidServiceType()
     */
    public void setNavaidServiceType(JAXBElement<NavaidServiceTypeType> value) {
        this.navaidServiceType = value;
    }

    /**
     * The values of latitude and longitude that define the position of the Navaid on the surface of the Earth with respect to a reference datum. [specialised from ICAO Doc 9881]
     * 
     * This optional field may be used to achieve unambiguous reference to the navaid. 
     * The combinations of fields that would make the reference unique are name + position + navaid service type.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link GeographicalPositionType }{@code >}
     *     
     */
    public JAXBElement<GeographicalPositionType> getPosition() {
        return position;
    }

    /**
     * Sets the value of the position property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link GeographicalPositionType }{@code >}
     *     
     * @see #getPosition()
     */
    public void setPosition(JAXBElement<GeographicalPositionType> value) {
        this.position = value;
    }

    /**
     * Provides an optional mechanism enabling FIXM aeronautical fields to be supplemented with references to AIXM features.  This field should be considered functionally equivalent to the xlink:href field used in AIXM to reference features. [FIXM]
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHref() {
        return href;
    }

    /**
     * Sets the value of the href property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getHref()
     */
    public void setHref(String value) {
        this.href = value;
    }

}
