//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.base;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Types of Navaid Services. [AIXM 5.1]
 * 
 * &lt;p&gt;Java class for NavaidServiceTypeType&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * &lt;pre&gt;{&#064;code
 * &lt;simpleType name="NavaidServiceTypeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="DF"/&gt;
 *     &lt;enumeration value="DME"/&gt;
 *     &lt;enumeration value="ILS"/&gt;
 *     &lt;enumeration value="ILS_DME"/&gt;
 *     &lt;enumeration value="LOC"/&gt;
 *     &lt;enumeration value="LOC_DME"/&gt;
 *     &lt;enumeration value="MKR"/&gt;
 *     &lt;enumeration value="MLS"/&gt;
 *     &lt;enumeration value="MLS_DME"/&gt;
 *     &lt;enumeration value="NDB"/&gt;
 *     &lt;enumeration value="NDB_DME"/&gt;
 *     &lt;enumeration value="NDB_MKR"/&gt;
 *     &lt;enumeration value="SDF"/&gt;
 *     &lt;enumeration value="TACAN"/&gt;
 *     &lt;enumeration value="TLS"/&gt;
 *     &lt;enumeration value="VOR"/&gt;
 *     &lt;enumeration value="VOR_DME"/&gt;
 *     &lt;enumeration value="VORTAC"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * }&lt;/pre&gt;
 * 
 */
@XmlType(name = "NavaidServiceTypeType")
@XmlEnum
public enum NavaidServiceTypeType {


    /**
     * Direction Finder.
     * 
     */
    DF,

    /**
     * Distance Measuring Equipment.
     * 
     */
    DME,

    /**
     * Instrument Landing System
     * 
     */
    ILS,

    /**
     * ILS with collocated DME. Collocation can be with the antenna or the loc.
     * 
     */
    ILS_DME,

    /**
     * Localizer
     * 
     */
    LOC,

    /**
     * Localizer and DME collocated
     * 
     */
    LOC_DME,

    /**
     * Marker Beacon
     * 
     */
    MKR,

    /**
     * Microwave Landing System
     * 
     */
    MLS,

    /**
     * MLS and DME collocated
     * 
     */
    MLS_DME,

    /**
     * Non-Directional Radio Beacon
     * 
     */
    NDB,

    /**
     * NDB and DME collocated
     * 
     */
    NDB_DME,

    /**
     * Non-Directional Radio Beacon and Marker Beacon
     * 
     */
    NDB_MKR,

    /**
     * Simplified Directional Facility
     * 
     */
    SDF,

    /**
     * Tactical Air Navigation Beacon
     * 
     */
    TACAN,

    /**
     * Transponder Landing System
     * 
     */
    TLS,

    /**
     * VHF Omni directional Radio Range.
     * 
     */
    VOR,

    /**
     * VOR and DME collocated
     * 
     */
    VOR_DME,

    /**
     * VOR and TACAN collocated.
     * 
     */
    VORTAC;

    public String value() {
        return name();
    }

    public static NavaidServiceTypeType fromValue(String v) {
        return valueOf(v);
    }

}
