//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.base;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The Telecom Networks that can be used to address an organisation. [adapted from AIXM]
 * 
 * &lt;p&gt;Java class for NetworkChoiceType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="NetworkChoiceType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="other" type="{http://www.fixm.aero/base/4.3}CharacterStringType"/&gt;
 *         &lt;element name="type" type="{http://www.fixm.aero/base/4.3}TelecomNetworkTypeType"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NetworkChoiceType", propOrder = {
    "other",
    "type"
})
public class NetworkChoiceType
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    /**
     * Used to specify network types not included in the TelecomNetworkType list.
     * 
     */
    protected String other;
    /**
     * Type of telecom network used.
     * 
     */
    @XmlSchemaType(name = "string")
    protected TelecomNetworkTypeType type;

    /**
     * Used to specify network types not included in the TelecomNetworkType list.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOther() {
        return other;
    }

    /**
     * Sets the value of the other property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getOther()
     */
    public void setOther(String value) {
        this.other = value;
    }

    /**
     * Type of telecom network used.
     * 
     * @return
     *     possible object is
     *     {@link TelecomNetworkTypeType }
     *     
     */
    public TelecomNetworkTypeType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link TelecomNetworkTypeType }
     *     
     * @see #getType()
     */
    public void setType(TelecomNetworkTypeType value) {
        this.type = value;
    }

}
