//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.base;

import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the aero.fixm.base package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private static final QName _VerticalRangeTypeLowerBound_QNAME = new QName("http://www.fixm.aero/base/4.3", "lowerBound");
    private static final QName _VerticalRangeTypeUpperBound_QNAME = new QName("http://www.fixm.aero/base/4.3", "upperBound");
    private static final QName _TrueAirspeedRangeTypeLowerSpeed_QNAME = new QName("http://www.fixm.aero/base/4.3", "lowerSpeed");
    private static final QName _TrueAirspeedRangeTypeUpperSpeed_QNAME = new QName("http://www.fixm.aero/base/4.3", "upperSpeed");
    private static final QName _TimeRangeTypeEarliest_QNAME = new QName("http://www.fixm.aero/base/4.3", "earliest");
    private static final QName _TimeRangeTypeLatest_QNAME = new QName("http://www.fixm.aero/base/4.3", "latest");
    private static final QName _PersonOrOrganizationTypeContact_QNAME = new QName("http://www.fixm.aero/base/4.3", "contact");
    private static final QName _PersonOrOrganizationTypeIdentifier_QNAME = new QName("http://www.fixm.aero/base/4.3", "identifier");
    private static final QName _PersonOrOrganizationTypeIdentifierDomain_QNAME = new QName("http://www.fixm.aero/base/4.3", "identifierDomain");
    private static final QName _PersonOrOrganizationTypeName_QNAME = new QName("http://www.fixm.aero/base/4.3", "name");
    private static final QName _AircraftOperatorTypeDesignatorIcao_QNAME = new QName("http://www.fixm.aero/base/4.3", "designatorIcao");
    private static final QName _AircraftOperatorTypeOperatingOrganization_QNAME = new QName("http://www.fixm.aero/base/4.3", "operatingOrganization");
    private static final QName _SidStarReferenceTypeAbbreviatedDesignator_QNAME = new QName("http://www.fixm.aero/base/4.3", "abbreviatedDesignator");
    private static final QName _RelativePointTypePosition_QNAME = new QName("http://www.fixm.aero/base/4.3", "position");
    private static final QName _NavaidTypeNavaidServiceType_QNAME = new QName("http://www.fixm.aero/base/4.3", "navaidServiceType");
    private static final QName _AtcUnitReferenceTypeAtcUnitNameOrAlternate_QNAME = new QName("http://www.fixm.aero/base/4.3", "atcUnitNameOrAlternate");
    private static final QName _AtcUnitReferenceTypeControlSectorDesignator_QNAME = new QName("http://www.fixm.aero/base/4.3", "controlSectorDesignator");
    private static final QName _AtcUnitReferenceTypeLocationIndicator_QNAME = new QName("http://www.fixm.aero/base/4.3", "locationIndicator");
    private static final QName _AerodromeReferenceTypeIataDesignator_QNAME = new QName("http://www.fixm.aero/base/4.3", "iataDesignator");
    private static final QName _AerodromeReferenceTypeReferencePoint_QNAME = new QName("http://www.fixm.aero/base/4.3", "referencePoint");
    private static final QName _AerodromeReferenceTypeReferenceRelativePoint_QNAME = new QName("http://www.fixm.aero/base/4.3", "referenceRelativePoint");
    private static final QName _TelephoneContactTypeFacsimile_QNAME = new QName("http://www.fixm.aero/base/4.3", "facsimile");
    private static final QName _TelephoneContactTypeVoice_QNAME = new QName("http://www.fixm.aero/base/4.3", "voice");
    private static final QName _PostalAddressTypeAdministrativeArea_QNAME = new QName("http://www.fixm.aero/base/4.3", "administrativeArea");
    private static final QName _PostalAddressTypeCity_QNAME = new QName("http://www.fixm.aero/base/4.3", "city");
    private static final QName _PostalAddressTypeCountryCode_QNAME = new QName("http://www.fixm.aero/base/4.3", "countryCode");
    private static final QName _PostalAddressTypeCountryName_QNAME = new QName("http://www.fixm.aero/base/4.3", "countryName");
    private static final QName _PostalAddressTypeDeliveryPoint_QNAME = new QName("http://www.fixm.aero/base/4.3", "deliveryPoint");
    private static final QName _PostalAddressTypePostalCode_QNAME = new QName("http://www.fixm.aero/base/4.3", "postalCode");
    private static final QName _OnlineContactTypeEmail_QNAME = new QName("http://www.fixm.aero/base/4.3", "email");
    private static final QName _OnlineContactTypeLinkage_QNAME = new QName("http://www.fixm.aero/base/4.3", "linkage");
    private static final QName _OnlineContactTypeNetwork_QNAME = new QName("http://www.fixm.aero/base/4.3", "network");
    private static final QName _ContactInformationTypeAddress_QNAME = new QName("http://www.fixm.aero/base/4.3", "address");
    private static final QName _ContactInformationTypePhoneFax_QNAME = new QName("http://www.fixm.aero/base/4.3", "phoneFax");
    private static final QName _ContactInformationTypeTitle_QNAME = new QName("http://www.fixm.aero/base/4.3", "title");
    private static final QName _RestrictionReferenceTypeRestrictionIdentifier_QNAME = new QName("http://www.fixm.aero/base/4.3", "restrictionIdentifier");
    private static final QName _RestrictionReferenceTypeRestrictionType_QNAME = new QName("http://www.fixm.aero/base/4.3", "restrictionType");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: aero.fixm.base
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GloballyUniqueFlightIdentifierType }
     * 
     * @return
     *     the new instance of {@link GloballyUniqueFlightIdentifierType }
     */
    public GloballyUniqueFlightIdentifierType createGloballyUniqueFlightIdentifierType() {
        return new GloballyUniqueFlightIdentifierType();
    }

    /**
     * Create an instance of {@link RestrictionReferenceType }
     * 
     * @return
     *     the new instance of {@link RestrictionReferenceType }
     */
    public RestrictionReferenceType createRestrictionReferenceType() {
        return new RestrictionReferenceType();
    }

    /**
     * Create an instance of {@link UniversallyUniqueIdentifierType }
     * 
     * @return
     *     the new instance of {@link UniversallyUniqueIdentifierType }
     */
    public UniversallyUniqueIdentifierType createUniversallyUniqueIdentifierType() {
        return new UniversallyUniqueIdentifierType();
    }

    /**
     * Create an instance of {@link ContactInformationType }
     * 
     * @return
     *     the new instance of {@link ContactInformationType }
     */
    public ContactInformationType createContactInformationType() {
        return new ContactInformationType();
    }

    /**
     * Create an instance of {@link NetworkChoiceType }
     * 
     * @return
     *     the new instance of {@link NetworkChoiceType }
     */
    public NetworkChoiceType createNetworkChoiceType() {
        return new NetworkChoiceType();
    }

    /**
     * Create an instance of {@link OnlineContactType }
     * 
     * @return
     *     the new instance of {@link OnlineContactType }
     */
    public OnlineContactType createOnlineContactType() {
        return new OnlineContactType();
    }

    /**
     * Create an instance of {@link PostalAddressType }
     * 
     * @return
     *     the new instance of {@link PostalAddressType }
     */
    public PostalAddressType createPostalAddressType() {
        return new PostalAddressType();
    }

    /**
     * Create an instance of {@link TelephoneContactType }
     * 
     * @return
     *     the new instance of {@link TelephoneContactType }
     */
    public TelephoneContactType createTelephoneContactType() {
        return new TelephoneContactType();
    }

    /**
     * Create an instance of {@link AltitudeType }
     * 
     * @return
     *     the new instance of {@link AltitudeType }
     */
    public AltitudeType createAltitudeType() {
        return new AltitudeType();
    }

    /**
     * Create an instance of {@link AltitudeWithSourceType }
     * 
     * @return
     *     the new instance of {@link AltitudeWithSourceType }
     */
    public AltitudeWithSourceType createAltitudeWithSourceType() {
        return new AltitudeWithSourceType();
    }

    /**
     * Create an instance of {@link AngleType }
     * 
     * @return
     *     the new instance of {@link AngleType }
     */
    public AngleType createAngleType() {
        return new AngleType();
    }

    /**
     * Create an instance of {@link BearingType }
     * 
     * @return
     *     the new instance of {@link BearingType }
     */
    public BearingType createBearingType() {
        return new BearingType();
    }

    /**
     * Create an instance of {@link DistanceType }
     * 
     * @return
     *     the new instance of {@link DistanceType }
     */
    public DistanceType createDistanceType() {
        return new DistanceType();
    }

    /**
     * Create an instance of {@link FlightLevelType }
     * 
     * @return
     *     the new instance of {@link FlightLevelType }
     */
    public FlightLevelType createFlightLevelType() {
        return new FlightLevelType();
    }

    /**
     * Create an instance of {@link FrequencyType }
     * 
     * @return
     *     the new instance of {@link FrequencyType }
     */
    public FrequencyType createFrequencyType() {
        return new FrequencyType();
    }

    /**
     * Create an instance of {@link GroundSpeedType }
     * 
     * @return
     *     the new instance of {@link GroundSpeedType }
     */
    public GroundSpeedType createGroundSpeedType() {
        return new GroundSpeedType();
    }

    /**
     * Create an instance of {@link HeightType }
     * 
     * @return
     *     the new instance of {@link HeightType }
     */
    public HeightType createHeightType() {
        return new HeightType();
    }

    /**
     * Create an instance of {@link IndicatedAirspeedType }
     * 
     * @return
     *     the new instance of {@link IndicatedAirspeedType }
     */
    public IndicatedAirspeedType createIndicatedAirspeedType() {
        return new IndicatedAirspeedType();
    }

    /**
     * Create an instance of {@link LengthType }
     * 
     * @return
     *     the new instance of {@link LengthType }
     */
    public LengthType createLengthType() {
        return new LengthType();
    }

    /**
     * Create an instance of {@link MassType }
     * 
     * @return
     *     the new instance of {@link MassType }
     */
    public MassType createMassType() {
        return new MassType();
    }

    /**
     * Create an instance of {@link PressureType }
     * 
     * @return
     *     the new instance of {@link PressureType }
     */
    public PressureType createPressureType() {
        return new PressureType();
    }

    /**
     * Create an instance of {@link TemperatureType }
     * 
     * @return
     *     the new instance of {@link TemperatureType }
     */
    public TemperatureType createTemperatureType() {
        return new TemperatureType();
    }

    /**
     * Create an instance of {@link TrueAirspeedType }
     * 
     * @return
     *     the new instance of {@link TrueAirspeedType }
     */
    public TrueAirspeedType createTrueAirspeedType() {
        return new TrueAirspeedType();
    }

    /**
     * Create an instance of {@link VerticalRateType }
     * 
     * @return
     *     the new instance of {@link VerticalRateType }
     */
    public VerticalRateType createVerticalRateType() {
        return new VerticalRateType();
    }

    /**
     * Create an instance of {@link VolumeType }
     * 
     * @return
     *     the new instance of {@link VolumeType }
     */
    public VolumeType createVolumeType() {
        return new VolumeType();
    }

    /**
     * Create an instance of {@link WeightType }
     * 
     * @return
     *     the new instance of {@link WeightType }
     */
    public WeightType createWeightType() {
        return new WeightType();
    }

    /**
     * Create an instance of {@link WindDirectionType }
     * 
     * @return
     *     the new instance of {@link WindDirectionType }
     */
    public WindDirectionType createWindDirectionType() {
        return new WindDirectionType();
    }

    /**
     * Create an instance of {@link WindSpeedType }
     * 
     * @return
     *     the new instance of {@link WindSpeedType }
     */
    public WindSpeedType createWindSpeedType() {
        return new WindSpeedType();
    }

    /**
     * Create an instance of {@link AerodromeReferenceType }
     * 
     * @return
     *     the new instance of {@link AerodromeReferenceType }
     */
    public AerodromeReferenceType createAerodromeReferenceType() {
        return new AerodromeReferenceType();
    }

    /**
     * Create an instance of {@link AirspaceDesignatorType }
     * 
     * @return
     *     the new instance of {@link AirspaceDesignatorType }
     */
    public AirspaceDesignatorType createAirspaceDesignatorType() {
        return new AirspaceDesignatorType();
    }

    /**
     * Create an instance of {@link AtcUnitReferenceType }
     * 
     * @return
     *     the new instance of {@link AtcUnitReferenceType }
     */
    public AtcUnitReferenceType createAtcUnitReferenceType() {
        return new AtcUnitReferenceType();
    }

    /**
     * Create an instance of {@link DesignatedPointType }
     * 
     * @return
     *     the new instance of {@link DesignatedPointType }
     */
    public DesignatedPointType createDesignatedPointType() {
        return new DesignatedPointType();
    }

    /**
     * Create an instance of {@link GeographicalPositionType }
     * 
     * @return
     *     the new instance of {@link GeographicalPositionType }
     */
    public GeographicalPositionType createGeographicalPositionType() {
        return new GeographicalPositionType();
    }

    /**
     * Create an instance of {@link NavaidType }
     * 
     * @return
     *     the new instance of {@link NavaidType }
     */
    public NavaidType createNavaidType() {
        return new NavaidType();
    }

    /**
     * Create an instance of {@link RelativePointType }
     * 
     * @return
     *     the new instance of {@link RelativePointType }
     */
    public RelativePointType createRelativePointType() {
        return new RelativePointType();
    }

    /**
     * Create an instance of {@link RouteDesignatorType }
     * 
     * @return
     *     the new instance of {@link RouteDesignatorType }
     */
    public RouteDesignatorType createRouteDesignatorType() {
        return new RouteDesignatorType();
    }

    /**
     * Create an instance of {@link RunwayDirectionDesignatorType }
     * 
     * @return
     *     the new instance of {@link RunwayDirectionDesignatorType }
     */
    public RunwayDirectionDesignatorType createRunwayDirectionDesignatorType() {
        return new RunwayDirectionDesignatorType();
    }

    /**
     * Create an instance of {@link SidStarReferenceType }
     * 
     * @return
     *     the new instance of {@link SidStarReferenceType }
     */
    public SidStarReferenceType createSidStarReferenceType() {
        return new SidStarReferenceType();
    }

    /**
     * Create an instance of {@link SignificantPointChoiceType }
     * 
     * @return
     *     the new instance of {@link SignificantPointChoiceType }
     */
    public SignificantPointChoiceType createSignificantPointChoiceType() {
        return new SignificantPointChoiceType();
    }

    /**
     * Create an instance of {@link AircraftOperatorType }
     * 
     * @return
     *     the new instance of {@link AircraftOperatorType }
     */
    public AircraftOperatorType createAircraftOperatorType() {
        return new AircraftOperatorType();
    }

    /**
     * Create an instance of {@link PersonOrOrganizationType }
     * 
     * @return
     *     the new instance of {@link PersonOrOrganizationType }
     */
    public PersonOrOrganizationType createPersonOrOrganizationType() {
        return new PersonOrOrganizationType();
    }

    /**
     * Create an instance of {@link FlightLevelOrAltitudeChoiceType }
     * 
     * @return
     *     the new instance of {@link FlightLevelOrAltitudeChoiceType }
     */
    public FlightLevelOrAltitudeChoiceType createFlightLevelOrAltitudeChoiceType() {
        return new FlightLevelOrAltitudeChoiceType();
    }

    /**
     * Create an instance of {@link FlightLevelOrAltitudeOrRangeChoiceType }
     * 
     * @return
     *     the new instance of {@link FlightLevelOrAltitudeOrRangeChoiceType }
     */
    public FlightLevelOrAltitudeOrRangeChoiceType createFlightLevelOrAltitudeOrRangeChoiceType() {
        return new FlightLevelOrAltitudeOrRangeChoiceType();
    }

    /**
     * Create an instance of {@link FlightLevelOrAltitudeOrVfrChoiceType }
     * 
     * @return
     *     the new instance of {@link FlightLevelOrAltitudeOrVfrChoiceType }
     */
    public FlightLevelOrAltitudeOrVfrChoiceType createFlightLevelOrAltitudeOrVfrChoiceType() {
        return new FlightLevelOrAltitudeOrVfrChoiceType();
    }

    /**
     * Create an instance of {@link TimeChoiceType }
     * 
     * @return
     *     the new instance of {@link TimeChoiceType }
     */
    public TimeChoiceType createTimeChoiceType() {
        return new TimeChoiceType();
    }

    /**
     * Create an instance of {@link TimeRangeType }
     * 
     * @return
     *     the new instance of {@link TimeRangeType }
     */
    public TimeRangeType createTimeRangeType() {
        return new TimeRangeType();
    }

    /**
     * Create an instance of {@link TrueAirspeedChoiceType }
     * 
     * @return
     *     the new instance of {@link TrueAirspeedChoiceType }
     */
    public TrueAirspeedChoiceType createTrueAirspeedChoiceType() {
        return new TrueAirspeedChoiceType();
    }

    /**
     * Create an instance of {@link TrueAirspeedRangeType }
     * 
     * @return
     *     the new instance of {@link TrueAirspeedRangeType }
     */
    public TrueAirspeedRangeType createTrueAirspeedRangeType() {
        return new TrueAirspeedRangeType();
    }

    /**
     * Create an instance of {@link VerticalRangeType }
     * 
     * @return
     *     the new instance of {@link VerticalRangeType }
     */
    public VerticalRangeType createVerticalRangeType() {
        return new VerticalRangeType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FlightLevelOrAltitudeChoiceType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FlightLevelOrAltitudeChoiceType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.3", name = "lowerBound", scope = VerticalRangeType.class)
    public JAXBElement<FlightLevelOrAltitudeChoiceType> createVerticalRangeTypeLowerBound(FlightLevelOrAltitudeChoiceType value) {
        return new JAXBElement<>(_VerticalRangeTypeLowerBound_QNAME, FlightLevelOrAltitudeChoiceType.class, VerticalRangeType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FlightLevelOrAltitudeChoiceType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FlightLevelOrAltitudeChoiceType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.3", name = "upperBound", scope = VerticalRangeType.class)
    public JAXBElement<FlightLevelOrAltitudeChoiceType> createVerticalRangeTypeUpperBound(FlightLevelOrAltitudeChoiceType value) {
        return new JAXBElement<>(_VerticalRangeTypeUpperBound_QNAME, FlightLevelOrAltitudeChoiceType.class, VerticalRangeType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TrueAirspeedType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TrueAirspeedType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.3", name = "lowerSpeed", scope = TrueAirspeedRangeType.class)
    public JAXBElement<TrueAirspeedType> createTrueAirspeedRangeTypeLowerSpeed(TrueAirspeedType value) {
        return new JAXBElement<>(_TrueAirspeedRangeTypeLowerSpeed_QNAME, TrueAirspeedType.class, TrueAirspeedRangeType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TrueAirspeedType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TrueAirspeedType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.3", name = "upperSpeed", scope = TrueAirspeedRangeType.class)
    public JAXBElement<TrueAirspeedType> createTrueAirspeedRangeTypeUpperSpeed(TrueAirspeedType value) {
        return new JAXBElement<>(_TrueAirspeedRangeTypeUpperSpeed_QNAME, TrueAirspeedType.class, TrueAirspeedRangeType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.3", name = "earliest", scope = TimeRangeType.class)
    public JAXBElement<XMLGregorianCalendar> createTimeRangeTypeEarliest(XMLGregorianCalendar value) {
        return new JAXBElement<>(_TimeRangeTypeEarliest_QNAME, XMLGregorianCalendar.class, TimeRangeType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.3", name = "latest", scope = TimeRangeType.class)
    public JAXBElement<XMLGregorianCalendar> createTimeRangeTypeLatest(XMLGregorianCalendar value) {
        return new JAXBElement<>(_TimeRangeTypeLatest_QNAME, XMLGregorianCalendar.class, TimeRangeType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContactInformationType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ContactInformationType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.3", name = "contact", scope = PersonOrOrganizationType.class)
    public JAXBElement<ContactInformationType> createPersonOrOrganizationTypeContact(ContactInformationType value) {
        return new JAXBElement<>(_PersonOrOrganizationTypeContact_QNAME, ContactInformationType.class, PersonOrOrganizationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.3", name = "identifier", scope = PersonOrOrganizationType.class)
    public JAXBElement<String> createPersonOrOrganizationTypeIdentifier(String value) {
        return new JAXBElement<>(_PersonOrOrganizationTypeIdentifier_QNAME, String.class, PersonOrOrganizationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.3", name = "identifierDomain", scope = PersonOrOrganizationType.class)
    public JAXBElement<String> createPersonOrOrganizationTypeIdentifierDomain(String value) {
        return new JAXBElement<>(_PersonOrOrganizationTypeIdentifierDomain_QNAME, String.class, PersonOrOrganizationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.3", name = "name", scope = PersonOrOrganizationType.class)
    public JAXBElement<String> createPersonOrOrganizationTypeName(String value) {
        return new JAXBElement<>(_PersonOrOrganizationTypeName_QNAME, String.class, PersonOrOrganizationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.3", name = "designatorIcao", scope = AircraftOperatorType.class)
    public JAXBElement<String> createAircraftOperatorTypeDesignatorIcao(String value) {
        return new JAXBElement<>(_AircraftOperatorTypeDesignatorIcao_QNAME, String.class, AircraftOperatorType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonOrOrganizationType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PersonOrOrganizationType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.3", name = "operatingOrganization", scope = AircraftOperatorType.class)
    public JAXBElement<PersonOrOrganizationType> createAircraftOperatorTypeOperatingOrganization(PersonOrOrganizationType value) {
        return new JAXBElement<>(_AircraftOperatorTypeOperatingOrganization_QNAME, PersonOrOrganizationType.class, AircraftOperatorType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.3", name = "abbreviatedDesignator", scope = SidStarReferenceType.class)
    public JAXBElement<String> createSidStarReferenceTypeAbbreviatedDesignator(String value) {
        return new JAXBElement<>(_SidStarReferenceTypeAbbreviatedDesignator_QNAME, String.class, SidStarReferenceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GeographicalPositionType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GeographicalPositionType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.3", name = "position", scope = RelativePointType.class)
    public JAXBElement<GeographicalPositionType> createRelativePointTypePosition(GeographicalPositionType value) {
        return new JAXBElement<>(_RelativePointTypePosition_QNAME, GeographicalPositionType.class, RelativePointType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NavaidServiceTypeType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link NavaidServiceTypeType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.3", name = "navaidServiceType", scope = NavaidType.class)
    public JAXBElement<NavaidServiceTypeType> createNavaidTypeNavaidServiceType(NavaidServiceTypeType value) {
        return new JAXBElement<>(_NavaidTypeNavaidServiceType_QNAME, NavaidServiceTypeType.class, NavaidType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GeographicalPositionType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GeographicalPositionType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.3", name = "position", scope = NavaidType.class)
    public JAXBElement<GeographicalPositionType> createNavaidTypePosition(GeographicalPositionType value) {
        return new JAXBElement<>(_RelativePointTypePosition_QNAME, GeographicalPositionType.class, NavaidType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GeographicalPositionType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GeographicalPositionType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.3", name = "position", scope = DesignatedPointType.class)
    public JAXBElement<GeographicalPositionType> createDesignatedPointTypePosition(GeographicalPositionType value) {
        return new JAXBElement<>(_RelativePointTypePosition_QNAME, GeographicalPositionType.class, DesignatedPointType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.3", name = "atcUnitNameOrAlternate", scope = AtcUnitReferenceType.class)
    public JAXBElement<String> createAtcUnitReferenceTypeAtcUnitNameOrAlternate(String value) {
        return new JAXBElement<>(_AtcUnitReferenceTypeAtcUnitNameOrAlternate_QNAME, String.class, AtcUnitReferenceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AirspaceDesignatorType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AirspaceDesignatorType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.3", name = "controlSectorDesignator", scope = AtcUnitReferenceType.class)
    public JAXBElement<AirspaceDesignatorType> createAtcUnitReferenceTypeControlSectorDesignator(AirspaceDesignatorType value) {
        return new JAXBElement<>(_AtcUnitReferenceTypeControlSectorDesignator_QNAME, AirspaceDesignatorType.class, AtcUnitReferenceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.3", name = "locationIndicator", scope = AtcUnitReferenceType.class)
    public JAXBElement<String> createAtcUnitReferenceTypeLocationIndicator(String value) {
        return new JAXBElement<>(_AtcUnitReferenceTypeLocationIndicator_QNAME, String.class, AtcUnitReferenceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GeographicalPositionType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GeographicalPositionType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.3", name = "position", scope = AtcUnitReferenceType.class)
    public JAXBElement<GeographicalPositionType> createAtcUnitReferenceTypePosition(GeographicalPositionType value) {
        return new JAXBElement<>(_RelativePointTypePosition_QNAME, GeographicalPositionType.class, AtcUnitReferenceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.3", name = "iataDesignator", scope = AerodromeReferenceType.class)
    public JAXBElement<String> createAerodromeReferenceTypeIataDesignator(String value) {
        return new JAXBElement<>(_AerodromeReferenceTypeIataDesignator_QNAME, String.class, AerodromeReferenceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.3", name = "locationIndicator", scope = AerodromeReferenceType.class)
    public JAXBElement<String> createAerodromeReferenceTypeLocationIndicator(String value) {
        return new JAXBElement<>(_AtcUnitReferenceTypeLocationIndicator_QNAME, String.class, AerodromeReferenceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.3", name = "name", scope = AerodromeReferenceType.class)
    public JAXBElement<String> createAerodromeReferenceTypeName(String value) {
        return new JAXBElement<>(_PersonOrOrganizationTypeName_QNAME, String.class, AerodromeReferenceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GeographicalPositionType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GeographicalPositionType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.3", name = "referencePoint", scope = AerodromeReferenceType.class)
    public JAXBElement<GeographicalPositionType> createAerodromeReferenceTypeReferencePoint(GeographicalPositionType value) {
        return new JAXBElement<>(_AerodromeReferenceTypeReferencePoint_QNAME, GeographicalPositionType.class, AerodromeReferenceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RelativePointType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RelativePointType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.3", name = "referenceRelativePoint", scope = AerodromeReferenceType.class)
    public JAXBElement<RelativePointType> createAerodromeReferenceTypeReferenceRelativePoint(RelativePointType value) {
        return new JAXBElement<>(_AerodromeReferenceTypeReferenceRelativePoint_QNAME, RelativePointType.class, AerodromeReferenceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.3", name = "facsimile", scope = TelephoneContactType.class)
    public JAXBElement<String> createTelephoneContactTypeFacsimile(String value) {
        return new JAXBElement<>(_TelephoneContactTypeFacsimile_QNAME, String.class, TelephoneContactType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.3", name = "voice", scope = TelephoneContactType.class)
    public JAXBElement<String> createTelephoneContactTypeVoice(String value) {
        return new JAXBElement<>(_TelephoneContactTypeVoice_QNAME, String.class, TelephoneContactType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.3", name = "administrativeArea", scope = PostalAddressType.class)
    public JAXBElement<String> createPostalAddressTypeAdministrativeArea(String value) {
        return new JAXBElement<>(_PostalAddressTypeAdministrativeArea_QNAME, String.class, PostalAddressType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.3", name = "city", scope = PostalAddressType.class)
    public JAXBElement<String> createPostalAddressTypeCity(String value) {
        return new JAXBElement<>(_PostalAddressTypeCity_QNAME, String.class, PostalAddressType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.3", name = "countryCode", scope = PostalAddressType.class)
    public JAXBElement<String> createPostalAddressTypeCountryCode(String value) {
        return new JAXBElement<>(_PostalAddressTypeCountryCode_QNAME, String.class, PostalAddressType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.3", name = "countryName", scope = PostalAddressType.class)
    public JAXBElement<String> createPostalAddressTypeCountryName(String value) {
        return new JAXBElement<>(_PostalAddressTypeCountryName_QNAME, String.class, PostalAddressType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.3", name = "deliveryPoint", scope = PostalAddressType.class)
    public JAXBElement<String> createPostalAddressTypeDeliveryPoint(String value) {
        return new JAXBElement<>(_PostalAddressTypeDeliveryPoint_QNAME, String.class, PostalAddressType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.3", name = "postalCode", scope = PostalAddressType.class)
    public JAXBElement<String> createPostalAddressTypePostalCode(String value) {
        return new JAXBElement<>(_PostalAddressTypePostalCode_QNAME, String.class, PostalAddressType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.3", name = "email", scope = OnlineContactType.class)
    public JAXBElement<String> createOnlineContactTypeEmail(String value) {
        return new JAXBElement<>(_OnlineContactTypeEmail_QNAME, String.class, OnlineContactType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.3", name = "linkage", scope = OnlineContactType.class)
    public JAXBElement<String> createOnlineContactTypeLinkage(String value) {
        return new JAXBElement<>(_OnlineContactTypeLinkage_QNAME, String.class, OnlineContactType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NetworkChoiceType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link NetworkChoiceType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.3", name = "network", scope = OnlineContactType.class)
    public JAXBElement<NetworkChoiceType> createOnlineContactTypeNetwork(NetworkChoiceType value) {
        return new JAXBElement<>(_OnlineContactTypeNetwork_QNAME, NetworkChoiceType.class, OnlineContactType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PostalAddressType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PostalAddressType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.3", name = "address", scope = ContactInformationType.class)
    public JAXBElement<PostalAddressType> createContactInformationTypeAddress(PostalAddressType value) {
        return new JAXBElement<>(_ContactInformationTypeAddress_QNAME, PostalAddressType.class, ContactInformationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.3", name = "name", scope = ContactInformationType.class)
    public JAXBElement<String> createContactInformationTypeName(String value) {
        return new JAXBElement<>(_PersonOrOrganizationTypeName_QNAME, String.class, ContactInformationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TelephoneContactType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TelephoneContactType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.3", name = "phoneFax", scope = ContactInformationType.class)
    public JAXBElement<TelephoneContactType> createContactInformationTypePhoneFax(TelephoneContactType value) {
        return new JAXBElement<>(_ContactInformationTypePhoneFax_QNAME, TelephoneContactType.class, ContactInformationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.3", name = "title", scope = ContactInformationType.class)
    public JAXBElement<String> createContactInformationTypeTitle(String value) {
        return new JAXBElement<>(_ContactInformationTypeTitle_QNAME, String.class, ContactInformationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.3", name = "restrictionIdentifier", scope = RestrictionReferenceType.class)
    public JAXBElement<String> createRestrictionReferenceTypeRestrictionIdentifier(String value) {
        return new JAXBElement<>(_RestrictionReferenceTypeRestrictionIdentifier_QNAME, String.class, RestrictionReferenceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.fixm.aero/base/4.3", name = "restrictionType", scope = RestrictionReferenceType.class)
    public JAXBElement<String> createRestrictionReferenceTypeRestrictionType(String value) {
        return new JAXBElement<>(_RestrictionReferenceTypeRestrictionType_QNAME, String.class, RestrictionReferenceType.class, value);
    }

}
