//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.base;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A reference to a SID or a STAR. [FIXM]
 * 
 * &lt;p&gt;Java class for SidStarReferenceType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="SidStarReferenceType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="abbreviatedDesignator" type="{http://www.fixm.aero/base/4.3}SidStarAbbreviatedDesignatorType" minOccurs="0"/&gt;
 *         &lt;element name="designator" type="{http://www.fixm.aero/base/4.3}SidStarDesignatorType"/&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/base/4.3}SidStarReferenceExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="href" type="{http://www.fixm.aero/base/4.3}HypertextReferenceType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SidStarReferenceType", propOrder = {
    "abbreviatedDesignator",
    "designator",
    "extension"
})
public class SidStarReferenceType
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    /**
     * A shortened designator of the SID or STAR. [FIXM] This abbreviated designator is based on ARINC 424 chapter 7.4 rules.
     * 
     */
    @XmlElementRef(name = "abbreviatedDesignator", namespace = "http://www.fixm.aero/base/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<String> abbreviatedDesignator;
    /**
     * The textual designator of a SID or STAR. [Specialised from AIXM 5.1]
     * 
     */
    @XmlElement(required = true)
    protected String designator;
    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     */
    @XmlElement(nillable = true)
    protected List<SidStarReferenceExtensionType> extension;
    /**
     * Provides an optional mechanism enabling FIXM aeronautical fields to be supplemented with references to AIXM features.  This field should be considered functionally equivalent to the xlink:href field used in AIXM to reference features. [FIXM]
     * 
     */
    @XmlAttribute(name = "href")
    protected String href;

    /**
     * A shortened designator of the SID or STAR. [FIXM] This abbreviated designator is based on ARINC 424 chapter 7.4 rules.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getAbbreviatedDesignator() {
        return abbreviatedDesignator;
    }

    /**
     * Sets the value of the abbreviatedDesignator property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     * @see #getAbbreviatedDesignator()
     */
    public void setAbbreviatedDesignator(JAXBElement<String> value) {
        this.abbreviatedDesignator = value;
    }

    /**
     * The textual designator of a SID or STAR. [Specialised from AIXM 5.1]
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesignator() {
        return designator;
    }

    /**
     * Sets the value of the designator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getDesignator()
     */
    public void setDesignator(String value) {
        this.designator = value;
    }

    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SidStarReferenceExtensionType }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<SidStarReferenceExtensionType> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * Provides an optional mechanism enabling FIXM aeronautical fields to be supplemented with references to AIXM features.  This field should be considered functionally equivalent to the xlink:href field used in AIXM to reference features. [FIXM]
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHref() {
        return href;
    }

    /**
     * Sets the value of the href property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getHref()
     */
    public void setHref(String value) {
        this.href = value;
    }

}
