//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.base;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A location type restricted to lat/long location, named location, or reference location.
 * 
 * &lt;p&gt;Java class for SignificantPointChoiceType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="SignificantPointChoiceType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="aerodromeReferencePoint" type="{http://www.fixm.aero/base/4.3}AerodromeReferenceType"/&gt;
 *         &lt;element name="designatedPoint" type="{http://www.fixm.aero/base/4.3}DesignatedPointType"/&gt;
 *         &lt;element name="navaid" type="{http://www.fixm.aero/base/4.3}NavaidType"/&gt;
 *         &lt;element name="position" type="{http://www.fixm.aero/base/4.3}GeographicalPositionType"/&gt;
 *         &lt;element name="relativePoint" type="{http://www.fixm.aero/base/4.3}RelativePointType"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SignificantPointChoiceType", propOrder = {
    "aerodromeReferencePoint",
    "designatedPoint",
    "navaid",
    "position",
    "relativePoint"
})
public class SignificantPointChoiceType
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    /**
     * The designated geographical location of an aerodrome. [ICAO Annex 14].
     * 
     */
    protected AerodromeReferenceType aerodromeReferencePoint;
    /**
     * A named geographical location used in defining an ATS route, the flight path of an aircraft or for other navigation or ATS purposes. [FIXM]
     * 
     */
    protected DesignatedPointType designatedPoint;
    /**
     * A radio navigation aid used in defining an ATS route, the flight path of an aircraft or for other navigation or ATS purposes. [FIXM]
     * 
     */
    protected NavaidType navaid;
    /**
     * The values of latitude and longitude that define the position of a point on the surface of the Earth with respect to a reference datum. [specialised from ICAO Doc 9881]
     * 
     */
    protected GeographicalPositionType position;
    /**
     * Bearing and distance from a reference point. [ICAO Doc 4444, Appendix 2, ITEM 15]
     * 
     */
    protected RelativePointType relativePoint;

    /**
     * The designated geographical location of an aerodrome. [ICAO Annex 14].
     * 
     * @return
     *     possible object is
     *     {@link AerodromeReferenceType }
     *     
     */
    public AerodromeReferenceType getAerodromeReferencePoint() {
        return aerodromeReferencePoint;
    }

    /**
     * Sets the value of the aerodromeReferencePoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link AerodromeReferenceType }
     *     
     * @see #getAerodromeReferencePoint()
     */
    public void setAerodromeReferencePoint(AerodromeReferenceType value) {
        this.aerodromeReferencePoint = value;
    }

    /**
     * A named geographical location used in defining an ATS route, the flight path of an aircraft or for other navigation or ATS purposes. [FIXM]
     * 
     * @return
     *     possible object is
     *     {@link DesignatedPointType }
     *     
     */
    public DesignatedPointType getDesignatedPoint() {
        return designatedPoint;
    }

    /**
     * Sets the value of the designatedPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link DesignatedPointType }
     *     
     * @see #getDesignatedPoint()
     */
    public void setDesignatedPoint(DesignatedPointType value) {
        this.designatedPoint = value;
    }

    /**
     * A radio navigation aid used in defining an ATS route, the flight path of an aircraft or for other navigation or ATS purposes. [FIXM]
     * 
     * @return
     *     possible object is
     *     {@link NavaidType }
     *     
     */
    public NavaidType getNavaid() {
        return navaid;
    }

    /**
     * Sets the value of the navaid property.
     * 
     * @param value
     *     allowed object is
     *     {@link NavaidType }
     *     
     * @see #getNavaid()
     */
    public void setNavaid(NavaidType value) {
        this.navaid = value;
    }

    /**
     * The values of latitude and longitude that define the position of a point on the surface of the Earth with respect to a reference datum. [specialised from ICAO Doc 9881]
     * 
     * @return
     *     possible object is
     *     {@link GeographicalPositionType }
     *     
     */
    public GeographicalPositionType getPosition() {
        return position;
    }

    /**
     * Sets the value of the position property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeographicalPositionType }
     *     
     * @see #getPosition()
     */
    public void setPosition(GeographicalPositionType value) {
        this.position = value;
    }

    /**
     * Bearing and distance from a reference point. [ICAO Doc 4444, Appendix 2, ITEM 15]
     * 
     * @return
     *     possible object is
     *     {@link RelativePointType }
     *     
     */
    public RelativePointType getRelativePoint() {
        return relativePoint;
    }

    /**
     * Sets the value of the relativePoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelativePointType }
     *     
     * @see #getRelativePoint()
     */
    public void setRelativePoint(RelativePointType value) {
        this.relativePoint = value;
    }

}
