//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.base;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The Telecom Networks that can be used to address an organisation. [adapted from AIXM]
 * 
 * &lt;p&gt;Java class for TelecomNetworkTypeType&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * &lt;pre&gt;{&#064;code
 * &lt;simpleType name="TelecomNetworkTypeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="AFTN"/&gt;
 *     &lt;enumeration value="INTERNET"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * }&lt;/pre&gt;
 * 
 */
@XmlType(name = "TelecomNetworkTypeType")
@XmlEnum
public enum TelecomNetworkTypeType {


    /**
     * The data interchange in the AFS is performed by the Aeronautical Fixed Telecommunications Network, AFTN. This is a message handling network running according to ICAO Standards documented in Annex 10 to the ICAO Convention.[AIXM]
     * 
     */
    AFTN,

    /**
     * The Internet is a worldwide, publicly accessible series of interconnected computer networks that transmit data by packet switching using the standard Internet Protocol (IP). 
     * The usage of this value indicates that a URL will be provided for the linkage property in OnlineContact.
     * 
     */
    INTERNET;

    public String value() {
        return name();
    }

    public static TelecomNetworkTypeType fromValue(String v) {
        return valueOf(v);
    }

}
