//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.base;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Represents a time range with a lower and/or upper bound.
 * 
 * &lt;p&gt;Java class for TimeRangeType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="TimeRangeType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="earliest" type="{http://www.fixm.aero/base/4.3}DateTimeUtcType" minOccurs="0"/&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/base/4.3}TimeRangeExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="latest" type="{http://www.fixm.aero/base/4.3}DateTimeUtcType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TimeRangeType", propOrder = {
    "earliest",
    "extension",
    "latest"
})
public class TimeRangeType
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    /**
     * Lower bound of the time range.
     * 
     */
    @XmlElementRef(name = "earliest", namespace = "http://www.fixm.aero/base/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<XMLGregorianCalendar> earliest;
    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     */
    @XmlElement(nillable = true)
    protected List<TimeRangeExtensionType> extension;
    /**
     * Upper bound of the time range.
     * 
     */
    @XmlElementRef(name = "latest", namespace = "http://www.fixm.aero/base/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<XMLGregorianCalendar> latest;

    /**
     * Lower bound of the time range.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getEarliest() {
        return earliest;
    }

    /**
     * Sets the value of the earliest property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     * @see #getEarliest()
     */
    public void setEarliest(JAXBElement<XMLGregorianCalendar> value) {
        this.earliest = value;
    }

    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TimeRangeExtensionType }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<TimeRangeExtensionType> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * Upper bound of the time range.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getLatest() {
        return latest;
    }

    /**
     * Sets the value of the latest property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     * @see #getLatest()
     */
    public void setLatest(JAXBElement<XMLGregorianCalendar> value) {
        this.latest = value;
    }

}
