//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.base;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Represent either a specific true airspeed or a true airspeed range with a lower and/or upper bound.
 * 
 * &lt;p&gt;Java class for TrueAirspeedChoiceType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="TrueAirspeedChoiceType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="range" type="{http://www.fixm.aero/base/4.3}TrueAirspeedRangeType"/&gt;
 *         &lt;element name="value" type="{http://www.fixm.aero/base/4.3}TrueAirspeedType"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TrueAirspeedChoiceType", propOrder = {
    "range",
    "value"
})
public class TrueAirspeedChoiceType
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    /**
     * Represents a true airspeed range with a lower and/or upper bound.
     * 
     */
    protected TrueAirspeedRangeType range;
    /**
     * A specific true airspeed value.
     * 
     */
    protected TrueAirspeedType value;

    /**
     * Represents a true airspeed range with a lower and/or upper bound.
     * 
     * @return
     *     possible object is
     *     {@link TrueAirspeedRangeType }
     *     
     */
    public TrueAirspeedRangeType getRange() {
        return range;
    }

    /**
     * Sets the value of the range property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrueAirspeedRangeType }
     *     
     * @see #getRange()
     */
    public void setRange(TrueAirspeedRangeType value) {
        this.range = value;
    }

    /**
     * A specific true airspeed value.
     * 
     * @return
     *     possible object is
     *     {@link TrueAirspeedType }
     *     
     */
    public TrueAirspeedType getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrueAirspeedType }
     *     
     * @see #getValue()
     */
    public void setValue(TrueAirspeedType value) {
        this.value = value;
    }

}
