//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.base;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;


/**
 * A 128-bit number used, with a high probability, to uniquely identify information in computer systems. [FIXM]
 * 
 * &lt;p&gt;Java class for UniversallyUniqueIdentifierType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="UniversallyUniqueIdentifierType"&gt;
 *   &lt;simpleContent&gt;
 *     &lt;extension base="&lt;http://www.fixm.aero/base/4.3&gt;RestrictedUniversallyUniqueIdentifierType"&gt;
 *       &lt;attribute name="codeSpace" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="urn:uuid" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UniversallyUniqueIdentifierType", propOrder = {
    "value"
})
@XmlSeeAlso({
    GloballyUniqueFlightIdentifierType.class
})
public class UniversallyUniqueIdentifierType
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    /**
     * Helper type for restrictions on UniversallyUniqueIdentifier
     * 
     */
    @XmlValue
    protected String value;
    /**
     * Code Space of the UUID
     * 
     */
    @XmlAttribute(name = "codeSpace", required = true)
    protected String codeSpace;

    /**
     * Helper type for restrictions on UniversallyUniqueIdentifier
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getValue()
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Code Space of the UUID
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodeSpace() {
        if (codeSpace == null) {
            return "urn:uuid";
        } else {
            return codeSpace;
        }
    }

    /**
     * Sets the value of the codeSpace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getCodeSpace()
     */
    public void setCodeSpace(String value) {
        this.codeSpace = value;
    }

}
