//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.base;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The reference quantities used to express the value of flight level.
 * 
 * &lt;p&gt;Java class for UomFlightLevelType&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * &lt;pre&gt;{&#064;code
 * &lt;simpleType name="UomFlightLevelType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="FL"/&gt;
 *     &lt;enumeration value="SM"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * }&lt;/pre&gt;
 * 
 */
@XmlType(name = "UomFlightLevelType")
@XmlEnum
public enum UomFlightLevelType {


    /**
     * Flight level in hundreds of feet.
     * 
     */
    FL,

    /**
     * Flight level in tens of metres.
     * 
     */
    SM;

    public String value() {
        return name();
    }

    public static UomFlightLevelType fromValue(String v) {
        return valueOf(v);
    }

}
