//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.base;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Radio frequency unit of measure. Either kHz OR MHz.
 * 
 * &lt;p&gt;Java class for UomFrequencyType&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * &lt;pre&gt;{&#064;code
 * &lt;simpleType name="UomFrequencyType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="KHZ"/&gt;
 *     &lt;enumeration value="MHZ"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * }&lt;/pre&gt;
 * 
 */
@XmlType(name = "UomFrequencyType")
@XmlEnum
public enum UomFrequencyType {


    /**
     * Indicates this radio frequency is measured in kHz.
     * 
     */
    KHZ,

    /**
     * Indicates this radio frequency is measured in MHz.
     * 
     */
    MHZ;

    public String value() {
        return name();
    }

    public static UomFrequencyType fromValue(String v) {
        return valueOf(v);
    }

}
