//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.base;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The reference quantities used to express the value of the length, or distance between two entities. [ISO 19103, chapter 6.5.7.8]
 * 
 * &lt;p&gt;Java class for UomLengthType&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * &lt;pre&gt;{&#064;code
 * &lt;simpleType name="UomLengthType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="CM"/&gt;
 *     &lt;enumeration value="FT"/&gt;
 *     &lt;enumeration value="IN"/&gt;
 *     &lt;enumeration value="KM"/&gt;
 *     &lt;enumeration value="M"/&gt;
 *     &lt;enumeration value="MI"/&gt;
 *     &lt;enumeration value="MM"/&gt;
 *     &lt;enumeration value="NM"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * }&lt;/pre&gt;
 * 
 */
@XmlType(name = "UomLengthType")
@XmlEnum
public enum UomLengthType {


    /**
     * Centimetre
     * 
     */
    CM,

    /**
     * Foot
     * 
     */
    FT,

    /**
     * Inch
     * 
     */
    IN,

    /**
     * Kilometre
     * 
     */
    KM,

    /**
     * Metre
     * 
     */
    M,

    /**
     * Statute mile
     * 
     */
    MI,

    /**
     * Millimeter
     * 
     */
    MM,

    /**
     * Nautical mile
     * 
     */
    NM;

    public String value() {
        return name();
    }

    public static UomLengthType fromValue(String v) {
        return valueOf(v);
    }

}
