//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.base;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The reference quantities used to express the value of temperature.
 * 
 * &lt;p&gt;Java class for UomTemperatureType&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * &lt;pre&gt;{&#064;code
 * &lt;simpleType name="UomTemperatureType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="C"/&gt;
 *     &lt;enumeration value="F"/&gt;
 *     &lt;enumeration value="K"/&gt;
 *     &lt;enumeration value="R"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * }&lt;/pre&gt;
 * 
 */
@XmlType(name = "UomTemperatureType")
@XmlEnum
public enum UomTemperatureType {


    /**
     * Degrees Celsius.
     * 
     */
    C,

    /**
     * Degrees Fahrenheit.
     * 
     */
    F,

    /**
     * Degrees Kelvin.
     * 
     */
    K,

    /**
     * Degrees Rankine.
     * 
     */
    R;

    public String value() {
        return name();
    }

    public static UomTemperatureType fromValue(String v) {
        return valueOf(v);
    }

}
