//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.base;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The reference quantities used to express the value of volume. [ISO 19103, chapter 6.5.7.16]
 * 
 * &lt;p&gt;Java class for UomVolumeType&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * &lt;pre&gt;{&#064;code
 * &lt;simpleType name="UomVolumeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="L"/&gt;
 *     &lt;enumeration value="US_GAL"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * }&lt;/pre&gt;
 * 
 */
@XmlType(name = "UomVolumeType")
@XmlEnum
public enum UomVolumeType {


    /**
     * Litre.
     * 
     */
    L,

    /**
     * US Gallon.
     * 
     */
    US_GAL;

    public String value() {
        return name();
    }

    public static UomVolumeType fromValue(String v) {
        return valueOf(v);
    }

}
