//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.base;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The reference quantities used to express the value of vertical rate.
 * 
 * &lt;p&gt;Java class for UomVerticalRateType&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * &lt;pre&gt;{&#064;code
 * &lt;simpleType name="UomVerticalRateType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="FT_MIN"/&gt;
 *     &lt;enumeration value="M_SEC"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * }&lt;/pre&gt;
 * 
 */
@XmlType(name = "UomVerticalRateType")
@XmlEnum
public enum UomVerticalRateType {


    /**
     * Feet per minute.
     * 
     */
    FT_MIN,

    /**
     * Metres per second.
     * 
     */
    M_SEC;

    public String value() {
        return name();
    }

    public static UomVerticalRateType fromValue(String v) {
        return valueOf(v);
    }

}
