//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.base;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A code indicating the reference for a vertical distance. [AIXM 5.1]
 * 
 * &lt;p&gt;Java class for VerticalReferenceType&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * &lt;pre&gt;{&#064;code
 * &lt;simpleType name="VerticalReferenceType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="SFC"/&gt;
 *     &lt;enumeration value="W84"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * }&lt;/pre&gt;
 * 
 */
@XmlType(name = "VerticalReferenceType")
@XmlEnum
public enum VerticalReferenceType {


    /**
     * The distance measured from the surface of the Earth (equivalent to AGL - Above Ground Level). [AIXM 5.1]
     * 
     */
    SFC("SFC"),

    /**
     * The distance measured from the WGS84 ellipsoid. [AIXM 5.1]
     * 
     */
    @XmlEnumValue("W84")
    W_84("W84");
    private final String value;

    VerticalReferenceType(String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static VerticalReferenceType fromValue(String v) {
        for (VerticalReferenceType c: VerticalReferenceType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
