//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.base;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Represents a vertical range with a lower and/or upper bound.
 * 
 * &lt;p&gt;Java class for VerticalRangeType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="VerticalRangeType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="extension" type="{http://www.fixm.aero/base/4.3}VerticalRangeExtensionType" maxOccurs="2000" minOccurs="0"/&gt;
 *         &lt;element name="lowerBound" type="{http://www.fixm.aero/base/4.3}FlightLevelOrAltitudeChoiceType" minOccurs="0"/&gt;
 *         &lt;element name="upperBound" type="{http://www.fixm.aero/base/4.3}FlightLevelOrAltitudeChoiceType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VerticalRangeType", propOrder = {
    "extension",
    "lowerBound",
    "upperBound"
})
public class VerticalRangeType
    implements Serializable
{

    private static final long serialVersionUID = 1L;
    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     */
    @XmlElement(nillable = true)
    protected List<VerticalRangeExtensionType> extension;
    /**
     * Lower bound of the vertical range.
     * 
     */
    @XmlElementRef(name = "lowerBound", namespace = "http://www.fixm.aero/base/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<FlightLevelOrAltitudeChoiceType> lowerBound;
    /**
     * Upper bound of the vertical range.
     * 
     */
    @XmlElementRef(name = "upperBound", namespace = "http://www.fixm.aero/base/4.3", type = JAXBElement.class, required = false)
    protected JAXBElement<FlightLevelOrAltitudeChoiceType> upperBound;

    /**
     * An extension hook for attaching extension (non-core) classes.
     * 
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VerticalRangeExtensionType }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<VerticalRangeExtensionType> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * Lower bound of the vertical range.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link FlightLevelOrAltitudeChoiceType }{@code >}
     *     
     */
    public JAXBElement<FlightLevelOrAltitudeChoiceType> getLowerBound() {
        return lowerBound;
    }

    /**
     * Sets the value of the lowerBound property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link FlightLevelOrAltitudeChoiceType }{@code >}
     *     
     * @see #getLowerBound()
     */
    public void setLowerBound(JAXBElement<FlightLevelOrAltitudeChoiceType> value) {
        this.lowerBound = value;
    }

    /**
     * Upper bound of the vertical range.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link FlightLevelOrAltitudeChoiceType }{@code >}
     *     
     */
    public JAXBElement<FlightLevelOrAltitudeChoiceType> getUpperBound() {
        return upperBound;
    }

    /**
     * Sets the value of the upperBound property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link FlightLevelOrAltitudeChoiceType }{@code >}
     *     
     * @see #getUpperBound()
     */
    public void setUpperBound(JAXBElement<FlightLevelOrAltitudeChoiceType> value) {
        this.upperBound = value;
    }

}
