//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package aero.fixm.base;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Indicates that no specific altitude has been provided for a flight operated under visual flight rules.
 * 
 * &lt;p&gt;Java class for VisualFlightRulesLevelType&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * &lt;pre&gt;{&#064;code
 * &lt;simpleType name="VisualFlightRulesLevelType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="VFR"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * }&lt;/pre&gt;
 * 
 */
@XmlType(name = "VisualFlightRulesLevelType")
@XmlEnum
public enum VisualFlightRulesLevelType {


    /**
     * No specific altitude has been provided for this VFR flight.
     * 
     */
    VFR;

    public String value() {
        return name();
    }

    public static VisualFlightRulesLevelType fromValue(String v) {
        return valueOf(v);
    }

}
